add check sys

diff --git a/scripts/_util b/scripts/_util
--- a/scripts/_util
+++ b/scripts/_util
@@ -28,9 +28,15 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+##
+## Relative paths
+##
 _0=$(basename "${0}")
+_D0=$(dirname "${0}")
 
-
+err() {
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
+}
 
 ##
 ## function Check_Swarm
@@ -39,7 +45,7 @@ _0=$(basename "${0}")
 Check_Swarm()
 {
   if ! docker stack ls &> /dev/null ; then
-    echo "${_0}: Docker Swarm is not inited"
+    err "${_0}: Docker Swarm is not inited"
     exit 1
   fi
 }
@@ -52,7 +58,7 @@ Check_Swarm()
 Check_Docker()
 {
   if ! docker info &> /dev/null ; then
-    echo "${_0}: Docker is not running"
+    err "${_0}: Docker is not running"
     exit 1
   fi
 }
@@ -64,7 +70,7 @@ Check_Docker()
 Check_LocalPersistPlugin()
 {
   if ! docker volume create -d local-persist -o mountpoint=.config/lptest --name=lptest &> /dev/null ; then
-    echo "${_0}: The local-persist volume plugin is not available. See readme for instructions."
+    err "${_0}: The local-persist volume plugin is not available. See readme for instructions."
     exit 1
   fi
 }
@@ -76,8 +82,8 @@ Check_LocalPersistPlugin()
 Check_Secret()
 {
   if ! docker secret inspect ${1} &> /dev/null ; then
-    echo "${1}: Docker Secret has not been installed."
-    echo "Run configure and install scripts."
+    err "${1}: Docker Secret has not been installed."
+    err "     Run configure and install scripts."
     exit 1
   fi
 
@@ -94,7 +100,7 @@ Add_Secret()
   fi
   echo "Storing ${NAME} as a docker secret .."
   if ! echo ${VALUE} | docker secret create ${NAME} - ; then
-    echo "Docker secret creation failed for ${NAME}"
+    err "Docker secret creation failed for ${NAME}"
     return 1
   else
     return 0
@@ -103,9 +109,9 @@ Add_Secret()
 
 Check_Volume()
 {
-    if ! docker volume inspect ${1} &> /dev/null  ; then
-      echo "${1}: Docker Volume has not been installed."
-      echo "Run generate and install scripts."
+    if ! docker volume inspect ${1} &> /dev/null; then
+      err "${1}: Docker Volume has not been installed."
+      err "${1}: Run generate and install scripts."
       exit 1
     fi
 }
@@ -113,9 +119,9 @@ Check_Volume()
 
 Check_Config()
 {
-    if ! docker config inspect ${1} &> /dev/null ; then
-      echo "${1}: Config file is missing. Run configure and install scripts.."
-      echo "Run generate and install scripts."
+    if ! docker config inspect ${1} &> /dev/null; then
+      err "${1}: Config file is missing. Run configure and install scripts.."
+      err "${1}: Run generate and install scripts."
       exit 1
     fi
 }
@@ -123,8 +129,8 @@ Check_Config()
 Check_Network()
 {
     if ! docker network inspect ${1} &> /dev/null  ; then
-      echo "${1}: Docker network has not been installed."
-      echo "Run generate and install scripts."
+      err "${1}: Docker network has not been installed."
+      err "${1}: Run generate and install scripts."
       exit 1
     fi
 }
@@ -136,8 +142,8 @@ Check_Network()
 Check_Installed()
 {
   while [ "X${1}" != "X" ]; do
-    if ! which "${1}" &> /dev/null ; then
-      echo "${_0}: ${1} not on the PATH (${PATH})"
+    if ! which "${1}" &> /dev/null; then
+      err "${_0}: ${1} not on the PATH (${PATH})"
       exit 1
     fi
     shift
@@ -238,12 +244,11 @@ is_yes() {
     fi
 }
 
-is_true() {
-    local WORD="${1}"
-    if [ "X${WORD}" = Xt* -o "X${WORD}" = XT* ]; then
-        return 0
+to_yes_no() {
+    if [ ${1} ]; then
+        echo "Y"
     else
-        return 1
+        echo "N"
     fi
 }
 
diff --git a/scripts/check_sys b/scripts/check_sys
--- a/scripts/check_sys
+++ b/scripts/check_sys
@@ -1,4 +1,4 @@
-#!/usr/local/bin/zsh
+#!/bin/bash
 # ---------------------------------------------------------------------------
 # check_sys - Check the host system for all necessary components for running LOCKSS stack.
 #
@@ -37,7 +37,11 @@
 
 PROGNAME=${0##*/}
 VERSION="1.0"
-
+##
+## Relative paths
+##
+_0=$(basename "${0}")
+_D0=$(dirname "${0}")
 ##
 ## Load _util
 ##
@@ -92,28 +96,61 @@ _EOF_
 }
 
 ensure_lockss_user() {
-  grep -q ^lockss: /etc/passwd || ( if useradd -s /bin/false lockss ; then mkdir -p /home/lockss ; chown lockss:lockss /home/lockss ; chmod 755 /home/lockss ; echo "Created user 'lockss'" ; else echo "Can't create user lockss" ; exit 1 ; fi )
+  if ! $(grep -q ^lockss: /etc/passwd) ; then
+    echo "${_0}: The is no 'lockss' user account."
+    ask_for_input "OK to create account for 'lockss' user?" Y
+    if is_yes "${ANS}" ; then
+      case `uname -s ` in
+        Linux)
+          if useradd -s /bin/false lockss ; then
+            mkdir -p /home/lockss
+            chown lockss:lockss /home/lockss
+            chmod 755 /home/lockss
+            echo "Created user 'lockss'" 
+          else 
+            err "Can't create user lockss" 
+            exit 1;
+          fi
+          ;;
+        Darwin)
+          dscl . create /Users/lockss uid 799
+          dscl . create /Users/lockss gid 799
+          dscl . create /Users/lockss shell /bin/bash
+          dscl . create /Users/lockss home /Users/lockss
+          dscl . create /Users/lockss realname "lockss"
+          dscl . create /Groups/lockss gid 799
+          dscl . create /Groups/lockss passwd \*
+          passwd lockss
+          ;;
+        *)
+          err "Unsupported system, create the user lockss in group lockss manually."
+          ;;
+      esac
+    fi
+  fi
 }
 
 ensure_docker() {
   if ! which "${1}" &> /dev/null ; then
-     echo "${_0}: Docker does not appear to be on the path."
-     ask_for_input "OK to install Docker?" Y
+    echo "${_0}: Docker does not appear to be on the path."
+    ask_for_input "OK to install Docker?" Y
     if is_yes "${ANS}"; then
       case `uname -s ` in
-      Linux)
-        curl -fsSL https://get.docker.com -o get-docker.sh
-        sh get-docker.sh
-        ;;
-      Darwin)
-        echo "Docker mac must be installed  as an application available from DockerHub."
-        echo "If you have homebrew: `homebrew cask install docker`"
-        echo "Full instructions for Mac, can be found in the README."
-        exit 1
-        ;;
+        Linux)
+          curl -fsSL https://get.docker.com -o get-docker.sh
+          $(sh get-docker.sh)
+          ;;
+        Darwin)
+          err "Docker mac must be installed  as an application available from DockerHub."
+          err "If you have homebrew: `homebrew cask install docker`"
+          err "Full instructions for Mac, can be found in the README."
+          exit 1
+          ;;
+        *)
+          err "Unsupported system, install docker manually."
       esac
+    fi
  fi
-
 }
 
 
diff --git a/scripts/configure-lockss b/scripts/configure-lockss
--- a/scripts/configure-lockss
+++ b/scripts/configure-lockss
@@ -67,7 +67,7 @@ configure_services() {
     if [ "X${USE_LOCKSS_CFG}" = X ]; then
          USE_LOCKSS_CFG=true
     fi
-    ask_for_input "Use LOCKSS Config Service?" ${USE_LOCKSS_CFG}
+    ask_for_input "Use LOCKSS Config Service?" $(to_yes_no ${USE_LOCKSS_CFG})
     if is_yes "${ANS}"; then
         USE_LOCKSS_CFG=true
     else
@@ -77,7 +77,7 @@ configure_services() {
     if [ "X${USE_LOCKSS_MDQ}" = X ]; then
          USE_LOCKSS_MDQ=true
     fi
-    ask_for_input "Use LOCKSS Metadata Service?" ${USE_LOCKSS_MDQ}
+    ask_for_input "Use LOCKSS Metadata Service?" $(to_yes_no ${USE_LOCKSS_MDQ})
     if is_yes "${ANS}"; then
         USE_LOCKSS_MDQ=true
     else
@@ -87,7 +87,7 @@ configure_services() {
     if [ "X${USE_LOCKSS_MDX}" = X ]; then
          USE_LOCKSS_MDX=true
     fi
-    ask_for_input "Use LOCKSS Metadata Extractor Service?" ${USE_LOCKSS_MDX}
+    ask_for_input "Use LOCKSS Metadata Extractor Service?" $(to_yes_no ${USE_LOCKSS_MDX})
     if is_yes "${ANS}"; then
         USE_LOCKSS_MDX=true
     else
@@ -97,7 +97,7 @@ configure_services() {
     if [ "X${USE_LOCKSS_REPO}" = X ]; then
          USE_LOCKSS_REPO=true
     fi
-    ask_for_input "Use LOCKSS Repository Service?" ${USE_LOCKSS_REPO}
+    ask_for_input "Use LOCKSS Repository Service?" $(to_yes_no ${USE_LOCKSS_REPO})
     if is_yes "${ANS}"; then
         USE_LOCKSS_REPO=true
     else
@@ -107,7 +107,7 @@ configure_services() {
     if [ "X${USE_LOCKSS_POSTGRES}"=X ]; then
          USE_LOCKSS_POSTGRES=true
     fi
-    ask_for_input "Use LOCKSS Postgres DB Service?" ${USE_LOCKSS_POSTGRES}
+    ask_for_input "Use LOCKSS Postgres DB Service?" $(to_yes_no ${USE_LOCKSS_POSTGRES})
     if is_yes "${ANS}"; then
         USE_LOCKSS_POSTGRES=true
         LOCKSS_POSTGRES_HOST='lockss-postgres'
@@ -171,7 +171,7 @@ configure_services() {
     if [ "X${USE_LOCKSS_SOLR}" = X ]; then
          USE_LOCKSS_SOLR=true
     fi
-    ask_for_input "Use LOCKSS SOLR Service?" ${USE_LOCKSS_SOLR}
+    ask_for_input "Use LOCKSS SOLR Service?" $(to_yes_no ${USE_LOCKSS_SOLR})
     if is_yes "${ANS}"; then
         USE_LOCKSS_SOLR=true
         LOCKSS_SOLR_HOST='lockss-solr'
@@ -422,12 +422,12 @@ LOCKSS_ADMIN_PASSWD="${LOCKSS_ADMIN_PASSWD}"
 LOCKSS_DB_PASSWD="${LOCKSS_DB_PASSWD}"
 LOCKSS_PROXY_PORT="${LOCKSS_PROXY_PORT}"
 LOCKSS_TMPDIR="${LOCKSS_TMPDIR}"
-LOCKSS_POSTGRES_HOST=${LOCKSS_POSTGRES_HOST}
-LOCKSS_POSTGRES_PORT=${LOCKSS_POSTGRES_PORT}
-LOCKSS_POSTGRES_USER=${LOCKSS_POSTGRES_USER}
-LOCKSS_POSTGRES_SCHEMA=${LOCKSS_POSTGRES_SCHEMA}
-LOCKSS_DBNAME_PREFIX=${LOCKSS_DBNAME_PREFIX}
-LOCKSS_SOLR_HOST=${LOCKSS_SOLR_HOST}
+LOCKSS_POSTGRES_HOST="${LOCKSS_POSTGRES_HOST}"
+LOCKSS_POSTGRES_PORT="${LOCKSS_POSTGRES_PORT}"
+LOCKSS_POSTGRES_USER="${LOCKSS_POSTGRES_USER}"
+LOCKSS_POSTGRES_SCHEMA="${LOCKSS_POSTGRES_SCHEMA}"
+LOCKSS_DBNAME_PREFIX="${LOCKSS_DBNAME_PREFIX}"
+LOCKSS_SOLR_HOST="${LOCKSS_SOLR_HOST}"
 LOCKSS_SOLR_PORT=${LOCKSS_SOLR_PORT}
 LOCKSS_SOLR_CORE_REPO=${LOCKSS_SOLR_CORE_REPO}
 LOCKSS_CLEAR_TMPDIR="${LOCKSS_CLEAR_TMPDIR:-yes}"
@@ -469,12 +469,12 @@ EOF
             CONFIG_OK=Y
             FILT_CONFIG=$(mktemp /tmp/filtconfig.XXXXX)
             egrep -sv 'PASSW(OR)?D.*=' <${1} >>${FILT_CONFIG}
-            if ! mail -s "Config for ${2}@${LOCKSS_HOSTNAME}" ${LOCKSS_EMAIL} ${LOCKSS_TEAM} <${FILT_CONFIG}; then
-                echo "Sending mail failed. Please check mail configuration."
-                UNSENT_FILE=/tmp/unsent-lockss-config
-                cp ${FILT_CONFIG} ${UNSENT_FILE}
-                echo "Please also send ${UNSENT_FILE} to ${LOCKSS_TEAM}."
-            fi
+#           if ! mail -s "Config for ${2}@${LOCKSS_HOSTNAME}" ${LOCKSS_EMAIL} ${LOCKSS_TEAM} <${FILT_CONFIG}; then
+#               echo "Sending mail failed. Please check mail configuration."
+#               UNSENT_FILE=/tmp/unsent-lockss-config
+#               cp ${FILT_CONFIG} ${UNSENT_FILE}
+#              echo "Please also send ${UNSENT_FILE} to ${LOCKSS_TEAM}."
+#            fi
             rm -f ${FILT_CONFIG}
 
        fi
@@ -484,9 +484,6 @@ EOF
 ###
 # Start
 ###
-#echo "$(date) Checking system installs"
-#. check_sys
-
 CONFIG_USER=$(whoami)
 OS_TYPE=$(uname -s)
 case ${OS_TYPE} in
@@ -523,6 +520,9 @@ case "${1}" in
   [1-9]) CONFIG_COUNT="${1}" ; break ;;
   *) echo "$(date) Invalid number of parallel stacks: ${1}" ; exit 1 ;;
 esac
+
+echo "$(date) Checking system installs"
+. check_sys
 
 #build config file
 echo "building config for ${CONFIG_COUNT} stacks on ${OS_TYPE} for user ${CONFIG_USER}..."
