Extract dir-creation/check into separate script

diff --git a/scripts/_util b/scripts/_util
--- a/scripts/_util
+++ b/scripts/_util
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# Copyright (c) 2000-2018, Board of Trustees of Leland Stanford Jr. University
+# Copyright (c) 2000-2021, Board of Trustees of Leland Stanford Jr. University
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without modification,
@@ -381,7 +381,7 @@ read_config() {
   IFS='
 '
   for A in $(sed -e '/[a-zA-Z0-9_]* *= *.*/!d' -e 's/\([a-zA-Z0-9_]*\) *= *\(.*\)/\
-\1=\2/' $1); do
+\1=\2/' "${FILE}"); do
     eval "$A"
   done
   IFS="${OLD_IFS}"
@@ -491,6 +491,49 @@ is_pos() {
   return $?
 }
 
+# setup_storage_dirs CONF_FILE CONFIG_USER
+# return nonzero if any errors
+setup_storage_dirs() {
+  local CONF_FILE="$1"
+  local USER="$2"
+  local ERRORS=""
+  echo "Checking content storage directory(s)"
+  read_config ${CONF_FILE}
+  IFS=';' read -r -a repoPaths <<< "${LOCKSS_REPO_HOST_DIRS}"
+
+  for dir in "${repoPaths[@]}"; do
+    if ! init_one_dir "${dir}" ${USER} 750; then
+        echo "${dir} cannot be created or written by ${USER}." >&2
+        ERRORS=1
+    fi
+  done
+  if [ "${LOCKSS_LOGS_DIR}" != "${LOCKSS_DATA_DIR}" ]; then
+      if ! init_one_dir ${LOCKSS_LOGS_DIR} ${USER} 755; then
+        echo "${dir} cannot be created or written by ${USER}." >&2
+        ERRORS=1
+      fi
+  fi
+  if [ "${LOCKSS_TMPDIR}" != "${LOCKSS_DATA_DIR}" ]; then
+      if ! init_one_dir ${LOCKSS_TMPDIR} ${USER} 750; then
+        echo "${dir} cannot be created or written by ${USER}." >&2
+        ERRORS=1
+      fi
+  fi
+  if [ "${LOCKSS_SCRIPT_LOG_DIR}" != "${LOCKSS_DATA_DIR}" ]; then
+      if ! init_one_dir ${LOCKSS_SCRIPT_LOG_DIR} ${USER} 755; then
+        echo "${dir} cannot be created or written by ${USER}." >&2
+        ERRORS=1
+      fi
+  fi
+  if [ -n "$ERRORS" ]; then
+      echo "Some directories could not be set up correctly.  Please either" >&2
+      echo " rerun configure-lockss and specify different directories, or" >&2
+      echo " fix the ownership/permission problems then run setup-storage." >&2
+      return 1
+  fi
+  return 0
+}
+
 # init_one_dir dir user mode
 init_one_dir() {
   local DIR="$1"
@@ -523,9 +566,10 @@ init_one_dir() {
   if check_writable "${DIR}" $USER; then
     echo "${DIR} exists and is writable by ${USER}"
   else
-    ask_for_input "${DIR} is not writable; shall I chown it?" Y
+    ask_for_input "${DIR} is not writable; shall I chown/chmod it?" Y
     if is_yes "${ANS}"; then
       chown ${USER} "${DIR}"
+      chmod ${MODE} "${DIR}"
       if check_writable "${DIR}" $USER; then
         return 0
       else
@@ -537,6 +581,7 @@ init_one_dir() {
       echo "Please ensure that ${DIR} is writable by user ${USER};"
       echo " LOCKSS will not run properly without it."
     fi
+    return 1
   fi
 }
 
diff --git a/scripts/configure-lockss b/scripts/configure-lockss
--- a/scripts/configure-lockss
+++ b/scripts/configure-lockss
@@ -2,7 +2,7 @@
 #---------------------------------------------------------------------------
 # configure-lockss - Collect host system information needed to run LOCKSS stack(s).
 
-# Copyright (c) 2019, Board of Trustees of Leland Stanford Jr. University
+# Copyright (c) 2019-2021, Board of Trustees of Leland Stanford Jr. University
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without modification,
@@ -41,6 +41,7 @@ VERSION="1.0"
 if [ -n "${BYPASS_ALL_CHECKS}" ]; then
   BYPASS_CHECK_USER=1
   BYPASS_KUBE_COMMANDS=1
+  BYPASS_MAIL=1
 fi
 
 ##
@@ -586,27 +587,9 @@ build_config_file() {
         exit 1
       fi
       Store_All_Secrets
-      echo "Checking content storage directory(s)"
-      for dir in "${curPaths[@]}"; do
-        if ! init_one_dir ${dir} $2 750; then
-          err_exit"${dir} cannot be created or written by $2.  Please fix permissions."
-        fi
-      done
-      if [ "${LOCKSS_LOGS_DIR}" != "${LOCKSS_DATA_DIR}" ]; then
-        if ! init_one_dir ${LOCKSS_LOGS_DIR} $2 755; then
-          err_exit "${dir} cannot be created or written by $2.  Please fix permissions."
-        fi
-      fi
-      if [ "${LOCKSS_TMPDIR}" != "${LOCKSS_DATA_DIR}" ]; then
-        if ! init_one_dir ${LOCKSS_TMPDIR} $2 750; then
-          err_exit "${dir} cannot be created or written by $2.  Please fix permissions."
-        fi
-      fi
-      if [ "${LOCKSS_SCRIPT_LOG_DIR}" != "${LOCKSS_DATA_DIR}" ]; then
-        if ! init_one_dir ${LOCKSS_SCRIPT_LOG_DIR} $2 755; then
-          err_exit "${dir} cannot be created or written by $2.  Please fix permissions."
-        fi
-      fi
+
+      local STORAGE_ERRORS=
+      setup_storage_dirs ${SYSTEM_CONF_FILE} ${CONFIG_USER} || STORAGE_ERRORS=1
 
       rm -f ${TMP_CONFIG}
       echo Done
@@ -615,11 +598,13 @@ build_config_file() {
       egrep -sv 'PASSW(OR)?D.*=' <${1} >>${FILT_CONFIG}
       mail_sent=""
       if [ $(command -v mail) >/dev/null ]; then
-        if mail -s "Config for ${2}@${LOCKSS_HOSTNAME}" ${LOCKSS_EMAIL} ${LOCKSS_TEAM} <${FILT_CONFIG}; then
-          mail_sent=1
-        else
-          echo "The attempt to mail configuration failed.  Please check your mail configuration."
-        fi
+          if [ -z "${BYPASS_MAIL}" ]; then
+              if mail -s "Config for ${2}@${LOCKSS_HOSTNAME}" ${LOCKSS_EMAIL} ${LOCKSS_TEAM} <${FILT_CONFIG}; then
+                  mail_sent=1
+              else
+                echo "The attempt to mail configuration failed.  Please check your mail configuration."
+              fi
+          fi
       else
         echo "The 'mail' command isn't installed (or isn't on the PATH)."
       fi
@@ -631,6 +616,13 @@ build_config_file() {
       rm -f ${FILT_CONFIG}
     fi
   done
+  if [ -n "${STORAGE_ERRORS}" ]; then
+      echo
+      echo "Storage directories have not been set up correctly.  Please"
+      echo "fix the problems and run setup-storage before attempting to"
+      echo "start the services."
+      return 1
+  fi
 }
 
 setup_k8s_cmd() {
@@ -728,5 +720,10 @@ esac
 
 #build config file
 echo "building config for ${CONFIG_COUNT} stacks on ${OS_TYPE} for user ${CONFIG_USER}..."
-build_config_file ${SYSTEM_CONF_FILE} ${CONFIG_USER} ${CONFIG_COUNT}
-echo "$(date) Run scripts/start-lockss to launch the LOCKSS stack 'lockss-stack'..."
+if build_config_file ${SYSTEM_CONF_FILE} ${CONFIG_USER} ${CONFIG_COUNT} ; then
+    echo "$(date) Run scripts/start-lockss to launch the LOCKSS stack 'lockss-stack'..."
+    exit 0
+else
+  echo "Exiting with errors"
+  exit 1
+fi
