add file logging elimate the generate-lockss script renames shutdown-lockss => stop-lockss cleanup scripts

diff --git a/scripts/_util b/scripts/_util
--- a/scripts/_util
+++ b/scripts/_util
@@ -46,6 +46,17 @@ DOCKER_CONFIGS_DIR="${CONFIG_DIR}/configs"
 TEMPLATES_DIR="${CONFIG_DIR}/templates"
 USEROPTS_DIR="${CONFIG_DIR}/useropts"
 
+# load log4sh
+if [ -r ${LIB_DIR}/log4sh ]; then
+  LOG4SH_CONFIGURATION='none' . ${LIB_DIR}/log4sh
+else
+  echo "ERROR: could not load (log4sh)" >&2
+  exit 1
+fi
+
+# change the default message level from ERROR to INFO
+logger_setLevel INFO
+
 err() {
   echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
 }
@@ -58,6 +69,7 @@ err_exit() {
 msg() {
   echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@"
 }
+
 
 #Check_Runnable()
 #{
diff --git a/scripts/deploy-lockss b/scripts/deploy-lockss
--- a/scripts/deploy-lockss
+++ b/scripts/deploy-lockss
@@ -72,7 +72,7 @@ clean_up() { # Perform pre-exit housekeeping
 }
 
 error_exit() {
-  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+  logger_error "${PROGNAME}: ${1:-"Unknown Error"}" >&2
   clean_up
   exit 1
 }
@@ -172,7 +172,7 @@ init_service_arrays() {
 
 # Check our secrets
 check_installed_secrets() {
-  echo "checking installed secrets..."
+  logger_info "checking installed secrets..."
   Check_Secret 'lockss-postgres-pass'
   Check_Secret 'lockss-ui-pass'
   Check_Secret 'lockss-auth'
@@ -182,7 +182,7 @@ check_installed_volumes() {
   local stack=$1
   # Check the mountpoints
   for svc in "${svcs[@]}"; do
-    echo "checking docker mountpoints for $stack-${svc}..."
+    logger_info "checking docker mountpoints for $stack-${svc}..."
     Check_Volume "$stack-${svc}-data"
     Check_Volume "$stack-${svc}-logs  "
   done
@@ -198,7 +198,7 @@ deploy_stack() {
   set +a
   pushd . &>/dev/null
   for svc in "${deploy_service_names[@]}"; do
-    echo "Deploying service from ${svc}..."
+    logger_trace "Deploying service from ${svc}..."
     $KUBECTL apply -f "${DOCKER_CONFIGS_DIR}/$stack/svcs/${svc}.yaml"
 #ß    $KUBECTL expose deployment $svc
   done
@@ -226,7 +226,7 @@ while [[ -n $1 ]]; do
   -a | --args)
     shift
     export ARGS_ADDITIONAL="$1"
-    msg "Adding additional runtime args $ARGS_ADDITIONAL"
+    logger_debug "Adding additional runtime args $ARGS_ADDITIONAL"
     shift
     ;;
   [1-9])
diff --git a/scripts/start-lockss b/scripts/start-lockss
--- a/scripts/start-lockss
+++ b/scripts/start-lockss
@@ -54,7 +54,7 @@ clean_up() { # Perform pre-exit housekeeping
 }
 
 error_exit() {
-	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+	logger_error  "${PROGNAME}: ${1:-"Unknown Error"}" >&2
 	clean_up
 	exit 1
 }
@@ -110,18 +110,18 @@ while [[ -n $1 ]]; do
       help_message; graceful_exit ;;
     -u | --update)
       UPDATE_ARG="-u"
-      msg "Forcing update of LOCKSS docker images"
+      logger_info "Forcing update of LOCKSS docker images"
       ;;
     -a | --args)
       shift
       export ARGS_ADDITIONAL="$1"
-      echo "Adding additional runtime args $ARGS_ADDITIONAL";
+      logger_info "Adding additional runtime args $ARGS_ADDITIONAL";
     ;;
     -* | --*)
       usage
       error_exit "Unknown option $1" ;;
     *)
-      echo "Argument $1 to process..." ;;
+      logger_trace "Argument $1 to process..." ;;
   esac
   shift
 done
@@ -134,10 +134,10 @@ if $(am_i_root); then
 fi
 
 if $(is_lockss_running); then
-  msg "There is already a running lockss stack."
+  logger_warn "There is already a running lockss stack."
   ask_for_input "Okay to stop the lockss-stack and restart?" "Y"
   if is_yes "${ANS}"; then
-    "${_D0}"/shutdown-lockss && sleep 5 && msg "Preparing to start stack..."
+    "${_D0}"/stop-lockss && sleep 10 && logger_info "Preparing to start stack..."
   else
     error_exit "Call shutdown-lockss and then run start-lockss again."
   fi
@@ -145,10 +145,8 @@ fi
 
 echo "Scripts dir ${SCRIPTS_DIR}"
 
-"${SCRIPTS_DIR}"/generate-lockss ${UPDATE_ARG} &&
-"${SCRIPTS_DIR}"/assemble-lockss &&
+"${SCRIPTS_DIR}"/assemble-lockss ${UPDATE_ARG} &&
 "${SCRIPTS_DIR}"/deploy-lockss -a "$ARGS_ADDITIONAL"
-
 
 graceful_exit
 
