fix merge conflict

diff --git a/scripts/_util b/scripts/_util
--- a/scripts/_util
+++ b/scripts/_util
@@ -28,18 +28,41 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
+##
+## Relative paths
+##
 _0=$(basename "${0}")
+_D0=$(dirname "${0}")
 
+err() {
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
+}
+
+err_exit() {
+    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@" >&2
+    exit 1
+}
+
+msg() {
+  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@"
+}
+
+Check_Runnable()
+{
+  Check_Installed 'docker'
+  Check_Docker
+  Check_Swarm
+  Check_LocalPersistPlugin
+}
 
 ##
-## function Check_SWarm
+## function Check_Swarm
 ##
 
-Check_Stack()
+Check_Swarm()
 {
   if ! docker stack ls &> /dev/null ; then
-    echo "${_0}: Docker Swarm is not inited"
-    exit 1
+    err_exit "${_0}: Docker Swarm is not inited"
   fi
 }
 
@@ -51,8 +74,7 @@ Check_Stack()
 Check_Docker()
 {
   if ! docker info &> /dev/null ; then
-    echo "${_0}: Docker is not running"
-    exit 1
+    err_exit "${_0}: Docker is not running"
   fi
 }
 
@@ -63,21 +85,19 @@ Check_Docker()
 Check_LocalPersistPlugin()
 {
   if ! docker volume create -d local-persist -o mountpoint=.config/lptest --name=lptest &> /dev/null ; then
-    echo "${_0}: The local-persist volume plugin is not available. See readme for instructions."
-    exit 1
+    err_exit "${_0}: The local-persist volume plugin is not available. See readme for instructions."
   fi
 }
 
 ##
 ## Check For installed secret
-## 
+##
 
 Check_Secret()
 {
   if ! docker secret inspect ${1} &> /dev/null ; then
-    echo "${1}: Docker Secret has not been installed."
-    echo "Run configure and install scripts."
-    exit 1
+    err "${1}: Docker Secret has not been installed."
+    err_exit "     Run configure and install scripts."
   fi
 
 }
@@ -87,13 +107,13 @@ Add_Secret()
   local NAME="${1}"
   local VALUE="${2}"
 
-  if docker secret inspect ${NAME} &> /dev/null; then
+  if docker secret inspect "${NAME}" &> /dev/null; then
     echo "removing stored password for ${NAME}"
-    docker secret rm ${NAME}
+    docker secret rm "${NAME}"
   fi
   echo "Storing ${NAME} as a docker secret .."
-  if ! echo ${VALUE} | docker secret create ${NAME} - ; then
-    echo "Docker secret creation failed for ${NAME}"
+  if ! echo -n "${VALUE}" | docker secret create "${NAME}" - ; then
+    err "Docker secret creation failed for ${NAME}"
     return 1
   else
     return 0
@@ -102,9 +122,9 @@ Add_Secret()
 
 Check_Volume()
 {
-    if ! docker volume inspect ${1} &> /dev/null  ; then
-      echo "${1}: Docker Volume has not been installed."
-      echo "Run generate and install scripts."
+    if ! docker volume inspect ${1} &> /dev/null; then
+      err "${1}: Docker Volume has not been installed."
+      err "${1}: Run lockss-install script."
       exit 1
     fi
 }
@@ -112,9 +132,9 @@ Check_Volume()
 
 Check_Config()
 {
-    if ! docker config inspect ${1} &> /dev/null ; then
-      echo "${1}: Config file is missing. Run configure and install scripts.."
-      echo "Run generate and install scripts."
+    if ! docker config inspect ${1} &> /dev/null; then
+      err "${1}: Config file is missing. Run configure and install scripts.."
+      err "${1}: Run lockss-install script."
       exit 1
     fi
 }
@@ -122,8 +142,8 @@ Check_Config()
 Check_Network()
 {
     if ! docker network inspect ${1} &> /dev/null  ; then
-      echo "${1}: Docker network has not been installed."
-      echo "Run generate and install scripts."
+      err "${1}: Docker network has not been installed."
+      err "${1}: Run lockss-install script."
       exit 1
     fi
 }
@@ -135,8 +155,8 @@ Check_Network()
 Check_Installed()
 {
   while [ "X${1}" != "X" ]; do
-    if ! which "${1}" &> /dev/null ; then
-      echo "${_0}: ${1} not on the PATH (${PATH})"
+    if ! which "${1}" &> /dev/null; then
+      err "${_0}: ${1} not on the PATH (${PATH})"
       exit 1
     fi
     shift
@@ -190,6 +210,31 @@ Wait_For_Port()
   done
 }
 
+# check if running as root
+am_i_root() {
+    [ "$(id -u)" -eq 0 ]
+}
+
+is_lockss_running() {
+  [ "$(docker stack ls | grep 'lockss-stack')" -eq 0 ]
+}
+
+#
+# Read existing config info and populate environment
+# Must be run before LOCKSS daemon can be started
+#
+read_config() {
+    local FILE="$1"
+    local OLD_IFS="${IFS}"
+    IFS='
+'
+    for A in $(sed -e '/[a-zA-Z0-9_]* *= *.*/!d' -e 's/\([a-zA-Z0-9_]*\) *= *\(.*\)/\
+\1=\2/' $1); do
+        eval "$A"
+    done
+    IFS="${OLD_IFS}"
+}
+
 ask_for_input() {
     echo "$1: [$2] "
     read ANS
@@ -213,11 +258,20 @@ ask_for_input_shadow() {
 }
 
 is_yes() {
-    local WORD="$1"
+    local WORD="${1}"
     if [ "X${WORD}" = Xy -o "X${WORD}" = XY ]; then
         return 0
     else
         return 1
+    fi
+}
+
+to_yes_no() {
+   local WORD="${1}"
+    if [ "X${WORD}" = Xtrue -o "X${WORD}" = XTRUE ]; then
+        echo "Y"
+    else
+        echo "N"
     fi
 }
 
@@ -227,6 +281,69 @@ is_pos() {
   return $?
 }
 
+# init_one_dir dir user
+init_one_dir() {
+    local DIR="$1"
+    if [ ! -d "${DIR}" ]; then
+        ask_for_input "${DIR} does not exist; shall I create it" Y
+        if is_yes "${ANS}"; then
+            mkdir -p "${DIR}"
+            if [ "X${CONFIG_USER}" != "X${2}" ] ; then
+                chown ${2} "${DIR}"
+            fi
+            chmod 750 "${DIR}"
+            if check_writable "${DIR}" ${2} ; then
+                return 0
+            else
+                echo "${DIR} not writable by user ${2}"
+                echo " Please make it so (check parent dir execute bits)"
+                echo " LOCKSS will not run properly without it."
+            fi
+        else
+            echo "Please create ${DIR} and make it writable by user ${2};"
+            echo " LOCKSS will not run properly without it."
+        fi
+        return 0
+    fi
+    if check_writable "${DIR}" $2 ; then
+        echo "${DIR} exists and is writable by ${2}"
+    else
+        ask_for_input "${DIR} is not writable; shall I chown it" Y
+        if is_yes "${ANS}"; then
+            chown ${2} "${DIR}"
+            if check_writable "${DIR}" $2 ; then
+                return 0
+            else
+                echo "${DIR} still not writable by user ${2}"
+                echo " Please make it so (check parent dir execute bits)"
+                echo " LOCKSS will not run properly without it."
+            fi
+        else
+            echo "Please ensure that ${DIR} is writable by user ${2};"
+            echo " LOCKSS will not run properly without it."
+        fi
+    fi
+}
+
+
+# check_writable (dir, user)
+check_writable() {
+    local DIR="$1"
+    true&
+    local PROBE_FILE=${DIR}/probe_$!
+    if [ "X${CONFIG_USER}" != "X${2}" ]; then
+        SUDO="sudo -u ${2}"
+    else
+        SUDO=""
+    fi
+    if ${SUDO} touch ${PROBE_FILE} >/dev/null 2>&1; then
+        rm -f ${PROBE_FILE}
+        return 0
+    fi
+    return 1
+}
+
+#parse_ip_address inp
 parse_ip_address() {
     local INP=$1
     local OLD_IFS="${IFS}"
@@ -251,6 +368,20 @@ parse_ip_address() {
     fi
 }
 
+# read_config file
+read_config() {
+    local FILE="$1"
+    local OLD_IFS="${IFS}"
+    IFS='
+'
+    for A in `sed -e '/[a-zA-Z0-9_]* *= *.*/!d' -e 's/\([a-zA-Z0-9_]*\) *= *\(.*\)/\
+\1=\2/' $1` ; do
+        eval "$A"
+    done
+    IFS="${OLD_IFS}"
+}
+
+# valid_ip_address address
 valid_ip_address() {
     local IPADDR=`parse_ip_address "$1"`
     if [ ${IPADDR} -eq 0 ]; then
@@ -260,6 +391,9 @@ valid_ip_address() {
     fi
 }
 
+#
+# Usage: valid_subnet address
+#
 valid_subnet() {
     local INP=$1
     if ! echo ${INP} | grep -s '/' >/dev/null; then
@@ -294,3 +428,24 @@ valid_subnet() {
     fi
 }
 
+#
+# Usage: normalize_path PATH
+#
+# Remove /./ and dir/.. sequences from a pathname and write result to stdout.
+# from https://www.linuxjournal.com/content/normalizing-path-names-bash
+#
+function normalize_path()
+{
+    # Remove all /./ sequences.
+    local path=${1//\/.\//\/}
+
+    # Remove first dir/.. sequence.
+    local npath=$(echo $path | sed -e 's;[^/][^/]*/\.\./;;')
+
+    # Remove remaining dir/.. sequence.
+    while [[ $npath != $path ]]
+    do
+        path=$npath
+        npath=$(echo $path | sed -e 's;[^/][^/]*/\.\./;;')
+    done
+}
