fix broken mustache templates

diff --git a/scripts/assemble-lockss b/scripts/assemble-lockss
--- a/scripts/assemble-lockss
+++ b/scripts/assemble-lockss
@@ -52,13 +52,12 @@ _D0=$(dirname "${0}")
 
 . "${_D0}/_util"
 
-
 ##
 ## Definitions
 ##
 
 # Directories
-COMPOSE_DIR="$( cd "${_D0}/.." >/dev/null 2>&1 && pwd )"
+COMPOSE_DIR="$(cd "${_D0}/.." >/dev/null 2>&1 && pwd)"
 echo "Setting Compose Dir: ${COMPOSE_DIR}"
 CONFIG_DIR="${COMPOSE_DIR}/config"
 SCRIPTS_DIR="${COMPOSE_DIR}/scripts"
@@ -74,8 +73,7 @@ EMPTY_LOCKSS_OPT="${TEMPLATES_DIR}/blank_lockss.opt"
 declare -a arr global_confs=("lockss-cluster" "lockss-bootstrap" "repo_properties")
 declare -a arr svcs
 declare -a arr svcs_confs
-
-
+declare -a arr repo_mounts
 
 STACK_PREFIX="lockss-stack"
 STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
@@ -84,38 +82,41 @@ STACK_NUM=0
 UPDATE_IMAGES=0
 
 clean_up() { # Perform pre-exit housekeeping
-	return
+  return
 }
 
 error_exit() {
-	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
-	clean_up
-	exit 1
+  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+  clean_up
+  exit 1
 }
 
 graceful_exit() {
-	clean_up
-	exit
+  clean_up
+  exit
 }
 
 signal_exit() { # Handle trapped signals
-	case $1 in
-		INT)
-			error_exit "Program interrupted by user" ;;
-		TERM)
-			echo -e "\n$PROGNAME: Program terminated" >&2
-			graceful_exit ;;
-		*)
-			error_exit "$PROGNAME: Terminating on unknown signal" ;;
-	esac
+  case $1 in
+  INT)
+    error_exit "Program interrupted by user"
+    ;;
+  TERM)
+    echo -e "\n$PROGNAME: Program terminated" >&2
+    graceful_exit
+    ;;
+  *)
+    error_exit "$PROGNAME: Terminating on unknown signal"
+    ;;
+  esac
 }
 
 usage() {
-	echo -e "Usage: $PROGNAME [-h|--help] [-u|--update]"
+  echo -e "Usage: $PROGNAME [-h|--help] [-u|--update]"
 }
 
 help_message() {
-  cat <<- _EOF_
+  cat <<-_EOF_
   $PROGNAME ver. $VERSION
   This script will take the generated stack and add necessary elements to docker.
 
@@ -130,8 +131,7 @@ _EOF_
 }
 
 # $1=file $2=blankfile
-Config_Or_Blank()
-{
+Config_Or_Blank() {
   if [ -f "${1}/${2}" ]; then
     echo "${1}/${2}"
   else
@@ -169,7 +169,7 @@ init_service_arrays() {
     svcs_confs+=("repo")
   fi
   if ${USE_LOCKSS_POSTGRES}; then
-     svcs+=("postgres")
+    svcs+=("postgres")
   fi
   if ${USE_LOCKSS_SOLR}; then
     svcs+=("solr")
@@ -186,41 +186,37 @@ init_service_arrays() {
 }
 
 # Create configs for each stack
-add_stack_configs()
-{
+add_stack_configs() {
   local stack=$1
   local stack_path="${DOCKER_CONFIGS_DIR}/$stack"
 
   # Create the global configs
-  for gconf in "${global_confs[@]}"
-  do
+  for gconf in "${global_confs[@]}"; do
     echo "removing old $stack-${gconf} and $stack-${gconf}_opt"
-    docker config rm $stack-${gconf} $stack-${gconf}_opt &> /dev/null
+    docker config rm $stack-${gconf} $stack-${gconf}_opt &>/dev/null
     echo "adding docker config $stack-${gconf}..."
-    if ! docker config create --template-driver golang $stack-${gconf} $(Config_Or_Blank $stack_path "${gconf}" "blank_lockss") ; then
+    if ! docker config create --template-driver golang $stack-${gconf} $(Config_Or_Blank $stack_path "${gconf}" "blank_lockss"); then
       error_exit "${_0}: error creating config $stack-${gconf}"
     fi
-    if ! docker config create --template-driver golang $stack-${gconf}_opt $(Config_Or_Blank $stack_path "${gconf}_opt" "blank_lockss_opt") ; then
+    if ! docker config create --template-driver golang $stack-${gconf}_opt $(Config_Or_Blank $stack_path "${gconf}_opt" "blank_lockss_opt"); then
       error_exit "${_0}: error creating config $stack-${gconf}_opt"
     fi
   done
   # Create the configs for each lockss service
-  for sconf in "${svcs_confs[@]}"
-  do
+  for sconf in "${svcs_confs[@]}"; do
     echo "adding docker config ${sconf}..."
-    docker config rm $stack-${sconf}-service $stack-${sconf}-service_opt &> /dev/null
-    if ! docker config create --template-driver golang $stack-${sconf}-service $(Config_Or_Blank $stack_path "${sconf}-service" "blank_lockss") ; then
+    docker config rm $stack-${sconf}-service $stack-${sconf}-service_opt &>/dev/null
+    if ! docker config create --template-driver golang $stack-${sconf}-service $(Config_Or_Blank $stack_path "${sconf}-service" "blank_lockss"); then
       error_exit "${_0}: error creating config $stack-${sconf}-service"
     fi
-    if ! docker config create --template-driver golang $stack-${sconf}-service_opt $(Config_Or_Blank $stack_path "${sconf}-service_opt" "blank_lockss_opt") ; then
+    if ! docker config create --template-driver golang $stack-${sconf}-service_opt $(Config_Or_Blank $stack_path "${sconf}-service_opt" "blank_lockss_opt"); then
       error_exit "${_0}: error creating config $stack-${sconf}-service_opt"
     fi
   done
 }
 
 # Create a mount points for each stack
-add_stack_volumes()
-{
+add_stack_volumes() {
   local stack=$1
   for svc in "${svcs[@]}"
   do
@@ -233,6 +229,22 @@ add_stack_volumes()
       error_exit "${_0}: error creating volume $stack-${svc}-logs"
     fi
   done
+  add_additional_stack_volumes $stack
+}
+
+add_additional_stack_volumes() {
+  local stack=$1
+  IFS=';' read -r -a datadirs <<<"${LOCKSS_REPO_CACHE}"
+  count=1
+  for count in "${!datadirs[@]}"; do
+    mtpoint=${datadirs[$count]}/$stack-repo-data
+    mtname=$stack-repo-data${count}
+    echo "creating additional docker data volumes for $stack-repo.."
+    docker volume remove $mtname &>/dev/null
+    if ! docker volume create -d local-persist -o mountpoint=${mtpoint} --name=${mtname}; then
+      error_exit "${_0}: error creating volume ${mtname} for ${mtpoint};"
+    fi
+  done
 }
 
 # Create stack network
@@ -240,15 +252,14 @@ add_stack_network() {
   local stack=$1
   # Create a lockss network
   echo "Creating lockss network"
-  docker network remove $stack-network &> /dev/null
+  docker network remove $stack-network &>/dev/null
   if ! docker network create -d overlay --opt encrypted $stack-network; then
     error_exit "$stack-network: error creating network."
   fi
 }
 
 check_stack_images() {
-  for svc in "${svcs[@]}"
-  do
+  for svc in "${svcs[@]}"; do
     base=$(echo $svc | tr [a-z] [A-Z])
     img="${base}_IMG"
     vers="${base}_VERSION"
@@ -285,9 +296,9 @@ check_stack_solr() {
   [ ! -d "${CORE_PATH}" ] && msg "Unbalbe to find ${CORE_PATH}"
   if [ ! -f "${SOLR_FILE}" ] && [ ! -d "${CORE_PATH}" ]; then
     msg "Preparing solr for new install to ${SOLR_HOME_PATH}..."
-    sudo tar -xzf "${UPDATES_DIR}/solr-home.tar.gz" -C "${SOLR_HOME_PATH}" > /dev/null ||
+    sudo tar -xzf "${UPDATES_DIR}/solr-home.tar.gz" -C "${SOLR_HOME_PATH}" >/dev/null ||
       error_exit "Unable to install LOCKSS solr files, exiting..."
-    sudo cp -r "${UPDATES_DIR}/configsets" ${SOLR_CONFIG_PATH}  ||
+    sudo cp -r "${UPDATES_DIR}/configsets" ${SOLR_CONFIG_PATH} ||
       error_exit "Unable to install LOCKSS solr configuration files, exiting..."
     sudo chown -R "${SOLR_OWNER}" "${SOLR_HOME_PATH}" ||
       error_exit "Attempt to change ownership to ${SOLR_OWNER} on ${SOLR_HOME_PATH} failed."
@@ -299,7 +310,7 @@ assemble_stack() {
   echo "Processing stack $stack"
   # Source config.info and env.sh for this stack
   set -a
-    . "${DOCKER_CONFIGS_DIR}/$stack/env.sh"
+  . "${DOCKER_CONFIGS_DIR}/$stack/env.sh"
   set +a
   check_stack_images
   add_stack_configs $stack
@@ -313,29 +324,34 @@ assemble_stack() {
 ###
 # Trap signals
 trap "signal_exit TERM" TERM HUP
-trap "signal_exit INT"  INT
+trap "signal_exit INT" INT
 
 # Parse command-line
 while [[ -n $1 ]]; do
   case $1 in
-    -h | --help)
-      help_message; graceful_exit ;;
-    -u | --update)
-      UPDATE_IMAGES=1
-      msg "Forcing update of LOCKSS docker images" ;;
-    [1-9])
-       STACK_NUM=$1;;
-    -* | --*)
-      usage
-      error_exit "Unknown option $1" ;;
-    *)
-      echo "Argument $1 to process..." ;;
+  -h | --help)
+    help_message
+    graceful_exit
+    ;;
+  -u | --update)
+    UPDATE_IMAGES=1
+    msg "Forcing update of LOCKSS docker images"
+    ;;
+  [1-9])
+    STACK_NUM=$1
+    ;;
+  -* | --*)
+    usage
+    error_exit "Unknown option $1"
+    ;;
+  *)
+    echo "Argument $1 to process..."
+    ;;
   esac
   shift
 done
 
 # Main logic
-
 
 # Source system config file
 set -a
@@ -357,7 +373,7 @@ if [ ${NUM_STACKS} -eq 0 ]; then
 elif [ ${NUM_STACKS} -eq 1 ]; then
   assemble_stack ""
 elif [ ${STACK_NUM} -eq 0 ]; then
-  for ((num=1 ; num <= $NUM_STACKS ; num++)); do
+  for ((num = 1; num <= $NUM_STACKS; num++)); do
     assemble_stack $num
   done
 elif [ -e "${DOCKER_CONFIGS_DIR}/${STACK_PREFIX}${STACK_NUM}" ]; then
