update logging in all primary scripts.

diff --git a/scripts/assemble-lockss b/scripts/assemble-lockss
--- a/scripts/assemble-lockss
+++ b/scripts/assemble-lockss
@@ -51,6 +51,7 @@ _D0=$(dirname "${0}")
 
 . "${_D0}/_util"
 . "${_D0}/lib/mo"
+
 ##
 ## Definitions
 ##
@@ -84,11 +85,11 @@ PULL_POLICY="IfNotPresent"
 KUBECTL='microk8s kubectl -n lockss'
 
 clean_up() { # Perform pre-exit housekeeping
-  return
+  log_script_exit  "${PROGNAME}"
 }
 
 error_exit() {
-  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+  logger_fatal "${1:-"Unknown Error"}" >&2
   clean_up
   exit 1
 }
@@ -104,11 +105,11 @@ signal_exit() { # Handle trapped signals
     error_exit "Program interrupted by user"
     ;;
   TERM)
-    echo -e "\n$PROGNAME: Program terminated" >&2
+    logger_error "Program terminated"
     graceful_exit
     ;;
   *)
-    error_exit "$PROGNAME: Terminating on unknown signal"
+    error_exit "Terminating on unknown signal"
     ;;
   esac
 }
@@ -144,16 +145,13 @@ Config_Or_Blank() {
 
 Check_Physical_Volumes() {
   if [ -z "${LOCKSS_DATA_DIR}" ]; then
-    echo "LOCKSS_DATA_DIR is not set; exiting"
-    exit 1
+    error_exit "LOCKSS_DATA_DIR is not set; exiting"
   fi
   if  [ -z "${LOCKSS_LOGS_DIR}" ]; then
-    echo "LOCKSS_LOGS_DIR is not set; exiting"
-    exit 1
+    error_exit "LOCKSS_LOGS_DIR is not set; exiting"
   fi
   if [ -z "${LOCKSS_TMPDIR}" ]; then
-    echo "LOCKSS_TMPDIR are not set; exiting"
-    exit 1
+    error_exit "LOCKSS_TMPDIR are not set; exiting"
   fi
 }
 
@@ -211,7 +209,7 @@ ensure_writable_dir() {
   if [ $USER -eq ${LOCKSS_UID} ]; then
      return 0
   else
-    logger_warn "${PROGNAME}: ${DIR} is not writable by ${LOCKSS_USER}; attempting to chown it."
+    logger_warn "${DIR} is not writable by ${LOCKSS_USER}; attempting to chown it."
     sudo chown -R ${LOCKSS_UID}:${LOCKSS_GID} "${DIR}"
   fi
 }
@@ -233,25 +231,25 @@ add_stack_configs() {
   local stack_path="${DOCKER_CONFIGS_DIR}/$stack"
   local key
   # Create the global configs
-  logger_info "${PROGNAME}:  Adding global config files"
+  logger_info "Adding global config files"
   for gconf in "${global_confs[@]}"; do
     key=${gconf}
-    if ! $KUBECTL create configmap ${key} --namespace=${LOCKSS_NAMESPACE} --from-file=${key}=$(Config_Or_Blank $stack_path "${gconf}" "blank_lockss"); then
+    if ! $KUBECTL create configmap ${key} --namespace=${LOCKSS_NAMESPACE} --from-file=${key}=$(Config_Or_Blank $stack_path "${gconf}""blank_lockss"); then
       error_exit "${_0}: error creating config $stack-${gconf}"
     fi
-    if ! $KUBECTL create configmap ${key}-opt --namespace=${LOCKSS_NAMESPACE} --from-file=${key}-opt=$(Config_Or_Blank $stack_path "${gconf}_opt" "blank_lockss_opt"); then
+    if ! $KUBECTL create configmap ${key}-opt --namespace=${LOCKSS_NAMESPACE} --from-file=${key}-opt=$(Config_Or_Blank $stack_path "${gconf}_opt""blank_lockss_opt"); then
       error_exit "${_0}: error creating config $stack-${gconf}_opt"
     fi
   done
   # Create the configs for each lockss service
-  logger_info "${PROGNAME}:  Adding service config files"
+  logger_info "Adding service config files"
   for sconf in "${svcs_confs[@]}"; do
     key=${sconf}-service
-    echo "adding service config ${key}..."
-   if ! $KUBECTL create configmap ${key} --namespace=${LOCKSS_NAMESPACE} --from-file=${key}=$(Config_Or_Blank $stack_path "${key}" "blank_lockss"); then
+    logger_debug "adding service config ${key}..."
+   if ! $KUBECTL create configmap ${key} --namespace=${LOCKSS_NAMESPACE} --from-file=${key}=$(Config_Or_Blank $stack_path "${key}""blank_lockss"); then
       error_exit "${_0}: error creating config ${key}"
     fi
-    if ! $KUBECTL create configmap ${key}-opt --namespace=${LOCKSS_NAMESPACE} --from-file=${key}-opt=$(Config_Or_Blank $stack_path "${key}-opt" "blank_lockss_opt"); then
+    if ! $KUBECTL create configmap ${key}-opt --namespace=${LOCKSS_NAMESPACE} --from-file=${key}-opt=$(Config_Or_Blank $stack_path "${key}-opt""blank_lockss_opt"); then
       error_exit "${_0}: error creating config ${key}-opt"
     fi
   done
@@ -262,11 +260,11 @@ add_stack_configs() {
 add_stack_shared() {
   local stack=$1
   local mk_dir="${DOCKER_CONFIGS_DIR}/$stack/mk"
-  logger_info "${PROGNAME}:  clearing old deployments..."
+  logger_debug"clearing old deployments..."
   $KUBECTL delete deployments,pvc -l lockss-stack-id=${stack}
-  logger_info "${PROGNAME}:  clearing old  configmaps..."
+  logger_debug "clearing old  configmaps..."
   $KUBECTL delete configmaps --all
-  logger_info "${PROGNAME}:  adding storage class: local-storage from ${mk_dir}/local-storage.yaml"
+  logger_debug "adding storage class: local-storage from ${mk_dir}/local-storage.yaml"
   microk8s kubectl apply -f "${mk_dir}/local-storage.yaml"
 }
 
@@ -280,18 +278,18 @@ check_stack_solr() {
   OLD_REPO="${SOLR_HOME_PATH}/${SOLR_CORE_REPO}"
   SOLR_CONFIG_PATH="${SOLR_HOME_PATH}/configsets/lockss"
 
-  logger_info "${PROGNAME}:  Checking solr installation at ${SOLR_HOME_PATH}..."
+  logger_info "Checking solr installation at ${SOLR_HOME_PATH}..."
 
   if [ -d "${OLD_REPO}" ]; then
     error_exit "You are attempting to run with an older version without updating, please run upgrade script"
   fi
-  logger_info "${PROGNAME}:  Checking solr installation for essential files..."
+  logger_info "Checking solr installation for essential files..."
 
-  if [ ! -e "${SOLR_FILE}"  -o ! -e "${CORE_PATH}" ]; then
-    logger_info "${PROGNAME}:  Preparing solr home '${SOLR_HOME_PATH}' for new install..."
+  if [ ! -e "${SOLR_FILE}" -o ! -e "${CORE_PATH}" ]; then
+    logger_info "Preparing solr home '${SOLR_HOME_PATH}' for new install..."
     ensure_writable_dir ${SOLR_HOME_PATH} ||
       error_exit "Unable to write to ${SOLR_HOME_PATH}"
-    tar -xzf "${UPDATES_DIR}/solr-home.tar.gz" -C "${SOLR_HOME_PATH}" >/dev/null ||
+    tar -xzf "${UPDATES_DIR}/solr-home.tar.gz"-C "${SOLR_HOME_PATH}">/dev/null ||
       error_exit "Unable to install LOCKSS solr files, exiting..."
   fi
 }
@@ -304,9 +302,9 @@ add_stack_volumes() {
   ensure_writable_dir $LOCKSS_DATA_DIR
   ensure_writable_dir $LOCKSS_LOGS_DIR
   ensure_writable_dir $LOCKSS_TMPDIR
-
+  logger_info "Creating data and log volumes for $stack"
  for svc in "${svcs[@]}"; do
-    logger_info "${PROGNAME}:  creating data and log volumes for $stack-${svc}..."
+    logger_debug "Creating data and log volumes for $stack-${svc}..."
     mtpoint=${LOCKSS_DATA_DIR}/$stack-${svc}-data
     mkdir -p ${mtpoint} || error_exit "unable to create data dir: ${mtpoint}"
     mtpoint=${LOCKSS_LOGS_DIR}/$stack-${svc}-logs
@@ -324,7 +322,7 @@ add_additional_stack_volumes() {
   IFS=';' read -r -a datadirs <<<"${LOCKSS_REPO_HOST_DIRS}"
   len=${#datadirs[@]}
   start=1
-  logger_debug "${PROGNAME}:  creating additional data volumes for $stack-repository-service..."
+  logger_debug "Creating additional data volumes for $stack-repository-service..."
   for ((cnt = $start; cnt < $len; cnt++)); do
     mtpoint=${datadirs[$cnt]}/$stack-repo-data
     mkdir -p ${mtpoint} || error_exit "unable to create data dir: ${mtpoint}"
@@ -340,7 +338,7 @@ assemble_stack() {
   . "${DOCKER_CONFIGS_DIR}/$stack/env.sh"
   set +a
   pushd . &>/dev/null
-  cd "${DOCKER_CONFIGS_DIR}/$stack" || error_exit "Unable to cd to ${DOCKER_CONFIGS_DIR}/$stack."
+  cd "${DOCKER_CONFIGS_DIR}/$stack"|| error_exit "Unable to cd to ${DOCKER_CONFIGS_DIR}/$stack."
   add_stack_shared ${stack}
   add_stack_volumes ${stack}
   add_stack_configs ${stack}
@@ -349,9 +347,9 @@ assemble_stack() {
 }
 
 generate_lockss() {
-	logger_info "${PROGNAME}:  Removing old config files..."
+	logger_info "Removing old generated configuration files..."
 	rm -rf "${DOCKER_CONFIGS_DIR}"
-	logger_info "${PROGNAME}:  Generating config files for $STACK_COUNT stacks..."
+	logger_info "Generating config files for $STACK_COUNT stacks..."
 	for ((num = 1; num <= $STACK_COUNT; num++)); do
 		export STACK_PORT_BASE=$((${PORT_BASE} + $num))
 		if [ ${STACK_COUNT} = 1 ]; then
@@ -359,24 +357,24 @@ generate_lockss() {
 		else
 			STACK_NAME="${STACK_PREFIX}$num"
 		fi
+    logger_info "Generating files for stack $STACK_NAME"
 		export STACK_NAME
 		export STACK_LCAP_PORT=$((${LOCKSS_V3_PORT} + $num - 1))
 		export STACK_CONFIG_DIR="${DOCKER_CONFIGS_DIR}/${STACK_NAME}"
 		stack_env_file="${STACK_CONFIG_DIR}/env.sh"
 		stack_compose_file="${STACK_CONFIG_DIR}/docker-compose.yml"
-
-		logger_info "${PROGNAME}: Stack ${num} named ${STACK_NAME} is using port base of ${STACK_PORT_BASE}."
+		logger_debug "Stack ${num} named ${STACK_NAME} is using port base of ${STACK_PORT_BASE}."
 		mkdir -p "${STACK_CONFIG_DIR}"
 
-		logger_info "${PROGNAME}: Generating the stack env.sh file..."
-		mo "${ENV_TMPL}" >"${stack_env_file}"
+		logger_debug "Generating the stack env.sh file..."
+		mo "${ENV_TMPL}">"${stack_env_file}"
 		set -a
 		. "${stack_env_file}"
 		set +a
 
-		logger_info "${PROGNAME}: Getting node hostname..."
+		logger_debug "Getting node hostname..."
 		export NODE_HOSTNAME=$(microk8s kubectl get nodes -o jsonpath='{.items[*].status.addresses[?(@.type=="Hostname")].address}')
-		logger_info "${PROGNAME}: Getting postgres password..."
+		logger_debug "Getting postgres password..."
 		export POSTGRES_PASSWD=$(microk8s kubectl get secret -n lockss lockss-postgres-pass -o jsonpath='{.data.lockss-postgres-pass}'| base64 --decode -)
 
 		IFS=';' read -r -a datadirs <<<"${LOCKSS_REPO_HOST_DIRS}"
@@ -390,44 +388,44 @@ generate_lockss() {
 			export $varname
 		done
 		export REPO_NUMS
-		logger_info "${PROGNAME}: converting the service deployments..."
+		logger_info "Converting the service deployments..."
 		mkdir "${STACK_CONFIG_DIR}/svcs"
 		for f in ${SERVICES_DIR}/*.mustache; do
 			src="${f}"
-			dst="${STACK_CONFIG_DIR}/svcs/$(basename "${f}" .mustache).yaml"
-			logger_debug "     Rendering ${src} to ${dst}..."
-			mo "${src}" >"${dst}"
+			dst="${STACK_CONFIG_DIR}/svcs/$(basename "${f}".mustache).yaml"
+			logger_debug "Rendering ${src} to ${dst}..."
+			mo "${src}">"${dst}"
 		done
-		logger_info "${PROGNAME}: Converting the microk8s elements..."
+		logger_info "Converting the microk8s files..."
 		mk_dst="${STACK_CONFIG_DIR}/mk"
 		mkdir "${mk_dst}"
 		cp "${MK_DIR}/${STORAGE_CLASS_FILE}" "${mk_dst}/${STORAGE_CLASS_FILE}"
 		for f in ${MK_DIR}/*.mustache; do
 			src="${f}"
-			dst="${mk_dst}/$(basename "${f}" .mustache).yaml"
-			logger_debug "     Rendering ${src} to ${dst}..."
-			mo "${src}" >"${dst}"
+			dst="${mk_dst}/$(basename "${f}".mustache).yaml"
+			logger_debug "Rendering ${src} to ${dst}..."
+			mo "${src}">"${dst}"
 			envsubst < ${dst} > ${dst}.out
 			mv ${dst}.out ${dst}
 		done
-		logger_info "${PROGNAME}: Generating lockss config files..."
+		logger_info "Generating lockss configuration files..."
 		for f in ${TEMPLATES_DIR}/*.mustache; do
 			src="${f}"
-			dst="${STACK_CONFIG_DIR}/$(basename "${f}" .mustache)"
-			logger_debug"     Rendering ${src} to ${dst}..."
-			mo "${src}" >"${dst}"
+			dst="${STACK_CONFIG_DIR}/$(basename "${f}".mustache)"
+			logger_debug"Rendering ${src} to ${dst}..."
+			mo "${src}">"${dst}"
 		done
-		logger_info "${PROGNAME}:  Generating user config files..."
+		logger_info "Generating user configuration files..."
 		for f in ${USEROPTS_DIR}/templates/*_opt.mustache; do
-			if [[ -f "${f}" ]]; then
+			if [ -f "${f}" ]; then
 				src="${f}"
-				dst="${STACK_CONFIG_DIR}/$(basename "${f}" _opt.mustache)-opt"
-				logger_debug "     Rendering ${src} to ${dst}..."
-				mo "${src}" >"${dst}"
+				dst="${STACK_CONFIG_DIR}/$(basename "${f}"_opt.mustache)-opt"
+				logger_debug "Rendering ${src} to ${dst}..."
+				mo "${src}">"${dst}"
 			fi
 		done
 	done
-	logger_info "${PROGNAME}:  Successfully regenerated stack components."
+	logger_info "Successfully regenerated stack components."
 }
 
 assemble_lockss() {
@@ -449,7 +447,7 @@ assemble_lockss() {
 	else
 		error_exit "Unable to find generated stack ${STACK_NUM}"
 	fi
-	logger_info "${PROGNAME}:  Successfully installed components."
+	logger_info "Successfully installed components."
 
 }
 
@@ -461,6 +459,14 @@ assemble_lockss() {
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT" INT
 
+# Source system config file
+set -a
+. "${SYSTEM_CONF_FILE}"
+set +a
+logger_init
+log_script_entry "${PROGNAME}"
+umask 002
+
 # Parse command-line
 while [[ -n $1 ]]; do
   case $1 in
@@ -470,7 +476,7 @@ while [[ -n $1 ]]; do
     ;;
   -u | --update)
     PULL_POLICY="Always"
-    logger_info "${PROGNAME}:  Forcing update of LOCKSS docker images"
+    logger_info "Forcing update of LOCKSS docker images"
     ;;
   [1-9])
     STACK_COUNT=$1
@@ -480,35 +486,20 @@ while [[ -n $1 ]]; do
     error_exit "Unknown option $1"
     ;;
   *)
-    echo "Argument $1 to process..."
+    logger_debug "Argument $1 to process..."
     ;;
   esac
   shift
 done
 
-# Main logic
-
-# Source system config file
-set -a
-. "${SYSTEM_CONF_FILE}"
-set +a
-
+# Sanity checks
 if $(am_i_root); then
   error_exit "This script should not be run as root. Run as the lockss user."
 fi
-umask 002
-version=$(installer-version)
-logger_info ${version}
-logger_info "Running assemble-lockss"
-# Sanity checks
-logger_info "${PROGNAME}:  Checking install..."
+logger_info "Checking system..."
 Check_Runnable
 Check_Physical_Volumes
-
 generate_lockss
-
 assemble_lockss
-
-logger_info "${PROGNAME}:  LOCKSS is ready to deploy."
-
+logger_info "LOCKSS is ready to deploy."
 graceful_exit
diff --git a/scripts/deploy-lockss b/scripts/deploy-lockss
--- a/scripts/deploy-lockss
+++ b/scripts/deploy-lockss
@@ -68,11 +68,11 @@ STACK_PREFIX="lockss-stack"
 KUBECTL="microk8s kubectl -n lockss"
 
 clean_up() { # Perform pre-exit housekeeping
-  return
+  log_script_exit  "${PROGNAME}"
 }
 
 error_exit() {
-  logger_error "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+  logger_fatal "${1:-"Unknown Error"}" >&2
   clean_up
   exit 1
 }
@@ -85,14 +85,14 @@ graceful_exit() {
 signal_exit() { # Handle trapped signals
   case $1 in
   INT)
-    error_exit "Program interrupted by user"
+    logger_info "Program interrupted by user"
     ;;
   TERM)
-    echo -e "\n$PROGNAME: Program terminated" >&2
+    logger_error "Program terminated"
     graceful_exit
     ;;
   *)
-    error_exit "$PROGNAME: Terminating on unknown signal"
+    error_exit "Terminating on unknown signal"
     ;;
   esac
 }
@@ -211,6 +211,14 @@ deploy_stack() {
 # Trap signals
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT" INT
+# Source system config file
+set -a
+. "${SYSTEM_CONF_FILE}"
+set +a
+#init the logger and mark script entry
+logger_init
+log_script_entry "${PROGNAME}"
+umask 002
 
 STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
 NUM_STACKS=${#STACK_DIRS[@]}
@@ -237,20 +245,17 @@ while [[ -n $1 ]]; do
     error_exit "Unknown option $1"
     ;;
   *)
-    echo "Argument $1 to process..."
+    logger_trace "Argument $1 to process..."
     ;;
   esac
   shift
 done
-
-set -a
-. "${SYSTEM_CONF_FILE}"
-set +a
+# Sanity checks
+logger_info "Checking system..."
 
 if $(am_i_root); then
   error_exit "This script should not be run as root. Run as the lockss user."
 fi
-umask 002
 Check_Runnable
 
 init_service_arrays
@@ -260,7 +265,7 @@ if [ ${NUM_STACKS} -eq 0 ]; then
 elif [ ${NUM_STACKS} -eq 1 ]; then
   deploy_stack ""
 elif [ ${STACK_NUM} -eq 0 ]; then
-  echo "Installing ${NUM_STACKS} stacks found in ${DOCKER_CONFIGS_DIR}"
+  logger_info "Deploying ${NUM_STACKS} stacks found in ${DOCKER_CONFIGS_DIR}"
   for ((num = 1; num <= $NUM_STACKS; num++)); do
     deploy_stack $num
   done
diff --git a/scripts/restart-lockss b/scripts/restart-lockss
--- a/scripts/restart-lockss
+++ b/scripts/restart-lockss
@@ -50,13 +50,13 @@ _D0=$(dirname "${0}")
 UPDATE_ARG=""
 
 clean_up() { # Perform pre-exit housekeeping
-	return
+  log_script_exit  "${PROGNAME}"
 }
 
 error_exit() {
-	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
-	clean_up
-	exit 1
+  logger_fatal "${1:-"Unknown Error"}" >&2
+  clean_up
+  exit 1
 }
 
 graceful_exit() {
@@ -101,6 +101,13 @@ _EOF_
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT"  INT
 
+# Source system config file
+set -a
+. "${SYSTEM_CONF_FILE}"
+set +a
+logger_init
+log_script_entry "${PROGNAME}"
+umask 002
 
 ARGS_ADDITIONAL=""
 # Parse command-line
@@ -110,18 +117,18 @@ while [[ -n $1 ]]; do
       help_message; graceful_exit ;;
     -u | --update)
       UPDATE_ARG="-u"
-      msg "Forcing update of LOCKSS docker images"
+      logger_info "Forcing update of LOCKSS docker images"
       ;;
     -a | --args)
       shift
       export ARGS_ADDITIONAL="$1"
-      echo "Adding additional runtime args $ARGS_ADDITIONAL";
+      logger_info "Adding additional runtime args $ARGS_ADDITIONAL";
     ;;
     -*)
       usage
       error_exit "Unknown option $1" ;;
     *)
-      echo "Argument $1 to process..." ;;
+      logger_debug "Argument $1 to process..." ;;
   esac
   shift
 done
@@ -133,14 +140,12 @@ if $(am_i_root); then
   error_exit "This script should not be run as root. Run as the lockss user."
 fi
 
-
-"${SCRIPTS_DIR}"/stop-lockss &&
+"${SCRIPTS_DIR}"/stop-lockss && logger_info "LOCKSS stack has been stopped."
 if [ -n "${UPDATE_ARG}" ]; then
-  "${SCRIPTS_DIR}"/assemble-lockss ${UPDATE_ARG} &&
-  "${SCRIPTS_DIR}"/deploy-lockss -a "$ARGS_ADDITIONAL"
-else
-  "${SCRIPTS_DIR}"/deploy-lockss -a "$ARGS_ADDITIONAL"
+  "${SCRIPTS_DIR}"/assemble-lockss ${UPDATE_ARG}
 fi
+logger_info "Restarting LOCKSS stack"
+"${SCRIPTS_DIR}"/deploy-lockss -a "$ARGS_ADDITIONAL"
 
 graceful_exit
 
diff --git a/scripts/uninstall-lockss b/scripts/uninstall-lockss
--- a/scripts/uninstall-lockss
+++ b/scripts/uninstall-lockss
@@ -53,30 +53,33 @@ _D0=$(dirname "${0}")
 . "${_D0}/_util"
 
 clean_up() { # Perform pre-exit housekeeping
-	return
+  log_script_exit  "${PROGNAME}"
 }
 
 error_exit() {
-	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
-	clean_up
-	exit 1
+  logger_error "${1:-"Unknown Error"}"
+  clean_up
+  exit 1
 }
 
 graceful_exit() {
-	clean_up
-	exit
+  clean_up
+  exit
 }
 
 signal_exit() { # Handle trapped signals
-	case $1 in
-		INT)
-			error_exit "Program interrupted by user" ;;
-		TERM)
-			echo -e "\n$PROGNAME: Program terminated" >&2
-			graceful_exit ;;
-		*)
-			error_exit "$PROGNAME: Terminating on unknown signal" ;;
-	esac
+  case $1 in
+  INT)
+    error_exit "Program interrupted by user"
+    ;;
+  TERM)
+    logger_error "Program terminated"
+    graceful_exit
+    ;;
+  *)
+    error_exit "Terminating on unknown signal"
+    ;;
+  esac
 }
 
 usage() {
@@ -103,6 +106,13 @@ _EOF_
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT"  INT
 
+# Source system config file
+set -a
+. "${SYSTEM_CONF_FILE}"
+set +a
+logger_init
+log_script_entry "${PROGNAME}"
+umask 002
 
 # Parse command-line
 while [[ -n $1 ]]; do
@@ -113,7 +123,7 @@ while [[ -n $1 ]]; do
       usage
       error_exit "Unknown option $1" ;;
     *)
-      echo "Argument $1 to process..." ;;
+      logger_debug "Argument $1 to process..." ;;
   esac
   shift
 done
@@ -126,11 +136,11 @@ if [[ $# -eq 0 ]]; then
   # Make sure we stop any running service by calling remove all stacks
   if microk8s kubectl get namespace "lockss" >/dev/null; then
     msg ""
-    microk8s kubectl delete services,deployments,pods,pvc -n "lockss"
-    microk8s kubectl delete configmaps,secrets -n "lockss"
-  echo ""
-  echo "Successfully removed all running service and removed all installed data."
-  echo "You will need to rerun configure-lockss and start-lockss to run again."
+    microk8s kubectl delete services,deployments,pods,pvc,secrets -n "lockss"
+    microk8s kubectl delete pv,configmaps
+  logger_info ""
+  logger_info "Successfully removed all running service and removed all installed data."
+  logger_info "You will need to rerun configure-lockss and start-lockss to run again."
 fi
 
 graceful_exit
