Add help message and formal parameter support, error handling

diff --git a/scripts/assemble-lockss b/scripts/assemble-lockss
--- a/scripts/assemble-lockss
+++ b/scripts/assemble-lockss
@@ -1,4 +1,6 @@
 #!/bin/bash
+# ---------------------------------------------------------------------------
+# assemble-lockss - Assemble lockss stack by installing generated configs files, volumes and networks..
 
 # Copyright (c) 2000-2019, Board of Trustees of Leland Stanford Jr. University
 # All rights reserved.
@@ -28,6 +30,15 @@
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
+#
+# Usage: assemble-lockss [-h|--help]
+#
+# Revision history:
+# 2019-04-18 version 1
+# ---------------------------------------------------------------------------
+PROGNAME=${0##*/}
+VERSION="1.0"
+
 ##
 ## Relative paths
 ##
@@ -62,6 +73,51 @@ declare -a arr global_confs=("lockss-cluster" "lockss-bootstrap" "repo_propertie
 declare -a arr service_confs=("cfg" "mdq" "mdx" "pol")
 
 STACK_PREFIX="lockss-stack"
+
+clean_up() { # Perform pre-exit housekeeping
+	return
+}
+
+error_exit() {
+	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+	clean_up
+	exit 1
+}
+
+graceful_exit() {
+	clean_up
+	exit
+}
+
+signal_exit() { # Handle trapped signals
+	case $1 in
+		INT)
+			error_exit "Program interrupted by user" ;;
+		TERM)
+			echo -e "\n$PROGNAME: Program terminated" >&2
+			graceful_exit ;;
+		*)
+			error_exit "$PROGNAME: Terminating on unknown signal" ;;
+	esac
+}
+
+usage() {
+	echo -e "Usage: $PROGNAME [-h|--help]"
+}
+
+help_message() {
+  cat <<- _EOF_
+  $PROGNAME ver. $VERSION
+  Assemble lockss stack by installing generated configs files, volumes and networks.
+
+  $(usage)
+
+  Options:
+  -h, --help  Display this help message and exit.
+
+_EOF_
+  return
+}
 
 # $1=file $2=blankfile
 Config_Or_Blank()
@@ -159,10 +215,35 @@ assemble_stack() {
   add_stack_network $stack
   add_stack_volumes $stack
 }
+###
+# Start
+###
+# Trap signals
+trap "signal_exit TERM" TERM HUP
+trap "signal_exit INT"  INT
 
 ##
 ## MAIN
 ##
+STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
+NUM_STACKS=${#STACK_DIRS[@]}
+STACK_NUM=0
+
+# Parse command-line
+while [[ -n $1 ]]; do
+  case $1 in
+    -h | --help)
+      help_message; graceful_exit ;;
+    [1-9])
+       STACK_NUM=$1;;
+    -* | --*)
+      usage
+      error_exit "Unknown option $1" ;;
+    *)
+      echo "Argument $1 to process..." ;;
+  esac
+  shift
+done
 
 # Source config.info and env.sh
 set -a
@@ -176,22 +257,22 @@ Check_Stack
 Check_LocalPersistPlugin
 Check_Physical_Volumes
 
-STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
-NUM_STACKS=${#STACK_DIRS[@]}
 
 if [[ NUM_STACKS -eq 0 ]]; then
-  echo "No configuration files have been generated, run generate-lockss first."
-  exit 1
-elif [[ $# -eq 0 ]]; then
+  error_exit "No configuration files have been generated, run generate-lockss first."
+elif [[ ${STACK_NUM} -eq 0 ]]; then
   for ((num=1 ; num <= $NUM_STACKS ; num++)); do
     assemble_stack $num
   done
-elif [[ -e "${DOCKER_CONFIGS_DIR}/${STACK_PREFIX}$1" ]]; then
-  assemble_stack $1
+elif [[ -e "${DOCKER_CONFIGS_DIR}/${STACK_PREFIX}${STACK_NUM}" ]]; then
+  assemble_stack ${STACK_NUM}
 else
-  echo "Unable to find generated stack $1"
-  exit 1
+  error_exit "Unable to find generated stack ${STACK_NUM}"
 fi
+
 echo ""
 echo "Successfully installed into docker all configs and volumes and networks."
+echo ""
 echo "Run deploy-lockss to deploy the assembled stack(s)."
+
+graceful_exit
diff --git a/scripts/configure-lockss b/scripts/configure-lockss
--- a/scripts/configure-lockss
+++ b/scripts/configure-lockss
@@ -1,11 +1,96 @@
 #!/bin/bash
+# ---------------------------------------------------------------------------
+# configure-lockss - Collect host system information needed to run a LOCKSS stack
+#
+# Copyright (c) 2000-2019, Board of Trustees of Leland Stanford Jr. University
+# All rights reserved.
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are met:
+#
+# 1. Redistributions of source code must retain the above copyright notice,
+# this list of conditions and the following disclaimer.
+#
+# 2. Redistributions in binary form must reproduce the above copyright notice,
+# this list of conditions and the following disclaimer in the documentation
+# and/or other materials provided with the distribution.
+#
+# 3. Neither the name of the copyright holder nor the names of its contributors
+# may be used to endorse or promote products derived from this software without
+# specific prior written permission.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
+# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
+# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
+# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
+# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
+# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
+# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
+# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
+# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
+# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
+# POSSIBILITY OF SUCH DAMAGE.
 
+# Usage: configure-lockss [-h|--help] <num stacks>
+
+# Revision history:
+# ---------------------------------------------------------------------------
+
+PROGNAME=${0##*/}
+VERSION="1.0"
 ##
 ## Relative paths
 ##
 
 _0=$(basename "${0}")
 _D0=$(dirname "${0}")
+
+clean_up() { # Perform pre-exit housekeeping
+	return
+}
+
+error_exit() {
+	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+	clean_up
+	exit 1
+}
+
+graceful_exit() {
+	clean_up
+	exit
+}
+
+signal_exit() { # Handle trapped signals
+	case $1 in
+		INT)
+			error_exit "Program interrupted by user" ;;
+		TERM)
+			echo -e "\n$PROGNAME: Program terminated" >&2
+			graceful_exit ;;
+		*)
+			error_exit "$PROGNAME: Terminating on unknown signal" ;;
+	esac
+}
+
+usage() {
+	echo -e "Usage: $PROGNAME [-h|--help] [<num stacks>]"
+}
+
+help_message() {
+  cat <<- _EOF_
+  $PROGNAME ver. $VERSION
+  Collect host system information needed to run a LOCKSS stack.
+
+  $(usage)
+
+  Options:
+  -h, --help  Display this help message and exit.
+  <num stacks> Optional number of stacks to run on this host.
+
+_EOF_
+  return
+}
+
 
 ##
 ## Load _util
@@ -376,16 +461,32 @@ EOF
 ###
 # Start
 ###
+# Trap signals
+trap "signal_exit TERM" TERM HUP
+trap "signal_exit INT"  INT
+
 Check_Installed 'docker'
 Check_Docker
 Check_Stack
+
 CONFIG_USER=$(whoami)
+CONFIG_COUNT=1
+LOCKSS_TEAM=lockssdiag@lockss.org
+LOCKSS_USER=lockss
+LOCAL_HOSTNAME=$(uname -n)
+CONFIG_FILE=${CONFIG_DIR}/config.info
+
 OS_TYPE=$(uname -s)
 case ${OS_TYPE} in
 Linux)
     LOCKSS_HOME=
     SHA256SUM=sha256sum
-    LOCAL_IPADDR=$(ifconfig eth0 | grep 'inet addr:' | grep -v 127.0.0.1 | tail -1 | sed 's/.*inet addr:\(.*\)  Mask.*/\1/')
+   if [ "X$(which ifconfig)" == "X" ]; then
+       SUDO="sudo"
+   else
+       SUDO=""
+   fi
+    LOCAL_IPADDR=$($SUDO ifconfig eth0 | grep 'inet addr:' | grep -v 127.0.0.1 | tail -1 | sed 's/.*inet addr:\(.*\)  Mask.*/\1/')
     ;;
 Darwin)
     LOCKSS_HOME=
@@ -393,15 +494,27 @@ Darwin)
     LOCAL_IPADDR=$(ifconfig -a | grep 'inet ' | grep -v 127.0.0.1 | tail -1 | sed 's/.*inet \(.*\) netmask.*/\1/')
     ;;
 *)
-    echo "${OS_TYPE} not supported"
-    exit 1
+    error_exit "${OS_TYPE} not supported"
     ;;
 esac
-LOCKSS_TEAM=lockssdiag@lockss.org
-LOCKSS_USER=lockss
-LOCAL_HOSTNAME=$(uname -n)
-CONFIG_FILE=${CONFIG_DIR}/config.info
-declare -i CONFIG_COUNT
+
+# Parse command-line
+while [[ -n $1 ]]; do
+  case $1 in
+    -h | --help)
+      help_message; graceful_exit ;;
+    [1-9])
+      CONFIG_COUNT=$1;;
+    -* | --*)
+      usage
+      error_exit "Unknown option $1" ;;
+    *)
+      echo "Argument $1 to process..." ;;
+  esac
+  shift
+done
+
+# Main logic
 
 echo "LOCKSS host configuration for ${OS_TYPE}."
 echo "For more information see README"
@@ -409,17 +522,14 @@ if [ -r "${CONFIG_FILE}" ]; then
     echo "Setting defaults from existing config: ${CONFIG_FILE}"
     read_config ${CONFIG_FILE}
 fi
-#get the number of stacks
-case "${1}" in
-  '') CONFIG_COUNT=1 ; break ;;
-  [1-9]) CONFIG_COUNT="${1}" ; break ;;
-  *) echo "Invalid number of parallel stacks: ${1}" ; exit 1 ;;
-esac
 #build config file
-echo "building config for ${CONFIG_COUNT} stacks on ${OS_TYPE} for user ${CONFIG_USER}..."
+echo "Creating config info for ${CONFIG_COUNT} stacks on ${OS_TYPE} for user ${CONFIG_USER}..."
 build_config_file ${CONFIG_FILE} ${CONFIG_USER} ${CONFIG_COUNT}
-
+echo ""
 #call generate-lockss
-. "${_D0}/generate-lockss"
+echo "Generating lockss config files for ${CONFIG_COUNT} stacks..."
+${_D0}/generate-lockss ${CONFIG_COUNT}
 echo ""
 echo "Call assemble-lockss to prepare for deploy-lockss"
+
+graceful_exit
diff --git a/scripts/deploy-lockss b/scripts/deploy-lockss
--- a/scripts/deploy-lockss
+++ b/scripts/deploy-lockss
@@ -1,5 +1,7 @@
 #!/bin/bash
-
+# ---------------------------------------------------------------------------
+# deploy-lockss - Collect host system information needed to run a LOCKSS stack
+#
 # Copyright (c) 2000-2019, Board of Trustees of Leland Stanford Jr. University
 # All rights reserved.
 #
@@ -28,6 +30,15 @@
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
+
+# Usage: deploy-lockss [-h|--help]
+
+# Revision history:
+# 2019-04-18 version 1
+# ---------------------------------------------------------------------------
+PROGNAME=${0##*/}
+VERSION="1.0"
+
 ##
 ## Relative paths
 ##
@@ -60,6 +71,51 @@ declare -a arr global_confs=("lockss-cluster" "lockss-bootstrap" "repo_propertie
 declare -a arr service_confs=("cfg" "mdq" "mdx" "pol")
 
 STACK_PREFIX="lockss-stack"
+
+clean_up() { # Perform pre-exit housekeeping
+	return
+}
+
+error_exit() {
+	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+	clean_up
+	exit 1
+}
+
+graceful_exit() {
+	clean_up
+	exit
+}
+
+signal_exit() { # Handle trapped signals
+	case $1 in
+		INT)
+			error_exit "Program interrupted by user" ;;
+		TERM)
+			echo -e "\n$PROGNAME: Program terminated" >&2
+			graceful_exit ;;
+		*)
+			error_exit "$PROGNAME: Terminating on unknown signal" ;;
+	esac
+}
+
+usage() {
+	echo -e "Usage: $PROGNAME [-h|--help]"
+}
+
+help_message() {
+  cat <<- _EOF_
+  $PROGNAME ver. $VERSION
+  Deploy the lockss stacks to docker.
+
+  $(usage)
+
+  Options:
+  -h, --help  Display this help message and exit.
+
+_EOF_
+  return
+}
 
 # Check our secrets
 check_installed_secrets()
@@ -135,6 +191,9 @@ deploy_stack()
 ##
 ## MAIN
 ##
+# Trap signals
+trap "signal_exit TERM" TERM HUP
+trap "signal_exit INT"  INT
 
 # Sanity checks
 Check_Installed 'docker'
@@ -144,20 +203,36 @@ Check_LocalPersistPlugin
 
 STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
 NUM_STACKS=${#STACK_DIRS[@]}
+STACK_NUM=0
+# Parse command-line
+while [[ -n $1 ]]; do
+  case $1 in
+    -h | --help)
+      help_message; graceful_exit ;;
+    [1-9])
+       STACK_NUM=$1;;
+    -* | --*)
+      usage
+      error_exit "Unknown option $1" ;;
+    *)
+      echo "Argument $1 to process..." ;;
+  esac
+  shift
+done
 
 if [[ NUM_STACKS -eq 0 ]]; then
-  echo "Unable to find generated stack info, run configure, generate and install first."
-  exit 1
-elif [[ $# -eq 0 ]]; then
+  error_exit "Unable to find generated stack info, run configure, generate and install first."
+elif [[ ${STACK_NUM} -eq 0 ]]; then
   echo "Installing ${NUM_STACKS} stacks found in ${DOCKER_CONFIGS_DIR}"
   for ((num=1 ; num <= $NUM_STACKS ; num++)); do
     check_stack_installed $num
     deploy_stack $num
   done
-elif [[ -e "${DOCKER_CONFIGS_DIR}/${STACK_PREFIX}$1" ]]; then
-    check_stack_installed $1
-    deploy_stack $1
+elif [[ -e "${DOCKER_CONFIGS_DIR}/${STACK_PREFIX}${STACK_NUM}" ]]; then
+    check_stack_installed ${STACK_NUM}
+    deploy_stack ${STACK_NUM}
 else
-  echo "Unable to find generated stack info for $1"
-  exit 1
+  error_exit "Unable to find generated stack info for ${STACK_NUM}"
 fi
+
+graceful_exit
diff --git a/scripts/generate-lockss b/scripts/generate-lockss
--- a/scripts/generate-lockss
+++ b/scripts/generate-lockss
@@ -1,5 +1,7 @@
 #!/bin/bash
-
+# ---------------------------------------------------------------------------
+# generate-lockss - Generate files needed to run a LOCKSS stack
+#
 # Copyright (c) 2000-2019, Board of Trustees of Leland Stanford Jr. University
 # All rights reserved.
 #
@@ -28,6 +30,14 @@
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
+#
+# Usage: generate-lockss [-h|--help] <num stacks>
+#
+# Revision history:
+# 2019-04-18 version 1
+# ---------------------------------------------------------------------------
+PROGNAME=${0##*/}
+VERSION="1.0"
 
 ##
 ## Relative paths
@@ -52,24 +62,84 @@ ENV_FILE="${CONFIG_DIR}/env.mustache"
 USER_CONF_FILE="${CONFIG_DIR}/config.info"
 
 # Variables
-declare -i STACK_COUNT
+declare -i STACK_COUNT=1
 STACK_PREFIX="lockss-stack"
 
+clean_up() { # Perform pre-exit housekeeping
+	return
+}
+
+error_exit() {
+	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+	clean_up
+	exit 1
+}
+
+graceful_exit() {
+	clean_up
+	exit
+}
+
+signal_exit() { # Handle trapped signals
+	case $1 in
+		INT)
+			error_exit "Program interrupted by user" ;;
+		TERM)
+			echo -e "\n$PROGNAME: Program terminated" >&2
+			graceful_exit ;;
+		*)
+			error_exit "$PROGNAME: Terminating on unknown signal" ;;
+	esac
+}
+
+usage() {
+	echo -e "Usage: $PROGNAME [-h|--help] [<num stacks>]"
+}
+
+help_message() {
+  cat <<- _EOF_
+  $PROGNAME ver. $VERSION
+  Generate files needed to run a LOCKSS stack.
+
+  $(usage)
+
+  Options:
+  -h, --help  Display this help message and exit.
+  <num stacks> Optional number of stacks to run on this host.
+
+_EOF_
+  return
+}
 ##
 ## MAIN
 ##
+
+# Trap signals
+trap "signal_exit TERM" TERM HUP
+trap "signal_exit INT"  INT
+
+# Parse command-line
+while [[ -n $1 ]]; do
+  case $1 in
+    -h | --help)
+      help_message; graceful_exit ;;
+    [1-9])
+      STACK_COUNT=$1;;
+    -* | --*)
+      usage
+      error_exit "Unknown option $1" ;;
+    *)
+      echo "Argument $1 to process..." ;;
+  esac
+  shift
+done
 
 # Source user-config
 set -a
 . "${CONFIG_DIR}/config.info"
 set +a
 
-if [ "$#" -ne 1 ]; then
-  echo "Stack count is being set to default of 1."
-  STACK_COUNT=1
-else
-  STACK_COUNT="${1}"
-fi
+
 echo "$(date) Removing old config files..."
 rm -rf "${DOCKER_CONFIGS_DIR}"
 echo "$(date) Generating config files for $STACK_COUNT stacks..."
@@ -112,3 +182,5 @@ for (( num=1 ; num<=$STACK_COUNT ; num++)); do
 done
 
 echo "$(date) Done updating configs."
+
+graceful_exit
diff --git a/scripts/shutdown-lockss b/scripts/shutdown-lockss
--- a/scripts/shutdown-lockss
+++ b/scripts/shutdown-lockss
@@ -1,5 +1,7 @@
 #!/bin/bash
-
+# ---------------------------------------------------------------------------
+# shutdown-lockss - Stop LOCKSS stack and containers.
+#
 # Copyright (c) 2000-2018, Board of Trustees of Leland Stanford Jr. University
 # All rights reserved.
 #
@@ -28,8 +30,63 @@
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
+#
+# Usage: shutdown-lockss [-h|--help]
+#
+# Revision history:
+# 2019-04-18 version 1
+# ---------------------------------------------------------------------------
+PROGNAME=${0##*/}
+VERSION="1.0"
+
 _0=$(basename "${0}")
 _D0=$(dirname "${0}")
+
+
+clean_up() { # Perform pre-exit housekeeping
+	return
+}
+
+error_exit() {
+	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+	clean_up
+	exit 1
+}
+
+graceful_exit() {
+	clean_up
+	exit
+}
+
+signal_exit() { # Handle trapped signals
+	case $1 in
+		INT)
+			error_exit "Program interrupted by user" ;;
+		TERM)
+			echo -e "\n$PROGNAME: Program terminated" >&2
+			graceful_exit ;;
+		*)
+			error_exit "$PROGNAME: Terminating on unknown signal" ;;
+	esac
+}
+
+usage() {
+	echo -e "Usage: $PROGNAME [-h|--help]"
+}
+
+help_message() {
+  cat <<- _EOF_
+  $PROGNAME ver. $VERSION
+  Stop LOCKSS stack and containers.
+
+  $(usage)
+
+  Options:
+  -h, --help  Display this help message and exit.
+
+_EOF_
+  return
+}
 
 ##
 ## Load _util
@@ -44,22 +101,45 @@ _D0=$(dirname "${0}")
 ##
 ## MAIN
 ##
+# Trap signals
+trap "signal_exit TERM" TERM HUP
+trap "signal_exit INT"  INT
+
+STACK_NUM=0
+
+# Parse command-line
+while [[ -n $1 ]]; do
+  case $1 in
+    -h | --help)
+      help_message; graceful_exit ;;
+    [1-9])
+       STACK_NUM=$1;;
+    -* | --*)
+      usage
+      error_exit "Unknown option $1" ;;
+    *)
+      echo "Argument $1 to process..." ;;
+  esac
+  shift
+done
 
 # Sanity checks
 Check_Installed 'docker'
 Check_Docker
 Check_Stack
 
-if [[ $# -eq 0 ]]; then
+if [[ ${STACK_NUM} -eq 0 ]]; then
   echo "Shutting down all LOCKSS stacks..."
   docker stack ls | grep 'lockss-stack' | awk '{print $1}' | xargs docker stack rm
   docker ps -a | grep 'lockss-stack' | awk '{print $1}' | xargs docker container stop
   docker ps -a | grep 'lockss-stack' | awk '{print $1}' | xargs docker container rm
   echo "Stopped all containers and removed containers and stacks. Run deploy-lockss to run again."
 else
-  echo "Shutting down lockss-stack$1"
-  docker stack ls | grep 'lockss-stack$1' | awk '{print $1}' | xargs docker stack rm
-  docker ps -a | grep 'lockss-stack$1' | awk '{print $1}' | xargs docker container stop
-  docker ps -a | grep 'lockss-stack$1' | awk '{print $1}' | xargs docker container rm
-  echo "Stopped all containers and removed containers for lockss-stack$1. Run deploy-lockss $1 to run again."
+  echo "Shutting down lockss-stack${STACK_NUM}"
+  docker stack ls | grep 'lockss-stack${STACK_NUM}' | awk '{print $1}' | xargs docker stack rm
+  docker ps -a | grep 'lockss-stack${STACK_NUM}' | awk '{print $1}' | xargs docker container stop
+  docker ps -a | grep 'lockss-stack${STACK_NUM}' | awk '{print $1}' | xargs docker container rm
+  echo "Stopped all containers and removed containers for lockss-stack${STACK_NUM}. Run deploy-lockss ${STACK_NUM} to run again."
 fi
+
+graceful_exit
diff --git a/scripts/uninstall-lockss b/scripts/uninstall-lockss
--- a/scripts/uninstall-lockss
+++ b/scripts/uninstall-lockss
@@ -1,5 +1,7 @@
 #!/bin/bash
-
+# ---------------------------------------------------------------------------
+# uninstall-lockss - Undeploy all stacks and remove all installed stack info..
+#
 # Copyright (c) 2000-2019, Board of Trustees of Leland Stanford Jr. University
 # All rights reserved.
 #
@@ -28,6 +30,15 @@
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
+#
+# Usage: uninstall-lockss [-h|--help]
+#
+# Revision history:
+# 2019-04-18 version 1
+# ---------------------------------------------------------------------------
+PROGNAME=${0##*/}
+VERSION="1.0"
+
 ##
 ## Relative paths
 ##
@@ -41,12 +52,71 @@ _D0=$(dirname "${0}")
 
 . "${_D0}/_util"
 
-##
-## Definitions
-##
+clean_up() { # Perform pre-exit housekeeping
+	return
+}
+
+error_exit() {
+	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+	clean_up
+	exit 1
+}
+
+graceful_exit() {
+	clean_up
+	exit
+}
+
+signal_exit() { # Handle trapped signals
+	case $1 in
+		INT)
+			error_exit "Program interrupted by user" ;;
+		TERM)
+			echo -e "\n$PROGNAME: Program terminated" >&2
+			graceful_exit ;;
+		*)
+			error_exit "$PROGNAME: Terminating on unknown signal" ;;
+	esac
+}
+
+usage() {
+	echo -e "Usage: $PROGNAME [-h|--help]"
+}
+
+help_message() {
+  cat <<- _EOF_
+  $PROGNAME ver. $VERSION
+  Undeploy all stacks and remove all installed stack info.
+
+  $(usage)
+
+  Options:
+  -h, --help  Display this help message and exit.
+
+_EOF_
+  return
+}
 ##
 ## MAIN
 ##
+# Trap signals
+trap "signal_exit TERM" TERM HUP
+trap "signal_exit INT"  INT
+
+
+# Parse command-line
+while [[ -n $1 ]]; do
+  case $1 in
+    -h | --help)
+      help_message; graceful_exit ;;
+    -* | --*)
+      usage
+      error_exit "Unknown option $1" ;;
+    *)
+      echo "Argument $1 to process..." ;;
+  esac
+  shift
+done
 
 # Sanity checks
 Check_Installed 'docker'
@@ -72,3 +142,5 @@ if [[ $# -eq 0 ]]; then
   echo "Successfully undeployed all stacks and removed all installed stack info."
   echo "You will need to rerun assemble-lockss and deploy-lockss to run again."
 fi
+
+graceful_exit
