fix volumes, secrets and configmaps

diff --git a/scripts/assemble-lockss b/scripts/assemble-lockss
--- a/scripts/assemble-lockss
+++ b/scripts/assemble-lockss
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # ---------------------------------------------------------------------------
 # assemble-lockss - Assemble lockss stack by installing generated configs files, volumes and networks..
 
@@ -65,17 +65,17 @@ SCRIPTS_DIR="${COMPOSE_DIR}/scripts"
 DOCKER_CONFIGS_DIR="${CONFIG_DIR}/configs"
 TEMPLATES_DIR="${CONFIG_DIR}/templates"
 UPDATES_DIR="${SCRIPTS_DIR}/upgrades"
+USEROPTS_DIR="${CONFIG_DIR}/useropts"
 # Files
 SYSTEM_CONF_FILE="${CONFIG_DIR}/system.cfg"
 EMPTY_LOCKSS_TXT="${TEMPLATES_DIR}/blank_lockss.txt"
 EMPTY_LOCKSS_OPT="${TEMPLATES_DIR}/blank_lockss.opt"
 
 #Data
-declare -a arr global_confs=("lockss-cluster" "lockss-bootstrap" "repo_properties")
+declare -a arr global_confs=("lockss-cluster" "lockss-bootstrap" "repo-properties")
 declare -a arr svcs
 declare -a arr svcs_confs
-
-
+declare -a secrets=("lockss-ui-pass" "lockss-auth" "lockss-postgres-pass")
 
 STACK_PREFIX="lockss-stack"
 STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
@@ -84,34 +84,34 @@ STACK_NUM=0
 UPDATE_IMAGES=0
 
 clean_up() { # Perform pre-exit housekeeping
-	return
+  return
 }
 
 error_exit() {
-	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
-	clean_up
-	exit 1
+  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+  clean_up
+  exit 1
 }
 
 graceful_exit() {
-	clean_up
-	exit
+  clean_up
+  exit
 }
 
 signal_exit() { # Handle trapped signals
-	case $1 in
-		INT)
-			error_exit "Program interrupted by user" ;;
-		TERM)
-			echo -e "\n$PROGNAME: Program terminated" >&2
-			graceful_exit ;;
-		*)
-			error_exit "$PROGNAME: Terminating on unknown signal" ;;
-	esac
+  case $1 in
+    INT)
+      error_exit "Program interrupted by user" ;;
+    TERM)
+      echo -e "\n$PROGNAME: Program terminated" >&2
+      graceful_exit ;;
+    *)
+      error_exit "$PROGNAME: Terminating on unknown signal" ;;
+  esac
 }
 
 usage() {
-	echo -e "Usage: $PROGNAME [-h|--help] [-u|--update]"
+  echo -e "Usage: $PROGNAME [-h|--help] [-u|--update]"
 }
 
 help_message() {
@@ -129,6 +129,15 @@ _EOF_
   return
 }
 
+# $1=file $2=blankfile
+Config_Or_Blank()
+{
+  if [ -f "${1}/${2}" ]; then
+    echo "${1}/${2}"
+  else
+    echo "${1}/${3}"
+  fi
+}
 
 Check_Physical_Volumes() {
   if [ -z "${LOCKSS_DATA_DIR}" ] || [ -z "${LOCKSS_LOGS_DIR}" ]; then
@@ -140,12 +149,108 @@ Check_Physical_Volumes() {
 # Create a mount points for each stack
 add_stack_volumes()
 {
+  echo "skipping volumes..."
+  #kubectl apply -f lockss-persistent-volumes.yml
+  local stack=$1
+  for svc in "${svcs[@]}"
+  do
+    echo "creating  data and log volumes for $stack-${svc}..."
+    init_one_dir ${LOCKSS_DATA_DIR}/$stack-${svc}-data ${LOCKSS_USER}
+    init_one_dir ${LOCKSS_LOGS_DIR}/$stack-${svc}-logs ${LOCKSS_USER}
+  done
   kubectl apply -f lockss-persistent-volumes.yml
 }
 
-# Create stack network
-add_stack_network() {
+#initialize the service arrays based on system.cfg info.
+init_service_arrays() {
+  if ${USE_LOCKSS_CFG}; then
+    svcs+=("cfg")
+    svcs_confs+=("cfg")
+  fi
+  if ${USE_LOCKSS_MDQ}; then
+    svcs+=("mdq")
+    svcs_confs+=("mdq")
+  fi
+  if ${USE_LOCKSS_MDX}; then
+    svcs+=("mdx")
+    svcs_confs+=("mdx")
+  fi
+  if ${USE_LOCKSS_POL}; then
+    svcs+=("pol")
+    svcs_confs+=("pol")
+  fi
+  if ${USE_LOCKSS_REPO}; then
+    svcs+=("repo")
+    svcs_confs+=("repo")
+  fi
+  if ${USE_LOCKSS_POSTGRES}; then
+    svcs+=("postgres")
+  fi
+  if ${USE_LOCKSS_SOLR}; then
+    svcs+=("solr")
+  fi
+  if ${USE_LOCKSS_HDFS}; then
+    svcs+=("hdfs")
+  fi
+  if ${USE_LOCKSS_PYWB}; then
+    svcs+=("pywb")
+  fi
+  if ${USE_LOCKSS_OPENWB}; then
+    svcs+=("openwb")
+  fi
+}
+
+# Create configs for each stack
+add_stack_configs() {
+  local stack=$1
+  local stack_path="${DOCKER_CONFIGS_DIR}/$stack"
+  local key
+  # Create the global configs
+  msg "Adding global config files"
+  for gconf in "${global_confs[@]}"; do
+    key=${gconf}
+    if ! kubectl create configmap ${key} --from-file=${key}=$(Config_Or_Blank $stack_path "${gconf}" "blank_lockss"); then
+      error_exit "${_0}: error creating config $stack-${gconf}"
+    fi
+    if ! kubectl create configmap ${key}-opt --from-file=${key}-opt=$(Config_Or_Blank $stack_path "${gconf}_opt" "blank_lockss_opt"); then
+      error_exit "${_0}: error creating config $stack-${gconf}_opt"
+    fi
+  done
+  # Create the configs for each lockss service
+  msg "Adding service config files"
+  for sconf in "${svcs_confs[@]}"; do
+    key=${sconf}-service
+    echo "adding service config ${key}..."
+    if ! kubectl create configmap ${key} --from-file=${key}=$(Config_Or_Blank $stack_path "${key}" "blank_lockss"); then
+      error_exit "${_0}: error creating config ${key}"
+    fi
+    if ! kubectl create configmap  ${key}-opt --from-file=${key}-opt=$(Config_Or_Blank $stack_path "${sconf}-service-opt" "blank_lockss_opt"); then
+      error_exit "${_0}: error creating config ${key}-opt"
+    fi
+  done
+}
+
+# Add shared stack elements
+add_stack_shared() {
+  local stack=$1
+
+  msg "Checking for namespace ${stack}..."
+  if ! kubectl get namespace ${stack} ; then
+    kubectl create namespace ${stack}
+  fi
+  msg "setting namespace in context..."
+  kubectl config set-context --current --namespace=${stack}
+  kubectl delete pods,services,configmaps,secrets --all
+  msg "adding storage class: local-storage"
+  kubectl apply -f local-storage.yaml
+  msg "adding networkpolicy..."
   kubectl apply -f lockss-networkpolicy.yml
+  msg "adding secrets..."
+  for sec in "${secrets[@]}"; do
+    if ! kubectl create secret generic ${sec} --from-file "${USEROPTS_DIR}/${sec}"; then
+       error_exit "${_0}: unable to create secret ${sec}"
+    fi
+  done
 }
 
 check_stack_solr() {
@@ -187,9 +292,10 @@ assemble_stack() {
   set +a
   pushd . &>/dev/null
   cd "${DOCKER_CONFIGS_DIR}/$stack"
-  add_stack_network $stack
+  add_stack_shared $stack
   add_stack_volumes $stack
   check_stack_solr $stack
+  add_stack_configs ${stack}
   popd &>/dev/null
 }
 
@@ -233,7 +339,9 @@ fi
 
 # Sanity checks
 #Check_Runnable
-Check_Physical_Volumes
+#Check_Physical_Volumes
+
+init_service_arrays
 
 if [ ${NUM_STACKS} -eq 0 ]; then
   error_exit "No configuration files have been generated, run generate-lockss first."
@@ -252,6 +360,6 @@ fi
 msg ""
 msg "Successfully installed volumes and networks."
 msg ""
-msg "Run deploy-lockss to deploy the assembled stack(s)."
+msg "Run deploy-lockss to deploy the assembled stacks."
 
 graceful_exit
diff --git a/scripts/generate-lockss b/scripts/generate-lockss
--- a/scripts/generate-lockss
+++ b/scripts/generate-lockss
@@ -64,6 +64,7 @@ USEROPTS_DIR="${CONFIG_DIR}/useropts"
 
 # Files
 ENV_TMPL="${CONFIG_DIR}/env.mustache"
+STORAGE_CLASS="${CONFIG_DIR}/local-storage.yaml"
 COMPOSE_TMPL="${CONFIG_DIR}/docker-compose.mustache"
 SYSTEM_CONF_FILE="${CONFIG_DIR}/system.cfg"
 
@@ -74,34 +75,34 @@ PORT_BASE=245
 declare -i STACK_COUNT=1
 
 clean_up() { # Perform pre-exit housekeeping
-	return
+  return
 }
 
 error_exit() {
-	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
-	clean_up
-	exit 1
+  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+  clean_up
+  exit 1
 }
 
 graceful_exit() {
-	clean_up
-	exit
+  clean_up
+  exit
 }
 
 signal_exit() { # Handle trapped signals
-	case $1 in
-		INT)
-			error_exit "Program interrupted by user" ;;
-		TERM)
-			echo -e "\n$PROGNAME: Program terminated" >&2
-			graceful_exit ;;
-		*)
-			error_exit "$PROGNAME: Terminating on unknown signal" ;;
-	esac
+  case $1 in
+    INT)
+      error_exit "Program interrupted by user" ;;
+    TERM)
+      echo -e "\n$PROGNAME: Program terminated" >&2
+      graceful_exit ;;
+    *)
+      error_exit "$PROGNAME: Terminating on unknown signal" ;;
+  esac
 }
 
 usage() {
-	echo -e "Usage: $PROGNAME [-h|--help] [<num stacks>]"
+  echo -e "Usage: $PROGNAME [-h|--help] [<num stacks>]"
 }
 
 help_message() {
@@ -165,18 +166,19 @@ for (( num=1 ; num<=$STACK_COUNT ; num++)); do
   fi
   export STACK_NAME
   export STACK_LCAP_PORT=$((${LOCKSS_V3_PORT} + $num -1))
-  stack_config_dir="${DOCKER_CONFIGS_DIR}/${STACK_NAME}"
-  stack_env_file="${stack_config_dir}/env.sh"
-  stack_compose_file="${stack_config_dir}/docker-compose.yml"
+  export STACK_CONFIG_DIR="${DOCKER_CONFIGS_DIR}/${STACK_NAME}"
+  stack_env_file="${STACK_CONFIG_DIR}/env.sh"
+  stack_compose_file="${STACK_CONFIG_DIR}/docker-compose.yml"
 
   echo "Stack ${num} named ${STACK_NAME} is using port base of ${STACK_PORT_BASE}."
-  mkdir -p "${stack_config_dir}"
+  mkdir -p "${STACK_CONFIG_DIR}"
 
   echo "generate the stack env.sh file..."
   mo "${ENV_TMPL}" > "${stack_env_file}"
   set -a
   . "${stack_env_file}"
   set +a
+  cp "${LOCAL_STORAGE}" "${STACK_CONFIG_DIR}/"
   export POSTGRES_PASSWD="{{ secret \"lockss-postgres-pass\" }}"
 
   #msg "${PROGNAME}:  Generating stack docker-compose file..."
@@ -185,7 +187,7 @@ for (( num=1 ; num<=$STACK_COUNT ; num++)); do
   #add the lockss config file templates
   for f in ${CONFIG_DIR}/templates/*.mustache ; do
     src="${f}"
-    dst="${stack_config_dir}/$(basename "${f}" .mustache)"
+    dst="${STACK_CONFIG_DIR}/$(basename "${f}" .mustache)"
     msg "${PROGNAME}:  Rendering ${src} to ${dst}..."
     mo "${src}" > "${dst}"
   done
@@ -193,7 +195,7 @@ for (( num=1 ; num<=$STACK_COUNT ; num++)); do
   for f in ${USEROPTS_DIR}/templates/*_opt.mustache ; do
     if [[ -f "${f}" ]]; then
       src="${f}"
-      dst="${stack_config_dir}/$(basename "${f}" .mustache)"
+      dst="${STACK_CONFIG_DIR}/$(basename "${f}" _opt.mustache)-opt"
       msg "${PROGNAME}:  Rendering ${src} to ${dst}..."
       mo "${src}" > "${dst}"
     fi
@@ -202,7 +204,7 @@ for (( num=1 ; num<=$STACK_COUNT ; num++)); do
   for f in ${USEROPTS_DIR}/*_opt ; do
     if [[ -f "${f}" ]]; then
       src="${f}"
-      dst="${stack_config_dir}/$(basename "$f")"
+      dst="${STACK_CONFIG_DIR}/$(basename "${f}" _opt)-opt"
       msg "${PROGNAME}:  Copying ${src} to ${dst}..."
       cp "${src}" "${dst}"
     fi
