merge of feature-logger changes

diff --git a/scripts/assemble-lockss b/scripts/assemble-lockss
--- a/scripts/assemble-lockss
+++ b/scripts/assemble-lockss
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 # ---------------------------------------------------------------------------
-# assemble-lockss - Assemble lockss stack by installing generated configs files, volumes and networks..
-
-# Copyright (c) 2000-2019, Board of Trustees of Leland Stanford Jr. University
+# assemble-lockss - Generate and assemble files needed to run a LOCKSS stack
+#
+# Copyright (c) 2000-2021, Board of Trustees of Leland Stanford Jr. University
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -31,10 +31,9 @@
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
 #
-# Usage: assemble [-h|--help] [-u|--update]
+# Usage: assemble-lockss [-h|--help] [-u|--update] <num stacks>
 #
 # Revision history:
-# 2019-04-18 version 1
 # ---------------------------------------------------------------------------
 PROGNAME=${0##*/}
 VERSION="1.0"
@@ -51,36 +50,50 @@ _D0=$(dirname "${0}")
 ##
 
 . "${_D0}/_util"
+. "${_D0}/lib/mo"
 
 ##
 ## Definitions
 ##
+# Directories
+USEROPTS_DIR="${CONFIG_DIR}/useropts"
+SERVICES_DIR="${TEMPLATES_DIR}/svcs"
+MK_DIR="${TEMPLATES_DIR}/mk"
 
 # Files
+ENV_TMPL="${CONFIG_DIR}/env.mustache"
+COMPOSE_TMPL="${CONFIG_DIR}/docker-compose.mustache"
 SYSTEM_CONF_FILE="${CONFIG_DIR}/system.cfg"
+STORAGE_CLASS_FILE="local-storage.yaml"
+
 EMPTY_LOCKSS_TXT="${TEMPLATES_DIR}/blank_lockss.txt"
 EMPTY_LOCKSS_OPT="${TEMPLATES_DIR}/blank_lockss.opt"
 
-#Data
+
+# Variables
+declare -i STACK_COUNT=1
+declare -a secrets=("lockss-ui-pass" "lockss-auth" "lockss-postgres-pass")
 declare -a arr global_confs=("lockss-cluster" "lockss-bootstrap" "repo-properties" "lockss-solr-log4j-properties")
 declare -a arr svcs
 declare -a arr svcs_confs
 declare -a arr lockss_owned
-
-KUBECTL='microk8s kubectl -n lockss'
 
 STACK_PREFIX="lockss-stack"
 STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
 NUM_STACKS=${#STACK_DIRS[@]}
 STACK_NUM=0
 UPDATE_IMAGES=0
+PORT_BASE=245
+PULL_POLICY="IfNotPresent"
+
+KUBECTL='microk8s kubectl -n lockss'
 
 clean_up() { # Perform pre-exit housekeeping
-  return
+  log_script_exit  "${PROGNAME}"
 }
 
 error_exit() {
-  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+  logger_fatal "${1:-"Unknown Error"}" >&2
   clean_up
   exit 1
 }
@@ -96,28 +109,30 @@ signal_exit() { # Handle trapped signals
     error_exit "Program interrupted by user"
     ;;
   TERM)
-    echo -e "\n$PROGNAME: Program terminated" >&2
+    logger_error "Program terminated"
     graceful_exit
     ;;
   *)
-    error_exit "$PROGNAME: Terminating on unknown signal"
+    error_exit "Terminating on unknown signal"
     ;;
   esac
 }
 
 usage() {
-  echo -e "Usage: $PROGNAME [-h|--help] [-u|--update]"
+  echo -e "Usage: $PROGNAME [-h|--help]  [-u|--update] [<num stacks>]"
 }
 
 help_message() {
   cat <<-_EOF_
   $PROGNAME ver. $VERSION
-  This script will take the generated stack and add necessary elements to docker.
+  Generate files needed to run a LOCKSS stack and assemble them for deployment.
 
   $(usage)
 
   Options:
   -h, --help  Display this help message and exit.
+  -u, --update  force update of LOCKSS docker images
+  <num stacks> Optional number of stacks to run on this host.
 
 _EOF_
   return
@@ -134,16 +149,13 @@ Config_Or_Blank() {
 
 Check_Physical_Volumes() {
   if [ -z "${LOCKSS_DATA_DIR}" ]; then
-    echo "LOCKSS_DATA_DIR is not set; exiting"
-    exit 1
+    error_exit "LOCKSS_DATA_DIR is not set; exiting"
   fi
   if  [ -z "${LOCKSS_LOGS_DIR}" ]; then
-    echo "LOCKSS_LOGS_DIR is not set; exiting"
-    exit 1
+    error_exit "LOCKSS_LOGS_DIR is not set; exiting"
   fi
   if [ -z "${LOCKSS_TMPDIR}" ]; then
-    echo "LOCKSS_TMPDIR are not set; exiting"
-    exit 1
+    error_exit "LOCKSS_TMPDIR are not set; exiting"
   fi
 }
 
@@ -201,7 +213,7 @@ ensure_writable_dir() {
   if [ $USER -eq ${LOCKSS_UID} ]; then
      return 0
   else
-    msg "${PROGNAME}: ${DIR} is not writable by ${LOCKSS_USER}; attempting to chown it."
+    logger_warn "${DIR} is not writable by ${LOCKSS_USER}; attempting to chown it."
     sudo chown -R ${LOCKSS_UID}:${LOCKSS_GID} "${DIR}"
   fi
 }
@@ -209,11 +221,11 @@ ensure_writable_dir() {
 ensure_lockss_owner() {
   for svc in "${lockss_owned[@]}"; do
     data_dir=${LOCKSS_DATA_DIR}/$stack-${svc}-data
-    find "${data_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {}
+    sudo find "${data_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {}
     logs_dir=${LOCKSS_LOGS_DIR}/$stack-${svc}-logs
-    find "${logs_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {}
+    sudo find "${logs_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {}
     tmp_dir=${LOCKSS_TMPDIR}/$stack-${svc}-tmp
-    find "${tmp_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {}
+    sudo find "${tmp_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {}
   done
 }
 
@@ -223,7 +235,7 @@ add_stack_configs() {
   local stack_path="${DOCKER_CONFIGS_DIR}/$stack"
   local key
   # Create the global configs
-  msg "${PROGNAME}:  Adding global config files"
+  logger_info "Adding global config files"
   for gconf in "${global_confs[@]}"; do
     key=${gconf}
     if ! $KUBECTL create configmap ${key} --namespace=${LOCKSS_NAMESPACE} --from-file=${key}=$(Config_Or_Blank $stack_path "${gconf}" "blank_lockss"); then
@@ -234,10 +246,10 @@ add_stack_configs() {
     fi
   done
   # Create the configs for each lockss service
-  msg "${PROGNAME}:  Adding service config files"
+  logger_info "Adding service config files"
   for sconf in "${svcs_confs[@]}"; do
     key=${sconf}-service
-    echo "adding service config ${key}..."
+    logger_debug "adding service config ${key}..."
    if ! $KUBECTL create configmap ${key} --namespace=${LOCKSS_NAMESPACE} --from-file=${key}=$(Config_Or_Blank $stack_path "${key}" "blank_lockss"); then
       error_exit "${_0}: error creating config ${key}"
     fi
@@ -252,11 +264,11 @@ add_stack_configs() {
 add_stack_shared() {
   local stack=$1
   local mk_dir="${DOCKER_CONFIGS_DIR}/$stack/mk"
-  msg "${PROGNAME}:  clearing old deployments..."
-  $KUBECTL delete deployments,pvc -l lockss-stack-id=${stack}
-  msg "${PROGNAME}:  clearing old  configmaps..."
+  logger_debug "Clearing old deployments..."
+  $KUBECTL delete deployments -l lockss-stack-id=${stack}
+  logger_debug "Clearing old  configuration maps..."
   $KUBECTL delete configmaps --all
-  msg "${PROGNAME}:  adding storage class: local-storage from ${mk_dir}/local-storage.yaml"
+  logger_debug "Applying storage class: local-storage from ${mk_dir}/local-storage.yaml"
   microk8s kubectl apply -f "${mk_dir}/local-storage.yaml"
 }
 
@@ -270,18 +282,18 @@ check_stack_solr() {
   OLD_REPO="${SOLR_HOME_PATH}/${SOLR_CORE_REPO}"
   SOLR_CONFIG_PATH="${SOLR_HOME_PATH}/configsets/lockss"
 
-  msg "${PROGNAME}:  Checking solr installation at ${SOLR_HOME_PATH}..."
+  logger_info "Checking solr installation at ${SOLR_HOME_PATH}..."
 
   if [ -d "${OLD_REPO}" ]; then
     error_exit "You are attempting to run with an older version without updating, please run upgrade script"
   fi
-  msg "${PROGNAME}:  Checking solr installation for essential files..."
+  logger_info "Checking solr installation for essential files..."
 
-  if [ ! -e "${SOLR_FILE}"  -o ! -e "${CORE_PATH}" ]; then
-    msg "${PROGNAME}:  Preparing solr home '${SOLR_HOME_PATH}' for new install..."
+  if [ ! -e "${SOLR_FILE}" -o ! -e "${CORE_PATH}" ]; then
+    logger_info "Preparing solr home '${SOLR_HOME_PATH}' for new install..."
     ensure_writable_dir ${SOLR_HOME_PATH} ||
       error_exit "Unable to write to ${SOLR_HOME_PATH}"
-    tar -xzf "${UPDATES_DIR}/solr-home.tar.gz" -C "${SOLR_HOME_PATH}" >/dev/null ||
+    tar -xzf "${UPDATES_DIR}/solr-home.tar.gz"-C "${SOLR_HOME_PATH}">/dev/null ||
       error_exit "Unable to install LOCKSS solr files, exiting..."
   fi
 }
@@ -294,9 +306,9 @@ add_stack_volumes() {
   ensure_writable_dir $LOCKSS_DATA_DIR
   ensure_writable_dir $LOCKSS_LOGS_DIR
   ensure_writable_dir $LOCKSS_TMPDIR
-
+  logger_info "Creating data and log volumes for $stack"
  for svc in "${svcs[@]}"; do
-    msg "${PROGNAME}:  creating data and log volumes for $stack-${svc}..."
+    logger_debug "Creating data and log volumes for $stack-${svc}..."
     mtpoint=${LOCKSS_DATA_DIR}/$stack-${svc}-data
     mkdir -p ${mtpoint} || error_exit "unable to create data dir: ${mtpoint}"
     mtpoint=${LOCKSS_LOGS_DIR}/$stack-${svc}-logs
@@ -314,23 +326,23 @@ add_additional_stack_volumes() {
   IFS=';' read -r -a datadirs <<<"${LOCKSS_REPO_HOST_DIRS}"
   len=${#datadirs[@]}
   start=1
-  msg "${PROGNAME}:  creating additional data volumes for $stack-repository-service..."
+  logger_debug "Creating additional data volumes for $stack-repository-service..."
   for ((cnt = $start; cnt < $len; cnt++)); do
     mtpoint=${datadirs[$cnt]}/$stack-repo-data
-    mkdir -p ${mtpoint} || error_exit "unable to create data dir: ${mtpoint}"
+    mkdir -p ${mtpoint} || error_exit "Unable to create data dir: ${mtpoint}"
     mtname=$stack-repo-data${cnt}
   done
 }
 
 assemble_stack() {
   local stack=${STACK_PREFIX}$1
-  echo "Processing stack $stack"
+  logger_info "Processing stack $stack"
   # Source config.info and env.sh for this stack
   set -a
   . "${DOCKER_CONFIGS_DIR}/$stack/env.sh"
   set +a
   pushd . &>/dev/null
-  cd "${DOCKER_CONFIGS_DIR}/$stack" || error_exit "Unable to cd to ${DOCKER_CONFIGS_DIR}/$stack."
+  cd "${DOCKER_CONFIGS_DIR}/$stack"|| error_exit "Unable to cd to ${DOCKER_CONFIGS_DIR}/$stack."
   add_stack_shared ${stack}
   add_stack_volumes ${stack}
   add_stack_configs ${stack}
@@ -338,12 +350,125 @@ assemble_stack() {
   popd &>/dev/null
 }
 
-###
-# Start
-###
+generate_lockss() {
+	logger_info "Removing old generated configuration files..."
+	rm -rf "${DOCKER_CONFIGS_DIR}"
+	logger_info "Generating config files for $STACK_COUNT stacks..."
+	for ((num = 1; num <= $STACK_COUNT; num++)); do
+		export STACK_PORT_BASE=$((${PORT_BASE} + $num))
+		if [ ${STACK_COUNT} = 1 ]; then
+			STACK_NAME="${STACK_PREFIX}"
+		else
+			STACK_NAME="${STACK_PREFIX}$num"
+		fi
+    logger_info "Generating files for stack $STACK_NAME"
+    export STACK_NAME
+    export STACK_LCAP_PORT=$((${LOCKSS_V3_PORT} + $num - 1))
+    export STACK_CONFIG_DIR="${DOCKER_CONFIGS_DIR}/${STACK_NAME}"
+    stack_env_file="${STACK_CONFIG_DIR}/env.sh"
+    stack_compose_file="${STACK_CONFIG_DIR}/docker-compose.yml"
+    logger_debug "Stack ${num} named ${STACK_NAME} is using port base of ${STACK_PORT_BASE}."
+    mkdir -p "${STACK_CONFIG_DIR}"
+
+    logger_debug "Generating the stack env.sh file..."
+    mo "${ENV_TMPL}" >"${stack_env_file}"
+    set -a
+    . "${stack_env_file}"
+    set +a
+
+    logger_debug "Getting node hostname..."
+    export NODE_HOSTNAME=$(microk8s kubectl get nodes -o jsonpath='{.items[*].status.addresses[?(@.type=="Hostname")].address}')
+    logger_degug "Getting postgres password..."
+    export POSTGRES_PASSWD=$(microk8s kubectl get secret -n lockss lockss-postgres-pass -o jsonpath='{.data.lockss-postgres-pass}'| base64 --decode -)
+
+    IFS=';' read -r -a datadirs <<<"${LOCKSS_REPO_HOST_DIRS}"
+    len=${#datadirs[@]}
+    REPO_NUMS[0]=""
+    export REPO_DATA_MAP_=${datadirs[0]}
+    for ((count = 1; count < $len; count++)); do
+      REPO_NUMS[${count}]="$count"
+      declare REPO_DATA_MAP_${count}=${datadirs[$count]}
+      varname=REPO_DATA_MAP_${count}
+      export $varname
+    done
+    export REPO_NUMS
+    logger_info "Generating the service deployments..."
+    mkdir "${STACK_CONFIG_DIR}/svcs"
+    for f in ${SERVICES_DIR}/*.mustache; do
+      src="${f}"
+      dst="${STACK_CONFIG_DIR}/svcs/$(basename "${f}" .mustache).yaml"
+      logger_debug "Rendering ${src} to ${dst}..."
+      mo "${src}" >"${dst}"
+    done
+    logger_info "Generating the microk8s files..."
+    mk_dst="${STACK_CONFIG_DIR}/mk"
+    mkdir "${mk_dst}"
+    cp "${MK_DIR}/${STORAGE_CLASS_FILE}" "${mk_dst}/${STORAGE_CLASS_FILE}"
+    for f in ${MK_DIR}/*.mustache; do
+      src="${f}"
+      dst="${mk_dst}/$(basename "${f}" .mustache).yaml"
+      logger_debug "Rendering ${src} to ${dst}..."
+      mo "${src}" >"${dst}"
+      envsubst < ${dst} > ${dst}.out
+      mv ${dst}.out ${dst}
+    done
+    logger_info "Generating lockss configuration files..."
+    for f in ${TEMPLATES_DIR}/*.mustache; do
+      src="${f}"
+      dst="${STACK_CONFIG_DIR}/$(basename "${f}" .mustache)"
+      logger_debug "Rendering ${src} to ${dst}..."
+      mo "${src}" >"${dst}"
+    done
+    logger_info "Generating the user configuration files..."
+    for f in ${USEROPTS_DIR}/templates/*_opt.mustache; do
+      if [[ -f "${f}" ]]; then
+        src="${f}"
+        dst="${STACK_CONFIG_DIR}/$(basename "${f}" _opt.mustache)-opt"
+        logger_debug "Rendering ${src} to ${dst}..."
+        mo "${src}" >"${dst}"
+      fi
+    done
+  done
+	logger_info "Successfully regenerated stack components."
+}
+
+assemble_lockss() {
+
+	NUM_STACKS=${#STACK_DIRS[@]}
+
+	if [ ${NUM_STACKS} -eq 0 ]; then
+		error_exit "No configuration files have been generated, run generate-lockss first."
+	elif [ ${NUM_STACKS} -eq 1 ]; then
+		assemble_stack ""
+	elif [ ${STACK_NUM} -eq 0 ]; then
+		for ((num = 1; num <= $NUM_STACKS; num++)); do
+			assemble_stack $num
+		done
+	elif [ -e "${DOCKER_CONFIGS_DIR}/${STACK_PREFIX}${STACK_NUM}" ]; then
+		assemble_stack ${STACK_NUM}
+	else
+		error_exit "Unable to find generated stack ${STACK_NUM}"
+	fi
+	logger_info "Successfully installed components."
+
+}
+
+##
+## MAIN
+##
+
 # Trap signals
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT" INT
+
+# Source system config file
+set -a
+. "${SYSTEM_CONF_FILE}"
+set +a
+
+logger_init
+log_script_entry "${PROGNAME}"
+umask 002
 
 # Parse command-line
 while [[ -n $1 ]]; do
@@ -352,55 +477,35 @@ while [[ -n $1 ]]; do
     help_message
     graceful_exit
     ;;
+  -u | --update)
+    PULL_POLICY="Always"
+    logger_info "Forcing update of LOCKSS docker images"
+    ;;
   [1-9])
-    STACK_NUM=$1
+    STACK_COUNT=$1
     ;;
   -* | --*)
     usage
     error_exit "Unknown option $1"
     ;;
   *)
-    echo "Argument $1 to process..."
+    logger_debug "Argument $1 to process..."
     ;;
   esac
   shift
 done
 
-# Main logic
-
-# Source system config file
-set -a
-. "${SYSTEM_CONF_FILE}"
-set +a
-
+# Sanity checks
 if $(am_i_root); then
   error_exit "This script should not be run as root. Run as the lockss user."
 fi
-umask 002
-
-# Sanity checks
-msg "${PROGNAME}:  Checking install..."
+logger_info "Checking system..."
 Check_Runnable
 Check_Physical_Volumes
 
 init_service_arrays
 
-if [ ${NUM_STACKS} -eq 0 ]; then
-  error_exit "No configuration files have been generated, run generate-lockss first."
-elif [ ${NUM_STACKS} -eq 1 ]; then
-  assemble_stack ""
-elif [ ${STACK_NUM} -eq 0 ]; then
-  for ((num = 1; num <= $NUM_STACKS; num++)); do
-    assemble_stack $num
-  done
-elif [ -e "${DOCKER_CONFIGS_DIR}/${STACK_PREFIX}${STACK_NUM}" ]; then
-  assemble_stack ${STACK_NUM}
-else
-  error_exit "Unable to find generated stack ${STACK_NUM}"
-fi
-msg "--------------------------------------------------------------------"
-msg "${PROGNAME}:  Successfully installed components."
-msg "${PROGNAME}:  Run deploy-lockss to deploy the services."
-msg "--------------------------------------------------------------------"
-
+generate_lockss || error_exit "Unable to generate needed components."
+assemble_lockss || error_exit "Unable to assemble all lockss components."
+logger_info "LOCKSS is ready to deploy."
 graceful_exit
diff --git a/scripts/deploy-lockss b/scripts/deploy-lockss
--- a/scripts/deploy-lockss
+++ b/scripts/deploy-lockss
@@ -68,11 +68,11 @@ STACK_PREFIX="lockss-stack"
 KUBECTL="microk8s kubectl -n lockss"
 
 clean_up() { # Perform pre-exit housekeeping
-  return
+  log_script_exit  "${PROGNAME}"
 }
 
 error_exit() {
-  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+  logger_fatal "${1:-"Unknown Error"}" >&2
   clean_up
   exit 1
 }
@@ -85,14 +85,14 @@ graceful_exit() {
 signal_exit() { # Handle trapped signals
   case $1 in
   INT)
-    error_exit "Program interrupted by user"
+    logger_info "Program interrupted by user"
     ;;
   TERM)
-    echo -e "\n$PROGNAME: Program terminated" >&2
+    logger_error "Program terminated"
     graceful_exit
     ;;
   *)
-    error_exit "$PROGNAME: Terminating on unknown signal"
+    error_exit "Terminating on unknown signal"
     ;;
   esac
 }
@@ -172,7 +172,7 @@ init_service_arrays() {
 
 # Check our secrets
 check_installed_secrets() {
-  echo "checking installed secrets..."
+  logger_info "checking installed secrets..."
   Check_Secret 'lockss-postgres-pass'
   Check_Secret 'lockss-ui-pass'
   Check_Secret 'lockss-auth'
@@ -182,7 +182,7 @@ check_installed_volumes() {
   local stack=$1
   # Check the mountpoints
   for svc in "${svcs[@]}"; do
-    echo "checking docker mountpoints for $stack-${svc}..."
+    logger_info "checking docker mountpoints for $stack-${svc}..."
     Check_Volume "$stack-${svc}-data"
     Check_Volume "$stack-${svc}-logs  "
   done
@@ -198,10 +198,12 @@ deploy_stack() {
   set +a
   pushd . &>/dev/null
   for svc in "${deploy_service_names[@]}"; do
-    echo "Deploying service from ${svc}..."
+    logger_trace "Deploying service from ${svc}..."
     $KUBECTL apply -f "${DOCKER_CONFIGS_DIR}/$stack/svcs/${svc}.yaml"
-#ß    $KUBECTL expose deployment $svc
+#    $KUBECTL expose deployment $svc
   done
+  $KUBECTL wait --for=condition=Ready --all pods --timeout=60s
+  #todo: Add new waitfor here
   popd &>/dev/null
 }
 
@@ -211,6 +213,16 @@ deploy_stack() {
 # Trap signals
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT" INT
+# Source system config file
+
+set -a
+. "${SYSTEM_CONF_FILE}"
+set +a
+
+#init the logger and mark script entry
+logger_init
+log_script_entry "${PROGNAME}"
+umask 002
 
 STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
 NUM_STACKS=${#STACK_DIRS[@]}
@@ -226,7 +238,7 @@ while [[ -n $1 ]]; do
   -a | --args)
     shift
     export ARGS_ADDITIONAL="$1"
-    msg "Adding additional runtime args $ARGS_ADDITIONAL"
+    logger_debug "Adding additional runtime args $ARGS_ADDITIONAL"
     shift
     ;;
   [1-9])
@@ -237,20 +249,17 @@ while [[ -n $1 ]]; do
     error_exit "Unknown option $1"
     ;;
   *)
-    echo "Argument $1 to process..."
+    logger_trace "Argument $1 to process..."
     ;;
   esac
   shift
 done
-
-set -a
-. "${SYSTEM_CONF_FILE}"
-set +a
+# Sanity checks
+logger_info "Checking system..."
 
 if $(am_i_root); then
   error_exit "This script should not be run as root. Run as the lockss user."
 fi
-umask 002
 Check_Runnable
 
 init_service_arrays
@@ -260,7 +269,7 @@ if [ ${NUM_STACKS} -eq 0 ]; then
 elif [ ${NUM_STACKS} -eq 1 ]; then
   deploy_stack ""
 elif [ ${STACK_NUM} -eq 0 ]; then
-  echo "Installing ${NUM_STACKS} stacks found in ${DOCKER_CONFIGS_DIR}"
+  logger_info "Deploying ${NUM_STACKS} stacks found in ${DOCKER_CONFIGS_DIR}"
   for ((num = 1; num <= $NUM_STACKS; num++)); do
     deploy_stack $num
   done
diff --git a/scripts/restart-lockss b/scripts/restart-lockss
--- a/scripts/restart-lockss
+++ b/scripts/restart-lockss
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/env bash
 # ---------------------------------------------------------------------------
 # restart-lockss - "Restart the running LOCKSS stack."
 # Copyright (c) 2019, Board of Trustees of Leland Stanford Jr. University
@@ -46,17 +46,19 @@ _D0=$(dirname "${0}")
 ##
 
 . "${_D0}/_util"
+SYSTEM_CONF_FILE="${CONFIG_DIR}/system.cfg"
+
 
 UPDATE_ARG=""
 
 clean_up() { # Perform pre-exit housekeeping
-	return
+  log_script_exit  "${PROGNAME}"
 }
 
 error_exit() {
-	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
-	clean_up
-	exit 1
+  logger_fatal "${1:-"Unknown Error"}" >&2
+  clean_up
+  exit 1
 }
 
 graceful_exit() {
@@ -101,6 +103,14 @@ _EOF_
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT"  INT
 
+# Source system config file
+set -a
+. "${SYSTEM_CONF_FILE}"
+set +a
+
+logger_init
+log_script_entry "${PROGNAME}"
+umask 002
 
 ARGS_ADDITIONAL=""
 # Parse command-line
@@ -110,18 +120,18 @@ while [[ -n $1 ]]; do
       help_message; graceful_exit ;;
     -u | --update)
       UPDATE_ARG="-u"
-      msg "Forcing update of LOCKSS docker images"
+      logger_info "Forcing update of LOCKSS docker images"
       ;;
     -a | --args)
       shift
       export ARGS_ADDITIONAL="$1"
-      echo "Adding additional runtime args $ARGS_ADDITIONAL";
+      logger_info "Adding additional runtime args $ARGS_ADDITIONAL";
     ;;
     -*)
       usage
       error_exit "Unknown option $1" ;;
     *)
-      echo "Argument $1 to process..." ;;
+      logger_debug "Argument $1 to process..." ;;
   esac
   shift
 done
@@ -133,15 +143,12 @@ if $(am_i_root); then
   error_exit "This script should not be run as root. Run as the lockss user."
 fi
 
-
-"${SCRIPTS_DIR}"/shutdown-lockss &&
+"${SCRIPTS_DIR}"/stop-lockss && logger_info "LOCKSS stack has been stopped."
 if [ -n "${UPDATE_ARG}" ]; then
-  "${SCRIPTS_DIR}"/generate-lockss ${UPDATE_ARG} &&
-  "${SCRIPTS_DIR}"/assemble-lockss &&
-  "${SCRIPTS_DIR}"/deploy-lockss -a "$ARGS_ADDITIONAL"
-else
-  "${SCRIPTS_DIR}"/deploy-lockss -a "$ARGS_ADDITIONAL"
+  "${SCRIPTS_DIR}"/assemble-lockss ${UPDATE_ARG}
 fi
+logger_info "Restarting LOCKSS stack"
+"${SCRIPTS_DIR}"/deploy-lockss -a "$ARGS_ADDITIONAL"
 
 graceful_exit
 
diff --git a/scripts/start-lockss b/scripts/start-lockss
--- a/scripts/start-lockss
+++ b/scripts/start-lockss
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/env bash
 # ---------------------------------------------------------------------------
 # Start-lockss - "Start the stopped or new LOCKSS stack."
 # Copyright (c) 2019, Board of Trustees of Leland Stanford Jr. University
@@ -47,33 +47,38 @@ _D0=$(dirname "${0}")
 
 . "${_D0}/_util"
 
+SYSTEM_CONF_FILE="${CONFIG_DIR}/system.cfg"
+
 UPDATE_ARG=""
 
 clean_up() { # Perform pre-exit housekeeping
-	return
+  log_script_exit  "${PROGNAME}"
 }
 
 error_exit() {
-	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
-	clean_up
-	exit 1
+  logger_error "${1:-"Unknown Error"}"
+  clean_up
+  exit 1
 }
 
 graceful_exit() {
-	clean_up
-	exit
+  clean_up
+  exit
 }
 
 signal_exit() { # Handle trapped signals
-	case $1 in
-		INT)
-			error_exit "Program interrupted by user" ;;
-		TERM)
-			echo -e "\n$PROGNAME: Program terminated" >&2
-			graceful_exit ;;
-		*)
-			error_exit "$PROGNAME: Terminating on unknown signal" ;;
-	esac
+  case $1 in
+  INT)
+    error_exit "Program interrupted by user"
+    ;;
+  TERM)
+    logger_error "Program terminated"
+    graceful_exit
+    ;;
+  *)
+    error_exit "Terminating on unknown signal"
+    ;;
+  esac
 }
 
 usage() {
@@ -101,6 +106,15 @@ _EOF_
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT"  INT
 
+# Source system config file
+set -a
+. "${SYSTEM_CONF_FILE}"
+set +a
+
+#init the logger and mark script entry
+logger_init
+log_script_entry "${PROGNAME}"
+
 
 ARGS_ADDITIONAL=""
 # Parse command-line
@@ -110,18 +124,18 @@ while [[ -n $1 ]]; do
       help_message; graceful_exit ;;
     -u | --update)
       UPDATE_ARG="-u"
-      msg "Forcing update of LOCKSS docker images"
+      logger_info "Forcing update of LOCKSS docker images"
       ;;
     -a | --args)
       shift
       export ARGS_ADDITIONAL="$1"
-      echo "Adding additional runtime args $ARGS_ADDITIONAL";
+      logger_info "Adding additional runtime args $ARGS_ADDITIONAL";
     ;;
     -* | --*)
       usage
       error_exit "Unknown option $1" ;;
     *)
-      echo "Argument $1 to process..." ;;
+      logger_trace "Argument $1 to process..." ;;
   esac
   shift
 done
@@ -134,21 +148,19 @@ if $(am_i_root); then
 fi
 
 if $(is_lockss_running); then
-  msg "There is already a running lockss stack."
+  logger_warn "There is already a running lockss stack."
   ask_for_input "Okay to stop the lockss-stack and restart?" "Y"
   if is_yes "${ANS}"; then
-    "${_D0}"/shutdown-lockss && sleep 5 && msg "Preparing to start stack..."
+    "${_D0}"/stop-lockss && logger_info "Preparing to start stack..."
   else
     error_exit "Call shutdown-lockss and then run start-lockss again."
   fi
 fi
 
-echo "Scripts dir ${SCRIPTS_DIR}"
+logger_debug "Scripts dir ${SCRIPTS_DIR}"
 
-"${SCRIPTS_DIR}"/generate-lockss ${UPDATE_ARG} &&
-"${SCRIPTS_DIR}"/assemble-lockss &&
+"${SCRIPTS_DIR}"/assemble-lockss ${UPDATE_ARG} &&
 "${SCRIPTS_DIR}"/deploy-lockss -a "$ARGS_ADDITIONAL"
-
 
 graceful_exit
 
