2.0-alpha2c point release
Squashed commit of the following:

commit 57bd41c996b5e1fd6e4d9afed9e4b3e613b55918
Author: Claire Griffin <clairetg@stanford.edu>
Date:   Sun Feb 16 21:05:59 2020 -0800

    fix permission errors

commit 0c1a58d388ca60b3611b5cc3c050ec61b845ced7
Author: Claire Griffin <clairetg@stanford.edu>
Date:   Sun Feb 16 09:12:36 2020 -0800

    Add fail checks.  Use the ownership of the old lockss-solr core and restore it at the end.

commit 8f0b03738fc52160302b048cf301e82f09e8eba5
Author: Claire Griffin <clairetg@stanford.edu>
Date:   Sun Feb 16 08:53:57 2020 -0800

    add solr creation with the v3 lockss configset

commit ecc4983133fc3f0e7f6557ab9e771b85d36a249e
Author: Claire Griffin <clairetg@stanford.edu>
Date:   Sun Feb 16 08:47:21 2020 -0800

    lockss configsets

commit 0cdbcbf9cf07a4e9796156864314726d908846f7
Author: Claire Griffin <clairetg@stanford.edu>
Date:   Fri Feb 14 03:48:26 2020 -0800

    add a check for each stacks solr install
    add a check for java 8
    fix logic for upgrade when solr has never run, fix file permissions for upgrades.

diff --git a/scripts/check_sys b/scripts/check_sys
--- a/scripts/check_sys
+++ b/scripts/check_sys
@@ -233,6 +233,22 @@ ensure_docker_swarm() {
   fi
 }
 
+ensure_java() {
+    if ! which java &> /dev/null; then
+      err "${_0}: Java not found on the PATH (${PATH})"
+      err "${_0}: LOCKSS requires java versions greater than 8 to be installed."
+      error_exit "See instructions: https://openjdk.java.net/install/"
+    else
+      jver=$(java -version 2>&1 | head -1 | cut -d'"' -f2 | sed '/^1\./s///' | cut -d'.' -f1)
+      if [ ${jver} -ge 8 ]; then
+        echo "Found java version ${jver}."
+      else
+        err "Java version is too old. LOCKSS requires versions greater than 8, your version is java ${jver}."
+        error_exit "See instructions: https://openjdk.java.net/install/"
+      fi
+    fi
+}
+
 # Trap signals
 trap "signal_exit TERM" TERM HUP
 trap "signal_exit INT" INT
@@ -277,7 +293,7 @@ if [ "X${LOCKSS_IPADDR}" = X ]; then
 fi
 IP_OK=N
 until is_yes ${IP_OK}; do
-  ask_for_input "IP address of this machine" ${LOCKSS_IPADDR}
+  ask_for_input "IP address of this machine?" ${LOCKSS_IPADDR}
   if valid_ip_address "${ANS}"; then
     LOCKSS_IPADDR="${ANS}"
     IP_OK=Y
@@ -292,5 +308,7 @@ echo "${_0}: Checking docker swarm is running..."
 ensure_docker_swarm
 echo "${_0}: Checking for lockss user..."
 ensure_lockss_user
+echo "${_0}: Checking for java install..."
+ensure_java
 echo "${_0}: Essential compoments have been sucessfully installed."
 graceful_exit
