Applicable tests are retried. Command line option loop. Cosmetic.

diff --git a/scripts/check-k3s b/scripts/check-k3s
--- a/scripts/check-k3s
+++ b/scripts/check-k3s
@@ -36,8 +36,9 @@
 _0=$(basename "${0}")
 _D0=$(dirname "${0}")
 
-BUSYBOX_VERSION="${BUSYBOX_VERSION:-1.28}"
-
+##
+## Fail function
+##
 Fail()
 {
   echo 'FAIL'
@@ -47,28 +48,131 @@ Fail()
   if [ "${KEEP_GOING}" = 'true' ] ; then
     FAILURES="$(expr "${FAILURES}" + 1)"
   else
+    echo 'STATUS: fail'
     exit 1
   fi 
 }
 
+##
+## Heading function
+##
 Heading()
 {
   printf '  * %s: ' "${1}" 
 }
 
+##
+## Help function
+##
+Help()
+{
+  cat <<MyEOF
+  ${_0} [--keep-going|-keep-going|-k] [--wait=SEC|-wait SEC|-w SEC]
+  ${_0} --help|-help|-h
+
+--help, -help, -h
+    Display this message and exit.
+
+--keep-going, -keep-going, -k
+    Move on to the next test when a test fails.
+
+--retries=N, -retries N, -r N
+    Retry a test that can be retried up to N times (default: ${DEFAULT_RETRIES}).
+
+--wait=SEC, -wait SEC, -w SEC
+    Wait SEC seconds before retrying a test that can be retried (default: ${DEFAULT_WAIT}).
+MyEOF
+}
+
+##
+## Pass function
+##
 Pass()
 {
   echo 'pass'
 }
 
+##
+## Retrying function
+##
 Retrying()
 {
-  printf 'retrying... '
-  sleep $WAIT
+  local count="${1}"
+  if [ "${count}" -lt "${RETRIES}" ] ; then
+    printf 'retrying... '
+    sleep $WAIT
+    return 1
+  else
+    return 0
+  fi
 }
 
+##
+## Definitions
+##
+
+BUSYBOX_VERSION="${BUSYBOX_VERSION:-1.28}"
 FAILURES='0'
-WAIT='10'
+
+KEEP_GOING='false'
+
+DEFAULT_RETRIES='3'
+RETRIES="${DEFAULT_RETRIES}"
+
+DEFAULT_WAIT='10'
+WAIT="${DEFAULT_WAIT}"
+
+##
+## Command line parsing
+##
+
+while true ; do
+  case "${1}" in
+  
+    '')
+      break
+      ;;
+
+    --help|-help|-h)
+      Help
+      exit 0
+      ;;
+    
+    --keep-going|-keep-going|-k)
+      KEEP_GOING=-'true'
+      shift
+      ;;
+
+    --retries=*)
+      RETRIES="${1#*=}"
+      shift
+      ;;
+    -retries|-r)
+      RETRIES="${2}"
+      shift ; shift
+      ;;
+    
+    --wait=*)
+      WAIT="${1#*=}"
+      shift
+      ;;
+    -wait|-w)
+      WAIT="${2}"
+      shift ; shift
+      ;;
+    
+    -*)
+      echo "unknown option: ${1}"
+      exit 1
+      ;;
+
+    *)
+      echo "unexpected argument: ${1}"
+      exit 1
+      ;;
+  
+  esac
+done
 
 K8S_FILE="$(realpath "${_D0}/../config/k8s.cfg")"
 
@@ -93,30 +197,53 @@ Heading 'K3s server is running'
 OUT="$($KUBECTL_CMD version 2>&1)" && Pass || Fail "${OUT}"
 
 Heading 'K3s node is ready'
+ACC=''
+COUNT=1
 until OUT="$($KUBECTL_CMD get node 2>&1 | tail -n +2)" &&
-      echo "${OUT}" | awk '$2 == "Ready" { exit 0 } { exit 1 }' ; do
-  Retrying
-done && Pass
+      echo "${OUT}" | awk '$2 == "Ready" { exit 0 } { exit 1 }' &&
+      Pass ; do
+  ACC="$(printf '%s\n%s' "${ACC}" "${OUT}")"
+  Retrying "${COUNT}" && Fail "${ACC}" && break
+  COUNT="$(expr "${COUNT}" + 1)"
+done
 
 # See https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/#check-if-dns-pods-are-running
 Heading 'CoreDNS pod is running and ready'
-until OUT="$($KUBECTL_CMD -n kube-system get pods -l k8s-app=kube-dns 2>&1 | tail -n +2)" &&
-      echo "${OUT}" | awk '$3 == "Running" && $2 == "1/1" { exit 0 } { exit 1 }' ; do
-  Retrying
-done && Pass
+ACC=''
+COUNT=1
+until OUT="$($KUBECTL_CMD --namespace=kube-system get pods --selector=k8s-app=kube-dns 2>&1 | tail -n +2)" &&
+      echo "${OUT}" | awk '$3 == "Running" && $2 == "1/1" { exit 0 } { exit 1 }' &&
+      Pass ; do
+  ACC="$(printf '%s\n%s' "${ACC}" "${OUT}")"
+  Retrying "${COUNT}" && Fail "${ACC}" && break
+  COUNT="$(expr "${COUNT}" + 1)"
+done
 
 K3S_CLUSTER_IP='10.43.0.10'
 
 # See https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/#check-if-the-dns-service-is-present-with-the-correct-cluster-ip
 Heading 'Kube-DNS is present with the correct cluster IP'
-OUT="$($KUBECTL_CMD -n kube-system get svc -l k8s-app=kube-dns | tail -n +2)" &&
+OUT="$($KUBECTL_CMD --namespace=kube-system get services --selector=k8s-app=kube-dns | tail -n +2)" &&
       [ "$(echo "${OUT}" | awk '$1 == "kube-dns" && $2 == "ClusterIP" { print $3 ; exit 0 } { exit 1 }')" = "${K3S_CLUSTER_IP}" ] &&
       Pass || Fail "${OUT}"
 
 # See https://rancher.com/docs/rancher/v2.x/en/troubleshooting/dns/#check-if-domain-names-are-resolving
 for host in kubernetes.default props.lockss.org ; do
   Heading "${host} resolves correctly"
-  until OUT="$($KUBECTL_CMD run -it --rm --restart=Never "busybox-${RANDOM}" "--image=busybox:${BUSYBOX_VERSION}" -- nslookup "${host}" 2>&1)" ; do
-    Retrying
-  done && Pass
+  ACC=''
+  COUNT=1
+  until OUT="$($KUBECTL_CMD run --quiet --tty --stdin --rm --restart=Never "busybox-${RANDOM}" "--image=busybox:${BUSYBOX_VERSION}" -- /bin/sh -c "nslookup ${host} 2>&1" 2>&1)" &&
+        Pass ; do
+    ACC="$(printf '%s\n%s' "${ACC}" "${OUT}")"
+    Retrying "${COUNT}" && Fail "${ACC}" && break
+    COUNT="$(expr "${COUNT}" + 1)"
+  done
 done
+
+if [ "${FAILURES}" = '0' ] ; then
+  echo 'STATUS: pass'
+  exit 0
+else
+  echo "STATUS: fail (${FAILURES} $([ "${FAILURES}" = '1' ] && echo 'error' || echo 'errors'))"
+  exit 1
+fi
