Add --verbose, --quiet, fix usage, help

diff --git a/scripts/check-kube-routing b/scripts/check-kube-routing
--- a/scripts/check-kube-routing
+++ b/scripts/check-kube-routing
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
 # ---------------------------------------------------------------------------
-# check-sys - Check the host system for all necessary components for running LOCKSS stack.
-#
-# Copyright (c) 2000-2019, Board of Trustees of Leland Stanford Jr. University
+# check-kube-routing - Check that Kubernetes networking/routing is
+# working correctly
+
+# Copyright (c) 2000-2025, Board of Trustees of Leland Stanford Jr. University
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -30,10 +31,15 @@
 # CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 # ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 # POSSIBILITY OF SUCH DAMAGE.
-# Usage: check-port-access [-h|--help]
+# Usage: check-port-access [-v|--verbose] [-q|--quiet] [-h|--help]
 
-# Revision history:
-# ---------------------------------------------------------------------------
+# check-kube-routing - Check that Kubernetes networking/routing is
+# working correctly:
+# - external IP (8.8.8.8) reachable
+# - internal DNS working
+# - src IP of incoming packets to containers preserved (not replaced by
+#   k8s backplane IP)
+
 
 PROGNAME=${0##*/}
 VERSION="1.0"
@@ -57,7 +63,7 @@ NC_HOST_PORT=24601
 clean_up() {
 
 # Perform pre-exit housekeeping
-  logger_info "cleaning up test pod and service..."
+  logger_debug "cleaning up test pod and service..."
   kubectl_cmd delete pod connection-test-pod --grace-period=0 --force -n lockss >/dev/null 2>&1
   kubectl_cmd delete service connection-test-service -n lockss >/dev/null 2>&1
   log_script_exit PROGNAME
@@ -89,19 +95,40 @@ signal_exit() { # Handle trapped signals
   esac
 }
 
+# log info if VERBOSE_LOG, else debug
+log_verbose() {
+  if [[ -n "${VERBOSE_LOG}" ]]; then
+    logger_info "${1}"
+  else
+    logger_debug "${1}"
+  fi
+}
+
+# log info if not QUIET, else debug
+log_not_quiet() {
+  if [[ -z "${QUIET}" ]]; then
+    logger_info "${1}"
+  else
+    logger_debug "${1}"
+  fi
+}
+
 usage() {
-  echo -e "Usage: $PROGNAME [-h|--help]"
+  echo -e "Usage: $PROGNAME [-v|--verbose] [-q|--quiet] [-h|--help]"
+  exit 2
 }
 
 help_message() {
   cat <<-_EOF_
   $PROGNAME ver. $VERSION
-  Run a series of checks on cluster to determine network access.
+  Verifies that Kubernetes networking is working as expected.
 
   $(usage)
 
   Options:
-  -h, --help  Display this help message and exit.
+  -v, --verbose  Report progress and successful tests.
+  -q, --quiet    Be extra quiet
+  -h, --help     Display this help message and exit.
 
 _EOF_
   return
@@ -157,30 +184,30 @@ wait_for_pod() {
 }
 
 run_network_checks() {
-    logger_info "Running network checks..."
+    log_verbose "Running network checks..."
 
-    kubectl_cmd exec -n lockss connection-test-pod -- /bin/sh -c '
+    kubectl_cmd exec -n lockss connection-test-pod -- /bin/sh -c "
       FAILED=0
       if nslookup kubernetes.default.svc.cluster.local >/dev/null 2>&1; then
-        echo "* DNS resolution working"
+        ${VERBOSE_ECHO} \"* DNS resolution OK\"
       else
-        echo "x DNS resolution failed"
+        echo \"* DNS resolution failed\"
         FAILED=1
       fi
       if ping -c 3 8.8.8.8 >/dev/null 2>&1; then
-        echo "* External connectivity working"
+        ${VERBOSE_ECHO} \"* External connectivity OK\"
       else
-        echo "x External connectivity failed"
+        echo \"* External connectivity failed\"
         FAILED=1
       fi
       exit $FAILED
-    ' && return 0 || return 1
+    " && return 0 || return 1
 }
 
 # Function to check IP preservation
 check_ip_preservation() {
     # Test the service with curl
-    logger_info "Checking Client IP Preservation..."
+    log_verbose "Checking source IP Preservation..."
     curl -s "http://${LOCKSS_HOSTNAME}:${NC_HOST_PORT}"
     # Get pod logs
     while IFS= read -r ip; do
@@ -192,9 +219,9 @@ check_ip_preservation() {
     if [ "${#connection_ips[@]}" -gt 0 ]; then
          last_ip="${connection_ips[${#connection_ips[@]}-1]}"
         if [ "${last_ip}" = "${LOCKSS_IPADDR}" ] ; then
-          logger_info "Client IP preservation OK"
+          log_verbose "Source IP preservation OK"
         else
-          error_exit "Client IP preservation check failed."
+          error_exit "Source IP preservation check failed."
         fi
     else
         error_exit "curl unable to reach test pod the pod."
@@ -208,7 +235,36 @@ trap "signal_exit INT"  INT
 logger_init
 log_script_entry "${PROGNAME}"
 
+VERBOSE_LOG=
+QUIET=
+# The command that will be used in the container to echo, or not,
+# progress messages.  Default no-op, set to "echo" if --verbose
+VERBOSE_ECHO=":"
+
+# Parse command-line
+while [[ -n "$1" ]]; do
+  case "$1" in
+  -v | --verbose)
+    VERBOSE_LOG=1
+    VERBOSE_ECHO="echo"
+    ;;
+  -q | --quiet)
+    QUIET=1
+    ;;
+  -h | --help)
+    help_message
+    exit 2
+    ;;
+  *)
+    usage
+    ;;
+  esac
+  shift
+done
+
 Check_Runnable
+
+log_not_quiet "Checking Kubernetes networking"
 
 create_test_pod
 wait_for_pod
