code review changes

diff --git a/scripts/check_sys b/scripts/check_sys
--- a/scripts/check_sys
+++ b/scripts/check_sys
@@ -173,8 +173,8 @@ ensure_docker() {
         sudo usermod -G docker -a lockss
         ;;
       Darwin)
-          err "Docker Mac must be downloaded and installed manually."
-          error_exit "Instructions: https://docs.docker.com/docker-for-mac/install/."
+        err "Docker Mac must be downloaded and installed manually."
+        error_exit "Instructions: https://docs.docker.com/docker-for-mac/install/."
         ;;
       *)
         error_exit "Unsupported system, install docker manually."
@@ -208,9 +208,9 @@ ensure_persistent_plugin() {
           -v $PLUGIN_DATA_PATH:/var/lib/docker/plugin-data/ \
           -v $DATA_VOLUME_PATH:$DATA_VOLUME_PATH \
           cwspear/docker-local-persist-volume-plugin
-          if ! docker volume create -d local-persist -o mountpoint=.config/lptest --name=lptest &>/dev/null; then
-            echo "Attempt to install local persistant plugin failed. See documentation."
-          fi
+        if ! docker volume create -d local-persist -o mountpoint=.config/lptest --name=lptest &>/dev/null; then
+          echo "Attempt to install local persistant plugin failed. See documentation."
+        fi
         ;;
       esac
     else
@@ -224,7 +224,7 @@ ensure_docker_swarm() {
     echo "${_0}: Docker Swarm is not inited"
     ask_for_input "OK to init swarm on this machine?" Y
     if is_yes "${ANS}"; then
-      if ! docker swarm init --advertise-addr $LOCAL_IPADDR; then
+      if ! docker swarm init --advertise-addr ${LOCKSS_IPADDR}; then
         error_exit "attempt install swarm failed."
       fi
     else
@@ -256,23 +256,33 @@ while [[ -n $1 ]]; do
 done
 
 # Main logic
-if ! am_i_root ; then
+if ! am_i_root; then
   error_exit "this script must be run as root."
 fi
 
 case ${OS_TYPE} in
 Linux)
-    LOCAL_IPADDR=$(ifconfig eth0 | grep 'inet addr:' | grep -v 127.0.0.1 | tail -1 | sed 's/.*inet addr:\(.*\)  Mask.*/\1/')
-    ;;
+  LOCAL_IPADDR=$(ifconfig eth0 | grep 'inet addr:' | grep -v 127.0.0.1 | tail -1 | sed 's/.*inet addr:\(.*\)  Mask.*/\1/')
+  ;;
 Darwin)
-    LOCAL_IPADDR=$(ifconfig -a | grep 'inet ' | grep -v 127.0.0.1 | tail -1 | sed 's/.*inet \(.*\) netmask.*/\1/')
-    ;;
+  LOCAL_IPADDR=$(ifconfig -a | grep 'inet ' | grep -v 127.0.0.1 | tail -1 | sed 's/.*inet \(.*\) netmask.*/\1/')
+  ;;
 *)
-    echo "${OS_TYPE} not supported"
-    exit 1
-    ;;
+  echo "${OS_TYPE} not supported"
+  exit 1
+  ;;
 esac
-
+if [ "X${LOCKSS_IPADDR}" = X ]; then
+  LOCKSS_IPADDR=${LOCAL_IPADDR}
+fi
+IP_OK=N
+until is_yes ${IP_OK}; do
+  ask_for_input "IP address of this machine" ${LOCKSS_IPADDR}
+  if valid_ip_address "${ANS}"; then
+    LOCKSS_IPADDR="${ANS}"
+    IP_OK=Y
+  fi
+done
 
 echo "${_0}: Checking for Docker..."
 ensure_docker
