Kubernetes agnostic

diff --git a/scripts/check-sys b/scripts/check-sys
--- a/scripts/check-sys
+++ b/scripts/check-sys
@@ -123,31 +123,27 @@ ensure_lockss_user() {
   esac
 }
 
-ensure_snap() {
-  local instr_link="https://lockss.github.io/administrators/manual/2.0-alpha3/installing/snap"
-  if ! which snap &> /dev/null; then
-      err "${_0}: Snap not found on path."
-      err "${_0}: Snap is used to install microk8s."
-        echo "To complete your install see: ${instr_link}"
+ensure_kubernetes() {
+  local instr_link=""
+  if ! which kubectl &> /dev/null; then
+    err "${_0}: kubectl is not found on the PATH (${PATH})"
+    err "${_0}: LOCKSS requires kubectl to run."
+    echo "checking for k3s install..."
+    if ! which k3s &> /dev/null; then
+      err "${_0}: K3s is not found on the PATH (${PATH})"
+      err "${_0}: LOCKSS uses k3s to install kubernetes."
+      echo "To complete your install see: ${instr_link}"
+    fi
+  elif ! sudo kubectl get node | grep -q "Ready"; then
+    err "${_0}: No available kubernetes node. Please start kubernetes node"
   fi
 }
-ensure_microk8s() {
-  local instr_link="https://lockss.github.io/administrators/manual/2.0-alpha3/installing/microk8s"
-  if ! sudo -i -u $LOCKSS_USER which microk8s &> /dev/null; then
-      err "${_0}: Mircok8s not found on the PATH (${PATH})"
-      err "${_0}: LOCKSS requires Microk8s to run."
-      error_exit "See instructions: ${instr_link}"
-  fi
-}
+
 
 ensure_lockss_access() {
   local instr_link="https://lockss.github.io/administrators/manual/2.0-alpha3/installing/user"
   if ! sudo -l -U lockss sudo &> /dev/null; then
       err "${_0}: The lockss user requires sudo privileges."
-      error_exit "See instructions: ${instr_link}"
-  fi
-  if !  grep '^microk8s:.*$' /etc/group | cut -d: -f4 | grep lockss &> /dev/null; then
-      err "${_0}: The lockss user should be a member of the group 'microk8s'."
       error_exit "See instructions: ${instr_link}"
   fi
 }
@@ -178,12 +174,10 @@ done
 echo "${_0}: Checking for lockss user..."
 ensure_lockss_user
 echo "${_0}: User lockss exists."
-echo "${_0}: Checking snapd install..."
-ensure_snap
-echo "${_0}: snapd is installed."
-echo "${_0}: Checking for microk8s..."
-ensure_microk8s
-echo "${_0}: microk8s is installed."
+echo "${_0}: Checking for kubernetes..."
+ensure_kubernetes
+echo "${_0}: kubernetes is installed and has a active node."
 echo "${_0}: Checking lockss groups and permissions.."
 ensure_lockss_access
+echo "${_0}: The lockss user has appropriate permissions.."
 graceful_exit
