close off the host port for jms clean up quoting

diff --git a/scripts/configure-lockss b/scripts/configure-lockss
--- a/scripts/configure-lockss
+++ b/scripts/configure-lockss
@@ -185,6 +185,56 @@ configure_crawler_services() {
   done
 }
 
+configure_migration() {
+  echo ""
+  echo "Configuring V1 To V2 Migration..."
+  echo ""
+  ask_for_input "Are V1 and V2 running on the same machine?" "" N
+  if is_yes "${ANS}"; then
+    if  [ ! -f /etc/lockss/config.dat ]; then
+      echo "Unable to find V1 configuration file: /etc/lockss/config.dat."
+      echo "Confirm V1 is running on local machine and contact LOCKSS support."
+      exit 1
+    fi
+    # read /etc/lockss/config.dat
+    declare -A props
+    eval `grep -v '^#' $PROPS_FILE | sed -e 's/"/\\"/g;s/\${\([^}]*\)}/${props[\1]}/g;s/^\([^=]*\)=\(.*\)$/props[\1]="\2"/'`
+    # Copy LOCKSS_EXTERNAL_IPADDR, LOCKSS_IPADDR, and LOCKSS_V3_PORT from config.dat to same configure-lockss vars
+    LOCKSS_EXTERNAL_IPADDR=${props[LOCKSS_EXTERNAL_IPADDR]}
+    LOCKSS_IPADDR=${props[LOCKSS_IPADDR]}
+    LOCKSS_V3_PORT=${props[LOCKSS_V3_PORT]}
+    #set LOCKSS_MIGRATE_LCAP_PORT from user input
+    PORT_OK=N
+    until is_yes ${PORT_OK}; do
+      ask_for_input "Port to use for LCAP traffic during migration" "${LOCKSS_MIGRATE_LCAP_PORT}" "9739"
+      if [ "X${ANS}" != "X" ]; then
+        LOCKSS_MIGRATE_LCAP_PORT="${ANS}"
+        PORT_OK=Y
+      fi
+    done
+  else
+   unset LOCKSS_MIGRATE_LCAP_PORT
+   # Set LOCKSS_EXTERNAL_IPADDR and LOCKSS_V3_PORT to V1 LCAP ID
+    EXT_OK=N
+    until is_yes ${EXT_OK}; do
+      ask_for_input "V1 machine IP address or external IP if V1 is behind NAT?" "${LOCKSS_EXTERNAL_IPADDR}"
+      if valid_ip4_address ${ANS}; then
+        LOCKSS_EXTERNAL_IPADDR=${ANS}
+        EXT_OK=Y
+      fi
+    done
+    PORT_OK=N
+    until is_yes ${PORT_OK}; do
+      ask_for_input "V1 machine LCAP port" "${LOCKSS_V3_PORT}" "9729"
+      if [ "X${ANS}" != "X" ]; then
+        LOCKSS_V3_PORT="${ANS}"
+        PORT_OK=Y
+      fi
+    done
+  fi
+  LOCKSS_IN_MIGRATION_MODE=true
+}
+
 configure_services() {
   echo ""
   echo "Configuring LOCKSS services..."
@@ -253,6 +303,7 @@ configure_services() {
   fi
 }
 
+
 # find os release name
 os_release_name() {
   if [ -f /etc/os-release ]; then
@@ -316,6 +367,8 @@ LOCKSS_TIMEZONE="${LOCKSS_TIMEZONE}"
 LOCKSS_CONTAINER_SUBNETS="${LOCKSS_CONTAINER_SUBNETS}"
 LOCKSS_CLASSIC_CRAWLER_ENABLE="${LOCKSS_CLASSIC_CRAWLER_ENABLE}"
 LOCKSS_WGET_CRAWLER_ENABLE="${LOCKSS_WGET_CRAWLER_ENABLE}"
+LOCKSS_MIGRATE_LCAP_PORT="${LOCKSS_MIGRATE_LCAP_PORT}"
+LOCKSS_IN_MIGRATION_MODE="${LOCKSS_IN_MIGRATION_MODE:-false}"
 PREV_CNI0_SUBNET="${CNI0_SUBNET}"
 KUBECTL_CMD="${KUBECTL_CMD}"
 USE_LOCKSS_CFG="${USE_LOCKSS_CFG:-true}"
@@ -382,22 +435,36 @@ build_config_file() {
         echo "Illegal IPv4 address: ${ANS}"
       fi
     done
-    NAT=N
-    if [ "${LOCKSS_EXTERNAL_IPADDR}X" != X ]; then
-      NAT=Y
-    fi
-    ask_for_input "Is this machine behind NAT?" "${NAT}"
-    if is_yes "${ANS}"; then
-      EXT_OK=N
-      until is_yes ${EXT_OK}; do
-        ask_for_input "External IP address for NAT" "${LOCKSS_EXTERNAL_IPADDR}"
-        if valid_ip4_address ${ANS}; then
-          LOCKSS_EXTERNAL_IPADDR=${ANS}
-          EXT_OK=Y
-        fi
-      done
+    if [ -n "$IS_V1_MIGRATION" ]; then
+      configure_migration
     else
-      unset LOCKSS_EXTERNAL_IPADDR
+      # confirm exit from migration mode - abort if
+      if is_yes "${LOCKSS_IN_MIGRATION_MODE}"; then
+        ask_for_input "Do you want to reconfigure V2 to no longer be in migration mode?" "" "Y"
+        if is_yes "${ANS}"; then
+          LOCKSS_IN_MIGRATION_MODE=false
+          unset LOCKSS_MIGRATE_LCAP_PORT
+        else
+          "Rerun scripts/configure-lockss with -m or --migrate"
+        fi
+      fi
+      NAT=N
+      if [ "${LOCKSS_EXTERNAL_IPADDR}X" != X ]; then
+        NAT=Y
+      fi
+      ask_for_input "Is this machine behind NAT?" "${NAT}"
+      if is_yes "${ANS}"; then
+        EXT_OK=N
+        until is_yes ${EXT_OK}; do
+          ask_for_input "External IP address for NAT" "${LOCKSS_EXTERNAL_IPADDR}"
+          if valid_ip4_address ${ANS}; then
+            LOCKSS_EXTERNAL_IPADDR=${ANS}
+            EXT_OK=Y
+          fi
+        done
+      else
+        unset LOCKSS_EXTERNAL_IPADDR
+      fi
     fi
     if [ "X${LOCKSS_ACCESS_SUBNET}" = "X" ]; then
       LOCKSS_ACCESS_SUBNET=$(echo ${LOCKSS_IPADDR} | sed 's/\.[0-9][0-9]*$/.0\/24/')
@@ -441,7 +508,7 @@ build_config_file() {
     done
 
     # LCAP V3 port
-    ask_for_input "LCAP V3 protocol port" "${LOCKSS_V3_PORT}" 9729
+    ask_for_input "LCAP protocol port" "${LOCKSS_V3_PORT}" 9729
     if [ "X${ANS}" != "X" ]; then
       LOCKSS_V3_PORT="${ANS}"
     fi
@@ -650,15 +717,17 @@ setup_k8s_cmd() {
 }
 
 usage() {
-  echo "Usage: configure-lockss [-r|--replay] [-h|--help]"
+  echo "Usage: configure-lockss [-r|--replay] [-m|--migrate] [-h|--help]"
   echo "  --replay  Prompt only for info not already in the config file. Useful when"
   echo "            running configure-lockss after upgrading to a new version of the"
   echo "            LOCKSS services."
+  echo "  --migrate  Set up LOCKSS services for migration from LOCKSS 1.0"
   echo "  --help    Print this text."
   exit 2
 }
 
 is_replay=
+IS_V1_MIGRATION=
 
 # Parse command-line
 while [[ -n "$1" ]]; do
@@ -668,6 +737,9 @@ while [[ -n "$1" ]]; do
     ;;
   -r | --replay)
     is_replay=1
+    ;;
+  -m | --migrate)
+    IS_V1_MIGRATION=1
     ;;
   *)
     usage
@@ -740,6 +812,7 @@ if [ -r "${K8S_CONF_FILE}" ]; then
   read_config ${K8S_CONF_FILE}
 fi
 echo "Checking system state..."
+BYPASS_KUBE_COMMANDS=true
 
 # Sanity checks
 if [ -z "${BYPASS_KUBE_COMMANDS}" ]; then
