Squashed commit of the following:
commit 168be272c48e1a3573449fa5409f7638e542764a
Author: Claire Griffin <clairetg@stanford.edu>
Date:   Fri Apr 5 11:29:27 2024 -0700

Add support for -s start, stop and restart a subset of configured services
Add fix for broken reference to 'latest' in dashboard which requires helm
Add a check for the presence of secrets in check_configured

diff --git a/scripts/deploy-lockss b/scripts/deploy-lockss
--- a/scripts/deploy-lockss
+++ b/scripts/deploy-lockss
@@ -182,11 +182,15 @@ deploy_stack() {
   logger_debug "Deploying services and deployments for stack $stack"
   for svc in "${SERVICES[@]}"; do
     service_name=${SERVICE_NAMES[$svc]}
-    logger_trace "Deploying service ${service_name}..."
-    if ! kubectl_lockss apply -f "${DOCKER_CONFIGS_DIR}/$stack/svcs/${service_name}.yaml" >/dev/null ; then
-      popd &>/dev/null
-      logger_error "An error was found in yaml file ${DOCKER_CONFIGS_DIR}/$stack/svcs/${service_name}.yaml"
-      logger_error_exit "Fix the error then run scripts/restart-lockss."
+    if kubectl_lockss get svs ${service_name} >/dev/null ; then
+      logger_info "${service_name} is already running, use restart_lockss to restart running services."
+    else
+      logger_trace "Deploying service ${service_name}..."
+      if ! kubectl_lockss apply -f "${DOCKER_CONFIGS_DIR}/$stack/svcs/${service_name}.yaml" >/dev/null ; then
+        popd &>/dev/null
+        logger_error "An error was found in yaml file ${DOCKER_CONFIGS_DIR}/$stack/svcs/${service_name}.yaml"
+        logger_error_exit "Fix the error then run scripts/restart-lockss."
+      fi
     fi
   done
   wait_for_ready "${LOCKSS_DATA_DIR}/$stack-pol-data/${LOCKSS_WAIT_FILE}"
@@ -270,5 +274,6 @@ elif [ -e "${DOCKER_CONFIGS_DIR}/${STACK_PREFIX}${STACK_NUM}" ]; then
 else
   logger_error_exit "Unable to find generated stack info for ${STACK_NUM}"
 fi
+
 
 graceful_exit
