Cleanup scripts by adding error checks, missing quotes or improved tests

diff --git a/scripts/deploy-lockss b/scripts/deploy-lockss
--- a/scripts/deploy-lockss
+++ b/scripts/deploy-lockss
@@ -49,7 +49,7 @@ _D0=$(dirname "${0}")
 ## Load _util
 ##
 
-. "${_D0}/_util"
+. "${_D0}/_util" || { echo "${_0}: internal error - failed to load _util" >&2; exit 1; }
 
 ##
 ## Definitions
@@ -161,9 +161,15 @@ wait_for_ready() {
   kubectl_lockss wait --for=condition=Ready --all pods --timeout=180s >/dev/null
   if [ "${CHECK_WAIT_FILE}" = "TRUE" ]; then
     logger_info "Waiting for LOCKSS services to start..."
-    while [ ! -f $wait_for_file ]
-    do
+    local wait_seconds=0
+    local wait_limit=300
+    while [ ! -f "$wait_for_file" ]; do
+      if [ ${wait_seconds} -ge ${wait_limit} ]; then
+        logger_info "LOCKSS services have not started, Ctrl-C to stop waiting."
+        wait_seconds=0
+      fi
       sleep 2
+      wait_seconds=$((wait_seconds + 2))
     done
     logger_info "LOCKSS services are ready; AUs may still be loading."
   else
@@ -215,7 +221,10 @@ logger_init
 log_script_entry "${PROGNAME}"
 umask 002
 
+# set nullglob so STACK_DIRS is a null array instead of string
+shopt -s nullglob
 STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
+shopt -u nullglob
 NUM_STACKS=${#STACK_DIRS[@]}
 STACK_NUM=0
 ARGS_ADDITIONAL=""
diff --git a/scripts/stop-lockss b/scripts/stop-lockss
--- a/scripts/stop-lockss
+++ b/scripts/stop-lockss
@@ -45,7 +45,7 @@ _D0=$(dirname "${0}")
 ## Load _util
 ##
 
-. "${_D0}/_util"
+. "${_D0}/_util" || { echo "${0##*/}: failed to load _util" >&2; exit 1; }
 
 
 declare -a secrets=("lockss-ui-pass" "lockss-auth" "lockss-postgres-pass")
@@ -98,7 +98,7 @@ signal_exit() { # Handle trapped signals
 usage() {
   cat <<- _EOF_
 Usage:
-  
+
   $PROGNAME [-s|--services SVCS]
 
   $PROGNAME [-h|--help]
@@ -128,7 +128,7 @@ undeploy_stack() {
   logger_info "Undeploying stack $stack"
   svc_arr=()
   # if no services req get all running services and stop them.
-  if [ -z $REQ_SERVICES ]; then
+  if [ -z "$REQ_SERVICES" ]; then
     logger_info "Stopping all running services."
     services=$(kubectl_lockss get svc -o jsonpath='{.items[*].metadata.name}')
     IFS=' ' read -a svc_arr <<< "$services"
@@ -150,8 +150,8 @@ undeploy_stack() {
 	do
     podname=$(kubectl_lockss get pod -l lockss-stack-id=${stack} 2> /dev/null | grep "${svc}" )
     logger_debug "Waiting for pod $podname to exit."
-    if [ -n "${podanme}" ]; then
-      kubectl_lockss wait --for=delete -l lockss-stack-id=${stack} pod ${podname} --timeout=60s | logger_debug
+    if [ -n "${podname}" ]; then
+      kubectl_lockss wait --for=delete -l lockss-stack-id=${stack} pod ${podname} --timeout=60s 2>&1 | logger_debug
     fi
   done
 
