Version 3.7 of the Compose file syntax. Clarified error messages.

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -52,7 +52,7 @@ DOCKER_CONFIGS_DIR="${CONFIG_DIR}/configs"
 TEMPLATES_DIR="${CONFIG_DIR}/templates"
 
 # Files
-DOCKER_COMPOSE_FILE="${COMPOSE_DIR}/docker-compose.yaml"
+DOCKER_COMPOSE_FILE="${COMPOSE_DIR}/docker-compose.yml"
 ENV_FILE="${CONFIG_DIR}/env.sh"
 EMPTY_LOCKSS_TXT="${TEMPLATES_DIR}/blank_lockss.txt"
 EMPTY_LOCKSS_OPT="${TEMPLATES_DIR}/blank_lockss.opt"
@@ -95,7 +95,7 @@ fi
 docker secret rm postgres_pass
 echo "creating docker secret for postgres password..."
 if ! docker secret create postgres_pass "${CONFIG_DIR}/postgres.sec" ; then
-  echo "${_0}: error creating postgres_pass"
+  echo "${_0}: error creating secret postgres_pass"
   exit 1
 fi
 
@@ -105,7 +105,7 @@ do
   docker config rm ${gconf}
   echo "creating docker config for global conf ${gconf}..."
   if ! docker config create --template-driver golang ${gconf} $(Config_Or_Blank ${gconf}) ; then
-    echo "${_0}: error creating ${gconf}"
+    echo "${_0}: error creating config ${gconf}"
     exit 1
   fi
 done
@@ -117,11 +117,11 @@ do
   echo "creating docker config for conf ${sconf}..."
   docker config rm ${sconf}_service ${sconf}_service_opt
   if ! docker config create --template-driver golang ${sconf}_service $(Config_Or_Blank ${sconf}_service) ; then
-    echo "${_0}: error creating ${sconf}_service"
+    echo "${_0}: error creating config ${sconf}_service"
     exit 1
   fi
   if ! docker config create --template-driver golang ${sconf}_service_opt $(Config_Or_Blank ${sconf}_service_opt) ; then
-    echo "${_0}: error creating ${sconf}_service_opt"
+    echo "${_0}: error creating config ${sconf}_service_opt"
     exit 1
   fi
 done
@@ -130,8 +130,14 @@ done
 for svc in "${svcs[@]}"
 do
   echo "creating docker data and log volumes for ${svc}..."
-  docker volume create -d local-persist -o mountpoint=${LOCKSS_DATA_DIR}/lockss-${svc}-data --name=lockss-${svc}-data
-  docker volume create -d local-persist -o mountpoint=${LOCKSS_LOGS_DIR}/lockss-${svc}-logs --name=lockss-${svc}-logs
+  if ! docker volume create -d local-persist -o mountpoint=${LOCKSS_DATA_DIR}/lockss-${svc}-data --name=lockss-${svc}-data ; then
+    echo "${_0}: error creating volume lockss-${svc}-data"
+    exit 1
+  fi
+  if ! docker volume create -d local-persist -o mountpoint=${LOCKSS_LOGS_DIR}/lockss-${svc}-logs --name=lockss-${svc}-logs ; then
+    echo "${_0}: error creating volume lockss-${svc}-logs"
+    exit 1
+  fi
 done
 
 docker stack deploy --compose-file ${DOCKER_COMPOSE_FILE} lockss-stack
