More explicit output. Cosmetic.

diff --git a/scripts/install-k3s b/scripts/install-k3s
--- a/scripts/install-k3s
+++ b/scripts/install-k3s
@@ -198,65 +198,111 @@ EOF
   fi
 }
 
-Adjust_Iptables()
+Configure_Iptables()
 {
+  echo "${PROGNAME}: Configuring iptables..."
   # Return if iptables is not on the PATH
-  command -v iptables > /dev/null || return 0
+  if ! command -v iptables > /dev/null ; then
+    echo 'iptables is not installed; no change needed'
+    return 0
+  fi
   # Get the iptables version
-  local line="$(iptables --version)"
-  local ver="$(echo "${line}" | awk '{print $2;exit 0}' | tail -c +2)"
+  # Examples of iptables --version:
+  #   iptables v1.8.7 (legacy)
+  #   iptables v1.8.7 (nf_tables)
+  #   iptables v1.4.21
+  local line
+  line="$(iptables --version)" || return 1
+  local ver
+  ver="$(echo "${line}" | awk '{print $2;exit 0}' | tail -c +2)" || return 1
   # Return if the version is not 1.8.0 or later
-  [ "$(echo "${ver}" | awk -F. '{print $1;exit 0}')" -ge 1 ] || return 0
-  [ "$(echo "${ver}" | awk -F. '{print $2;exit 0}')" -ge 8 ] || return 0
+  if [ "$(echo "${ver}" | awk -F. '{print $1;exit 0}')" -lt 1 ] || [ "$(echo "${ver}" | awk -F. '{print $2;exit 0}')" -lt 8 ] ; then
+    echo 'iptables is not version 1.8.0 or later; no change needed'
+    return 0
+  fi
   # Return if the mode is not nf_tables
-  [ "$(echo "${line}" | awk '{print $3;exit 0}' | tr -d '()')" = 'nf_tables' ] || return 0
+  if [ "$(echo "${line}" | awk '{print $3;exit 0}' | tr -d '()')" != 'nf_tables' ] ; then
+    echo 'iptables is not in nf_tables mode; no change needed'
+    return 0
+  fi
   # Return if update-alternatives is not on the PATH
-  command -v update-alternatives  > /dev/null || return 0
-  # Return if there are no symlinks matching /etc/alternatives/ip*tables*
-  local alts="$(readlink /etc/alternatives/ip*tables*)" || return 0
-  [ -n "${alts}" ] || return 0
-  # Return if the first symlink is not executable or its mode is not nf_tables
-  for alt in $alts ; do
-    [ -x "${alt}" ] || return 0
-    [ "$($alt --version | awk '{print $3;exit 0}' | tr -d '()')" = 'nf_tables' ] || return 0
+  if ! command -v update-alternatives > /dev/null ; then
+    echo 'iptables is not managed via alternatives; no change needed'
+    return 0
+  fi
+  # Return if the first /etc/alternatives/ip*tables* is not a symlink or not in nf_tables mode
+  for alt in /etc/alternatives/ip*tables* ; do
+    if [ ! -h "${alt}" ] ; then
+      echo 'iptables is not managed via alternatives; no change needed'
+      return 0
+    fi
+    if [ "$($alt --version | awk '{print $3;exit 0}' | tr -d '()')" != 'nf_tables' ] ; then
+      echo 'iptables managed via alternatives is not in nf_tables mode; no change needed'
+      return 0
+    fi
     break
   done
   # Ask for permission
   echo
-  echo "Your system is running iptables version 1.8.0 or later,"
-  echo "in nf_tables mode, via the alternatives system. For K3s"
-  echo "to work properly, it is necessary to switch iptables to"
-  echo "legacy mode via the alternatives system."
+  echo 'Your system is running iptables version 1.8.0 or later, in nf_tables'
+  echo 'mode, via alternatives. For K3s to work properly, it is necessary to'
+  echo 'switch iptables to legacy mode via alternatives. This script can do it'
+  echo 'for you. If you opt out, the script will continue but K3s is likely to'
+  echo 'malfunction without external intervention; see the manual for details.'
   echo
-  ask_for_input "Switch iptables to legacy mode via the alternatives system?" Y
+  if [ "${ASSUME_YES}" = 'true' ] ; then
+    echo "${PROGNAME} in automatic 'yes' mode"
+    ANS=Y
+  else
+    ask_for_input 'Switch iptables to legacy mode via alternatives?' Y
+  fi
   if ! is_yes "${ANS}" ; then
-    echo "Leaving iptables unchanged."
+    echo 'Leaving iptables unchanged; see manual for details.'
     return 0
   fi
-  # Perform change
-  echo "Switching iptables to legacy mode via the alternatives system..."  
+  # Perform change; see https://github.com/k3s-io/k3s/issues/116#issuecomment-624770403
+  echo "Switching iptables to legacy mode via alternatives..."
+  # iptables-legacy and ip6tables-legacy are mandatory, return 1 if it fails
   $SUDO update-alternatives --set iptables /usr/sbin/iptables-legacy || return 1
   $SUDO update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || return 1
+  # arptables-legacy and ebtables-legacy are optional, don't return if it fails
+  $SUDO update-alternatives --set arptables /usr/sbin/arptables-legacy
+  $SUDO update-alternatives --set ebtables /usr/sbin/ebtables-legacy
+  # Reload iptables
   $SUDO iptables --flush || return 1
-  echo "Done."
+  echo 'Done.'
   return 0
 }
 
-Adjust_Firewalld()
+Configure_Firewalld()
 {
+  echo "${PROGNAME}: Configuring firewalld..."
   # Return if firewall-cmd is not on the PATH
-  command -v firewall-cmd > /dev/null || return 0
+  if ! command -v firewall-cmd > /dev/null ; then
+    echo 'firewalld is not installed; no change needed'
+    return 0
+  fi
   # Return if firewalld is not running
-  [ "$($SUDO firewall-cmd --state 2>&1)" = 'running' ] || return 0
+  if [ "$($SUDO firewall-cmd --state 2>&1)" != 'running' ] ; then
+    echo 'firewalld is not running; no change needed'
+    return 0
+  fi
   # Ask for permission
   echo
-  echo "Your system is running firewalld. For K3s to work properly,"
-  echo "it is necessary to add 10.42.0.0/16 and 10.43.0.0/16 to"
-  echo "firewalld's trusted zone."
+  echo 'Your system is running firewalld. For K3s to work properly, it is'
+  echo "necessary to add 10.42.0.0/16 and 10.43.0.0/16 to firewalld's trusted"
+  echo 'zone. This script can do it for you. If you opt out, the script will'
+  echo 'continue but K3s is likely to malfunction without external intervention;'
+  echo 'see the manual for details.'
   echo
-  ask_for_input "Add 10.42.0.0/16 and 10.43.0.0/16 to firewalld's trusted zone?" Y
+  if [ "${ASSUME_YES}" = 'true' ] ; then
+    echo "${PROGNAME} in automatic 'yes' mode"
+    ANS=Y
+  else
+    ask_for_input "Add 10.42.0.0/16 and 10.43.0.0/16 to firewalld's trusted zone?" Y
+  fi
   if ! is_yes "${ANS}" ; then
-    echo "Leaving firewalld unchanged."
+    echo 'Leaving firewalld unchanged; see manual for details.'
     return 0
   fi
   # Perform change
@@ -264,39 +310,56 @@ Adjust_Firewalld()
   $SUDO firewall-cmd --permanent --zone=trusted --add-source=10.42.0.0/16 || return 1
   $SUDO firewall-cmd --permanent --zone=trusted --add-source=10.43.0.0/16 || return 1
   $SUDO firewall-cmd --reload || return 1  
-  echo "Done."
+  echo 'Done.'
   return 0
 }
 
-Adjust_Ufw()
+Configure_Ufw()
 {
   # Return if ufw is not on the PATH
-  command -v ufw > /dev/null || return 0
+  if ! command -v ufw > /dev/null ; then
+    echo 'ufw is not installed; no change needed'
+    return 0
+  fi
   # Return if ufw is not active
-  [ "$($SUDO ufw status | grep -m 1 '^Status:')" = 'Status: active' ] || return 0
+  if [ "$($SUDO ufw status | grep -m 1 '^Status:')" != 'Status: active' ] ; then
+    echo 'ufw is not active; no change needed'
+    return 0
+  fi
   # Ask for permission
   echo
-  echo "Your system is running ufw. For K3s to work properly,"
-  echo "it is necessary to allow traffic from 10.42.0.0/16 and"
-  echo "10.43.0.0/16 via ufw."
+  echo 'Your system is running ufw. For K3s to work properly, it is necessary to'
+  echo 'allow traffic from 10.42.0.0/16 and 10.43.0.0/16 via ufw. This script'
+  echo 'can do it for you. If you opt out, the script will continue but K3s is'
+  echo 'likely to malfunction without external intervention; see the manual for'
+  echo 'details.'
   echo
-  ask_for_input "Allow traffic from 10.42.0.0/16 and 10.43.0.0/16 via ufw?" Y
+  if [ "${ASSUME_YES}" = 'true' ] ; then
+    echo "${PROGNAME} in automatic 'yes' mode"
+    ANS=Y
+  else
+    ask_for_input 'Allow traffic from 10.42.0.0/16 and 10.43.0.0/16 via ufw?' Y
+  fi
   if ! is_yes "${ANS}" ; then
-    echo "Leaving ufw unchanged."
+    echo 'Leaving ufw unchanged; see manual for details.'
     return 0
   fi
   # Perform change
-  echo "Allowing traffic from 10.42.0.0/16 and 10.43.0.0/16 via ufw..."  
+  echo 'Allowing traffic from 10.42.0.0/16 and 10.43.0.0/16 via ufw...'  
   $SUDO ufw allow from 10.42.0.0/16 to any || return 1
   $SUDO ufw allow from 10.43.0.0/16 to any || return 1
   $SUDO ufw reload || return 1  
-  echo "Done."
+  echo 'Done.'
   return 0
 }
 
 ##
 ## MAIN
 ##
+
+# Intentional '-' not ':-': use ASSUME_YES (if set to anything including null),
+# else default to 'false' (if unset).
+ASSUME_YES="${ASSUME_YES-false}"
 
 # Trap signals
 trap "signal_exit TERM" TERM HUP
@@ -311,7 +374,10 @@ while [[ -n $1 ]]; do
     help_message
     graceful_exit
     ;;
-  -* | --*)
+  -y|--assume-yes)
+    ASSUME_YES='true'
+    ;;
+  -*)
     usage
     error_exit "Unknown option $1"
     ;;
@@ -328,20 +394,17 @@ if [ $(id -u) -eq 0 ]; then
     SUDO=
 fi
 
-echo "${PROGNAME}: Adjusting iptables if needed..."
-Adjust_Iptables || error_exit "Attempt to adjust iptables failed."
+Configure_Iptables || error_exit "Attempt to configure iptables failed."
 
-echo "${PROGNAME}: Adjusting firewalld if needed..."
-Adjust_Firewalld || error_exit "Attempt to adjust firewalld failed."
+Configure_Firewalld || error_exit "Attempt to configure firewalld failed."
 
-echo "${PROGNAME}: Adjusting ufw if needed..."
-Adjust_Ufw || error_exit "Attempt to adjust ufw failed."
+Configure_Ufw || error_exit "Attempt to configure ufw failed."
 
-echo "${PROGNAME}: Setting resolv.conf for container dns usage..."
-configure_resolv_conf || error_exit "Unable obtain valid resolv.conf information."
+echo "${PROGNAME}: Setting resolv.conf for container DNS resolution..."
+configure_resolv_conf || error_exit "Unable to obtain valid resolv.conf information."
 
-echo "${PROGNAME}: Installing k3s kubernetes..."
-install_k3s || error_exit "Attempt to install k3s failed."
+echo "${PROGNAME}: Installing K3s..."
+install_k3s || error_exit "Attempt to install K3s failed."
 
 echo "${PROGNAME}: Writing configuration file..."
-write_config ${K8S_CONF_FILE}|| error_exit "Attempt to write ${K8S_CONF_FILE} failed."
+write_config ${K8S_CONF_FILE} || error_exit "Attempt to write ${K8S_CONF_FILE} failed."
