Mirror the k3s install paths for location of k3s install Add it as a util function. Remove system check.

diff --git a/scripts/install-k3s b/scripts/install-k3s
--- a/scripts/install-k3s
+++ b/scripts/install-k3s
@@ -176,20 +176,25 @@ check_k3s() {
   fi
 }
 
+
 write_config() {
-  get_k3s_bin_dir
+  set_k3s_bin_dir
 
   cat >"${1}" <<EOF
 K8S_FLAVOR="k3s"
 K8S_VERSION="${K8S_VERSION}"
-K8S_CHANNEL="${K8S_CHANNEL}"
 K3S_VERSION="${K3S_VERSION}"
-KUBECTL_CMD="$(command -v k3s) kubectl"
-RESOLVE_CONF_CONFIG="${RESOLVE_CONF_CONFIG}"
+KUBECTL_CMD="${BIN_DIR}/kubectl"
+RESOLV_CONF_CONFIG="${RESOLV_CONF_CONFIG}"
 EOF
-  if [ $(id -u) -eq 0 ]; then
-    chown lockss:lockss "${1}" ||
-    echo "The file ${CONFIG_DIR}/k8s.cfg is not owned by lockss. Please create lockss user and group and chown it to lockss."
+  # we are hard coding the assumption that the only name for LOCKSS_USER is "lockss"
+  lockss_uid=$(id -u lockss)
+  lockss_gid=$(id -g lockss)
+
+  if [ $(id -u) -ne ${lockss_uid} ]; then
+    chown lockss_uid:lockss_gid "${1}" ||
+    echo "The file ${CONFIG_DIR}/k8s.cfg is not owned by lockss."
+    echo "Please create lockss user and group and chown the file to lockss before running configure-lockss."
   fi
 }
 
@@ -227,8 +232,8 @@ echo "${PROGNAME}: Setting resolv.conf for container dns usage..."
 configure_resolv_conf || error_exit "Unable obtain valid resolv.conf information."
 echo "${PROGNAME}: Installing k3s kubernetes..."
 install_k3s || error_exit "Attempt to install k3s failed."
-echo "${PROGNAME}: Running k3s system check..."
-check_k3s || error_exit "System check failed run 'SUDO k3s check_config' for details."
+#echo "${PROGNAME}: Running k3s system check..."
+#check_k3s || error_exit "System check failed run 'SUDO k3s check_config' for details."
 echo "${PROGNAME}: Writing configurgation file..."
 write_config ${K8S_CONF_FILE}|| error_exit "Attempt to write ${K8S_CONF_FILE} failed."
 
