add password directly to secure store

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -114,7 +114,6 @@ do
   fi
 done
 
-# Create the secret for the
 # Create the configs for each lockss service
 for sconf in "${service_confs[@]}"
 do
@@ -147,6 +146,9 @@ done
 # Create a lockss network
 echo "Creating lockss network"
 docker network remove lockss-network
-docker network create -d overlay --opt encrypted --attachable lockss-network
+if ! docker network create -d overlay --opt encrypted --attachable lockss-network; then
+  echo "lockss-network: error creating network."
+  exit 1
+fi
 
-echo "Successfully installed Docker secrets, configs and volumes and network."
+echo "Successfully installed Docker Secrets, Configs and Volumes and Networks."
