Error handling for ctrl-c exit from hung scripts.

diff --git a/scripts/update-alpha1-to-alpha2 b/scripts/update-alpha1-to-alpha2
--- a/scripts/update-alpha1-to-alpha2
+++ b/scripts/update-alpha1-to-alpha2
@@ -68,6 +68,52 @@ OLD_SYSTEM_CONF_FILE="${CONFIG_DIR}/config.info"
 SQL_FILE="${UPDATES_PATH}/alpha1-to-alpha2-db-rename.sql"
 SQL_PASS_FILE="/run/secrets/lockss-postgres-pass"
 
+clean_up() { # Perform pre-exit housekeeping
+	return
+}
+
+error_exit() {
+	echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
+	clean_up
+	exit 1
+}
+
+graceful_exit() {
+	clean_up
+	exit
+}
+
+signal_exit() { # Handle trapped signals
+	case $1 in
+		INT)
+			error_exit "Program interrupted by user" ;;
+		TERM)
+			echo -e "\n$PROGNAME: Program terminated" >&2
+			graceful_exit ;;
+		*)
+			error_exit "$PROGNAME: Terminating on unknown signal" ;;
+	esac
+}
+
+usage() {
+	echo -e "Usage: $PROGNAME [-h|--help] [-a|--args ARGS_ADDITIONAL]"
+}
+
+help_message() {
+  cat <<- _EOF_
+  $PROGNAME ver. $VERSION
+  "Update an alpha1 version to an alpha2 version."
+
+  $(usage)
+
+  Options:
+  -h, --help  Display this help message and exit.
+
+_EOF_
+  return
+}
+
+
 rename_dirs() {
   msg "${PROGNAME}: Looking for old data directories..."
   if [ -d "${LOCKSS_DATA_DIR}/lockss-stack1-cfg-data" ]; then
@@ -151,6 +197,13 @@ USE_LOCKSS_OPENWB="${USE_LOCKSS_OPENWB:-false}"
 EOF
 }
 
+###
+# Start
+###
+# Trap signals
+trap "signal_exit TERM" TERM HUP
+trap "signal_exit INT"  INT
+
 # MAIN ENTRY POINT
 # Sanity checks
 msg "${PROGNAME}: Checking system..."
@@ -206,3 +259,5 @@ msg "${PROGNAME}: Checking solr indices for update..."
 echo "  ---------------------------  "
 msg "${PROGNAME}: Update complete."
 msg "${PROGNAME}: Call configure-lockss to check configuration settings."
+
+graceful_exit
