err_msg doesn't exist s/b err_exit or err.

diff --git a/scripts/upgrade-alpha1-to-alpha2 b/scripts/upgrade-alpha1-to-alpha2
--- a/scripts/upgrade-alpha1-to-alpha2
+++ b/scripts/upgrade-alpha1-to-alpha2
@@ -234,7 +234,7 @@ rename_dirs
 
 echo "  ---------------------------  "
 msg "${PROGNAME}: checking for postgres changes..."
-update_sql || err_msg "Attempt to update sql failed."
+update_sql || err "Attempt to update sql failed."
 
 echo "  ---------------------------  "
 msg "${PROGNAME}: Uninstalling all lockss docker elements"
@@ -243,7 +243,7 @@ msg "${PROGNAME}: Uninstalling all lockss docker elements"
 
 echo "  ---------------------------  "
 msg "${PROGNAME}: Checking solr indices for update..."
-"${SCRIPTS_DIR}/upgrade-alpha1-solr" || err_msg "Your solr instance needs to be checked."
+"${SCRIPTS_DIR}/upgrade-alpha1-solr" || err_exit "Your solr instance needs to be checked."
 
 echo "  ---------------------------  "
 msg "${PROGNAME}: Update complete."
