use console for logging
place existence checks before attempting to check ownership and write permssions.

eliminate fix_directory_permissions allowing a single loop through directories

diff --git a/scripts/upgrades/fix-permissions b/scripts/upgrades/fix-permissions
--- a/scripts/upgrades/fix-permissions
+++ b/scripts/upgrades/fix-permissions
@@ -62,11 +62,11 @@ set -a
 set +a
 
 clean_up() { # Perform pre-exit housekeeping
-  log_script_exit  "${PROGNAME}"
+  return
 }
 
 error_exit() {
-  logger_fatal "${1:-"Unknown Error"}" >&2
+  echo -e "${PROGNAME}: ${1:-"Unknown Error"}" >&2
   clean_up
   exit 1
 }
@@ -79,14 +79,14 @@ graceful_exit() {
 signal_exit() { # Handle trapped signals
   case $1 in
   INT)
-    logger_info "Program interrupted by user"
+    error_exit "Program interrupted by user"
     ;;
   TERM)
-    logger_error "Program terminated"
+    echo -e "\n$PROGNAME: Program terminated" >&2
     graceful_exit
     ;;
   *)
-    error_exit "Terminating on unknown signal"
+    error_exit "$PROGNAME: Terminating on unknown signal"
     ;;
   esac
 }
@@ -154,7 +154,7 @@ ensure_writable_dir() {
   local user=$(stat -c '%u' ${dir})
   local group=$(stat -c '%g' ${dir})
   if [ "${user}" != "$(id -u $LOCKSS_USER)" ]; then
-    logger_warn "${dir} is not writable by $LOCKSS_USER; attempting to chown it."
+    echo "${dir} is not writable by $LOCKSS_USER; attempting to chown it."
     sudo chown -R ${LOCKSS_UID}:${LOCKSS_GID} "${dir}" || error_exit "Unable to chown ${dir}"
   fi
 }
@@ -168,31 +168,35 @@ ensure_lockss_owner() {
 
   for svc in "${lockss_owned[@]}"; do
     data_dir=${LOCKSS_DATA_DIR}/$stack-${svc}-data
-    sudo find "${data_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {} | logger_debug
+    if [ -n "${data_dir}" ]; then
+      sudo find "${data_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {} >/dev/null
+      sudo chmod 750 "${data_dir}" >/dev/null
+    fi
     logs_dir=${LOCKSS_LOGS_DIR}/$stack-${svc}-logs
-    sudo find "${logs_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {} | logger_debug
+    if [ -n "${logs_dir}" ]; then
+      sudo find "${logs_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {} >/dev/null
+      sudo chmod 750 "${logs_dir}" >/dev/null
+    fi
     tmp_dir=${LOCKSS_TMPDIR}/$stack-${svc}-tmp
-    sudo find "${tmp_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {} | logger_debug
+    if [ -n "${tmp_dir}" ]; then
+      sudo find "${tmp_dir}" \! -user ${LOCKSS_UID} | xargs -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {} >/dev/null
+      sudo chmod 1777 "${tmp_dir}" >/dev/null
+    fi
     IFS=';' read -r -a datadirs <<<"${LOCKSS_REPO_HOST_DIRS}"
     len=${#datadirs[@]}
     start=1
     for ((cnt = $start; cnt < $len; cnt++)); do
       data_dir="${datadirs[$cnt]}/$stack-repo-data"
-      sudo find "${data_dir}" \! -user ${LOCKSS_UID} | xargs -0 -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {} | logger_debug
+      if [ -n "${data_dir}" ]; then
+        sudo find "${data_dir}" \! -user ${LOCKSS_UID} | xargs -0 -I{} -P3 -- sudo chown ${LOCKSS_UID}:${LOCKSS_GID} {} >/dev/null
+        sudo chmod 750 "${data_dir}" >/dev/null
+      fi
     done
   done
+  # Make sure that postgres can write to the lockss logs directory
+  sudo chmod 777 "${LOCKSS_LOGS_DIR}/$stack-postgres-logs" >/dev/null
 }
 
-fix_directory_permissions() {
-  local stack=${STACK_PREFIX}$1
-  for svc in "${lockss_owned[@]}"; do
-    sudo chmod 750  "${LOCKSS_DATA_DIR}/$stack-${svc}-data"
-    sudo chmod 750  "${LOCKSS_LOGS_DIR}/$stack-${svc}-logs"
-    sudo chmod 1777 "${LOCKSS_TMPDIR}/$stack-${svc}-tmp"
-  done
-  # fix ownership of the lockss postgres directory
-  sudo chmod 777 "${LOCKSS_LOGS_DIR}/$stack-postgres-logs"
-}
 
 ##
 ## MAIN
@@ -203,7 +207,8 @@ trap "signal_exit INT" INT
 # Source system config file
 
 if [ ! -r "$SYSTEM_CONF_FILE" ]; then
-  err_exit "$_0: The system configuration file does not exist.  Run scripts/configure-lockss."
+  err "$_0: The system configuration file does not exist.  This script requires the ./config/system.cfg file."
+  err_exit "$_0: Run scripts/configure-lockss first."
 fi
 
 # Parse command-line
@@ -215,15 +220,12 @@ while [[ $# -gt 0 ]]; do
       usage
       error_exit "Unknown option $1" ;;
     *)
-      logger_trace "Argument $1 to process..."
       shift
       ;;
   esac
 done
 
 #init the logger and mark script entry
-logger_init
-log_script_entry "${PROGNAME}"
 umask 002
 
 STACK_DIRS=(${DOCKER_CONFIGS_DIR}/*/)
@@ -232,27 +234,31 @@ STACK_NUM=0
 
 init_service_arrays
 
-logger_info "Checking for lockss directories found in system.cfg."
-ensure_writable_dir $LOCKSS_DATA_DIR ||
-  error_exit "Unable to write $LOCKSS_DATA_DIR"
-ensure_writable_dir $LOCKSS_LOGS_DIR ||
-  error_exit "Unable to write $LOCKSS_LOGS_DIR"
-ensure_writable_dir $LOCKSS_TMPDIR ||
-  error_exit "Unable to write $LOCKSS_TMPDIR"
-ensure_writable_dir $LOCKSS_SCRIPT_LOG_DIR ||
-  error_exit "Unable to write $LOCKSS_SCRIPT_LOG_DIR"
-
-logger_info "Checking for lockss stack info found in config/configs..."
+echo "Checking for lockss directories found in system.cfg."
+if [ -n "$LOCKSS_DATA_DIR" ]; then
+  ensure_writable_dir $LOCKSS_DATA_DIR ||
+    error_exit "Unable to write $LOCKSS_DATA_DIR"
+fi
+if [ -n "$LOCKSS_LOGS_DIR" ]; then
+  ensure_writable_dir $LOCKSS_LOGS_DIR ||
+    error_exit "Unable to write $LOCKSS_LOGS_DIR"
+fi
+if [ -n "$LOCKSS_TMPDIR" ]; then
+  ensure_writable_dir $LOCKSS_TMPDIR ||
+    error_exit "Unable to write $LOCKSS_TMPDIR"
+fi
+if [ -n "$LOCKSS_SCRIPT_LOG_DIR" ]; then
+  ensure_writable_dir $LOCKSS_SCRIPT_LOG_DIR ||
+    error_exit "Unable to write $LOCKSS_SCRIPT_LOG_DIR"
+fi
+echo "Checking for lockss stack info found in config/configs..."
 if [ "${NUM_STACKS}" -le 1 ]; then
   ensure_lockss_owner ""
-  fix_directory_permissions ""
 else
-  logger_info "Checking ${NUM_STACKS} stacks."
+  echo "Checking ${NUM_STACKS} stacks."
   ensure_lockss_owner ""
-  fix_directory_permissions ""
   for ((num = 1; num < $NUM_STACKS; num++)); do
     ensure_lockss_owner $num
-    fix_directory_permissions $num
   done
 fi
 
