Add check for upgrading flag to start-lockss and restart-lockss. Add postgresql conf file Add wait for ready check for postgres start.

diff --git a/scripts/upgrades/upgrade-postgres b/scripts/upgrades/upgrade-postgres
--- a/scripts/upgrades/upgrade-postgres
+++ b/scripts/upgrades/upgrade-postgres
@@ -59,6 +59,7 @@ SYSTEM_CONF_FILE="${CONFIG_DIR}/system.cfg"
 source_config
 STACK_PREFIX="lockss-stack"
 POSTGRES_DATA_DIR="${LOCKSS_DATA_DIR}/${STACK_PREFIX}-postgres-data"
+POSTGRES_TMP_DIR="${LOCKSS_DATA_DIR}/${STACK_PREFIX}-postgres-tmp"
 
 clean_up() { # Perform pre-exit housekeeping
   restore_env
@@ -168,19 +169,46 @@ version_compare()
     return 0
 }
 
+	check_pg_ready()
+	{
+
+		for i in {1..10}
+		do
+  		 kubectl_lockss exec ${PODNAME} -- pg_isready -U LOCKSS
+  			case $? in
+    		0)
+      		logger_info "PostgreSQL is ready for sql commands."
+      		return 0
+      		;;
+    		1 | 2)
+      		logger_trace "PostgreSQl is not responding or is starting up."
+      		;;
+   	 		3)
+      		logger_error_exit "Unable to connect to PostgreSQL container - Invalid arguments."
+      		;;
+      esac
+      sleep 30
+  	done
+  	return 1
+	}
+
 dump_old_version()
 {
   # add the postgres version to the opt file
   echo POSTGRES_VERSION=${OLD_VERSION} | tee "${UPGRADE_ENV_TMPL}"
 
   # bring up the old version
-  "${SCRIPTS_DIR}"/start-lockss -s "postgres" || logger_error_exit "Attempt to start old PostgreSQL failed."
-  podname="deploy/lockss-postgres-service"
+	  "${SCRIPTS_DIR}"/start-lockss -U -s "postgres" || logger_error_exit "Attempt to start old PostgreSQL failed."
+
   #wait for the  deployment to be marked as Available
   kubectl_lockss wait deployment lockss-postgres-service --for condition=Available=True --timeout=180s
+	  # get the pod name
+	  PODNAME=$(kubectl get pods -n lockss --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
+		# check that the postgres is ready for sql commands
+	  check_pg_ready  ||  logger_error_exit "Timed out waiting for PostgreSQL to allow sql commands."
   # dump the old versions content
-  kubectl_lockss exec ${podname} -- pg_dumpall -U "${LOCKSS_POSTGRES_USER}" -c --if-exists --file="/tmp/${DUMP_FILE}" ||
-    logger_error_exit "Unable to exec into pod to perform database dump."
+	  kubectl_lockss exec ${PODNAME} -- pg_dumpall -U ${LOCKSS_POSTGRES_USER} -c --if-exists --file="${DUMP_FILE}" ||
+	  	logger_error_exit "Unable to perform database dump."
   # shutdown old version
   "${SCRIPTS_DIR}"/stop-lockss  || logger_error_exit "Attempt to stop PostgreSQL failed."
 
@@ -195,15 +223,20 @@ dump_old_version()
 
 restore_dump()
 {
-# bring up the new version -- psql -q -U
- "${SCRIPTS_DIR}"/start-lockss -s "postgres" || logger_error_exit "Attempt to start new PostgreSQL failed."
+	  echo POSTGRES_VERSION=${NEW_VERSION} | tee "${UPGRADE_ENV_TMPL}"
+		# bring up the new version
+	 	"${SCRIPTS_DIR}"/start-lockss -U -s "postgres" || logger_error_exit "Attempt to start new PostgreSQL failed."
  kubectl_lockss wait deployment lockss-postgres-service --for condition=Available=True --timeout=180s
- sleep 15
- # load the dump into the new version
- kubectl_lockss exec -it deploy/lockss-postgres-service -- psql -q -U "${LOCKSS_POSTGRES_USER}" --file="/tmp/${DUMP_FILE}" --dbname=postgres >/dev/null ||
+	  PODNAME=$(kubectl get pods -n lockss --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
+		# check that the postgres is ready for sql commands
+	  check_pg_ready  ||  logger_error_exit "Timed out waiting for PostgreSQL to allow sql commands."
+	 	# load the dump into the new version psql -q -U
+	 	kubectl_lockss exec ${PODNAME} -- psql -q -U "${LOCKSS_POSTGRES_USER}" --file="${DUMP_FILE}" --dbname=postgres >/dev/null ||
    logger_error_exit "Unable to exec into pod to perform database restore."
  # shutdown the new version.
  "${SCRIPTS_DIR}"/stop-lockss || logger_error_exit "Attempt to stop running PostgreSQL failed."
+
+	  restore_env
 }
 
 ###
@@ -241,14 +274,18 @@ Check_Configured
 
 logger_init
 check_versions
-DUMP_FILE="${OLD_VERSION}.dump"
-logger_info "Dumping contents of $OLD_VERSION of PostgreSQL to $LOCKSS_DATA_DIR/$stack-postgres-tmp/${DUMP_FILE}."
+
+DUMP_FILE_NAME="${OLD_VERSION}.dump"
+logger_info "Dumping contents of $OLD_VERSION of PostgreSQL to ${POSTGRES_TMP_DIR}/${DUMP_FILE_NAME}."
+DUMP_FILE="/tmp/${DUMP_FILE_NAME}"
+
 dump_old_version
-# wait for things to settle
-sleep 30
 logger_info "Successfully dumped data from $OLD_VERSION of PostgreSQL."
+
+# wait for things to settle
+sleep 5
 logger_info "Starting $NEW_VERSION of PostgreSQL to begin data restore."
-restore_dump || logger_error_exit "Attempt to restore data failed"
+restore_dump
 logger_info "Successfully restored data to $NEW_VERSION of PostgreSQL."
 logger_info "PostgreSQL upgrade completed."
 
